// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveAgents = `-- name: CountActiveAgents :one
SELECT COUNT(*) FROM agents WHERE org_id = $1 AND is_active = true
`

func (q *Queries) CountActiveAgents(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAgents, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deactivateAgent = `-- name: DeactivateAgent :execrows
UPDATE agents SET is_active = false WHERE org_id = $1 AND id = $2 AND is_active = true
`

type DeactivateAgentParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

// Soft delete — is_active=false, row stays for run history (Workflow 9+).
// :execrows (not :exec) so the handler can distinguish "deactivated" from
// "no such agent in this org" (0 rows) and return a real 404.
func (q *Queries) DeactivateAgent(ctx context.Context, arg DeactivateAgentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateAgent, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgent = `-- name: GetAgent :one
SELECT a.id, a.name, a.slug, a.description, a.agent_type, a.model, a.system_prompt,
       a.context_window_tokens, a.max_output_tokens, a.temperature,
       a.policy_scope, a.allowed_mcp_servers, a.is_active, a.version,
       a.created_at, a.updated_at,
       (SELECT COUNT(*) FROM workflows w WHERE w.agent_id = a.id AND w.is_active = true) AS workflow_count
FROM agents a
WHERE a.org_id = $1 AND a.id = $2
`

type GetAgentParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

type GetAgentRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	Slug                string             `json:"slug"`
	Description         *string            `json:"description"`
	AgentType           string             `json:"agent_type"`
	Model               *string            `json:"model"`
	SystemPrompt        string             `json:"system_prompt"`
	ContextWindowTokens *int32             `json:"context_window_tokens"`
	MaxOutputTokens     *int32             `json:"max_output_tokens"`
	Temperature         *float64           `json:"temperature"`
	PolicyScope         []byte             `json:"policy_scope"`
	AllowedMcpServers   []byte             `json:"allowed_mcp_servers"`
	IsActive            *bool              `json:"is_active"`
	Version             *int32             `json:"version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	WorkflowCount       int64              `json:"workflow_count"`
}

func (q *Queries) GetAgent(ctx context.Context, arg GetAgentParams) (GetAgentRow, error) {
	row := q.db.QueryRow(ctx, getAgent, arg.OrgID, arg.ID)
	var i GetAgentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.AgentType,
		&i.Model,
		&i.SystemPrompt,
		&i.ContextWindowTokens,
		&i.MaxOutputTokens,
		&i.Temperature,
		&i.PolicyScope,
		&i.AllowedMcpServers,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkflowCount,
	)
	return i, err
}

const getOrganizationMaxAgents = `-- name: GetOrganizationMaxAgents :one
SELECT max_agents FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationMaxAgents(ctx context.Context, id pgtype.UUID) (*int32, error) {
	row := q.db.QueryRow(ctx, getOrganizationMaxAgents, id)
	var max_agents *int32
	err := row.Scan(&max_agents)
	return max_agents, err
}

const insertAgent = `-- name: InsertAgent :one
INSERT INTO agents (
    org_id, name, slug, description, agent_type, model, system_prompt,
    max_output_tokens, temperature, policy_scope, allowed_mcp_servers, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (org_id, name) WHERE is_active = true DO NOTHING
RETURNING id, name, slug, description, agent_type, model, system_prompt,
    context_window_tokens, max_output_tokens, temperature,
    policy_scope, allowed_mcp_servers, is_active, version,
    created_at, updated_at
`

type InsertAgentParams struct {
	OrgID             pgtype.UUID `json:"org_id"`
	Name              string      `json:"name"`
	Slug              string      `json:"slug"`
	Description       *string     `json:"description"`
	AgentType         string      `json:"agent_type"`
	Model             *string     `json:"model"`
	SystemPrompt      string      `json:"system_prompt"`
	MaxOutputTokens   *int32      `json:"max_output_tokens"`
	Temperature       *float64    `json:"temperature"`
	PolicyScope       []byte      `json:"policy_scope"`
	AllowedMcpServers []byte      `json:"allowed_mcp_servers"`
	CreatedBy         pgtype.UUID `json:"created_by"`
}

type InsertAgentRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	Slug                string             `json:"slug"`
	Description         *string            `json:"description"`
	AgentType           string             `json:"agent_type"`
	Model               *string            `json:"model"`
	SystemPrompt        string             `json:"system_prompt"`
	ContextWindowTokens *int32             `json:"context_window_tokens"`
	MaxOutputTokens     *int32             `json:"max_output_tokens"`
	Temperature         *float64           `json:"temperature"`
	PolicyScope         []byte             `json:"policy_scope"`
	AllowedMcpServers   []byte             `json:"allowed_mcp_servers"`
	IsActive            *bool              `json:"is_active"`
	Version             *int32             `json:"version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

// ON CONFLICT ... DO NOTHING against the partial unique index added in
// 000006_agents_unique_org_name_active: a real duplicate name returns 0
// rows (pgx.ErrNoRows on the :one Scan), which the handler translates to a
// 400 DUPLICATE_AGENT_NAME rather than a generic 500.
func (q *Queries) InsertAgent(ctx context.Context, arg InsertAgentParams) (InsertAgentRow, error) {
	row := q.db.QueryRow(ctx, insertAgent,
		arg.OrgID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.AgentType,
		arg.Model,
		arg.SystemPrompt,
		arg.MaxOutputTokens,
		arg.Temperature,
		arg.PolicyScope,
		arg.AllowedMcpServers,
		arg.CreatedBy,
	)
	var i InsertAgentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.AgentType,
		&i.Model,
		&i.SystemPrompt,
		&i.ContextWindowTokens,
		&i.MaxOutputTokens,
		&i.Temperature,
		&i.PolicyScope,
		&i.AllowedMcpServers,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many

SELECT a.id, a.name, a.slug, a.description, a.agent_type, a.model, a.system_prompt,
       a.context_window_tokens, a.max_output_tokens, a.temperature,
       a.policy_scope, a.allowed_mcp_servers, a.is_active, a.version,
       a.created_at, a.updated_at,
       (SELECT COUNT(*) FROM workflows w WHERE w.agent_id = a.id AND w.is_active = true) AS workflow_count
FROM agents a
WHERE a.org_id = $1 AND a.is_active = true
ORDER BY a.created_at DESC
`

type ListAgentsRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	Slug                string             `json:"slug"`
	Description         *string            `json:"description"`
	AgentType           string             `json:"agent_type"`
	Model               *string            `json:"model"`
	SystemPrompt        string             `json:"system_prompt"`
	ContextWindowTokens *int32             `json:"context_window_tokens"`
	MaxOutputTokens     *int32             `json:"max_output_tokens"`
	Temperature         *float64           `json:"temperature"`
	PolicyScope         []byte             `json:"policy_scope"`
	AllowedMcpServers   []byte             `json:"allowed_mcp_servers"`
	IsActive            *bool              `json:"is_active"`
	Version             *int32             `json:"version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	WorkflowCount       int64              `json:"workflow_count"`
}

// Queries backing workflow 7 (agent configuration CRUD). All tenant-scoped,
// run through app_user via tenant.WithTx like every other feature area in
// this file set — nothing here is cross-tenant, unlike the recovery-sweep
// style queries elsewhere.
// workflow_count (added for workflow 8's "deleting an agent that has
// workflows shows a warning" acceptance criterion) is a correlated
// subquery, not a JOIN + GROUP BY — an agent with 0 workflows must still
// appear exactly once, and a JOIN would either drop it (INNER) or need the
// GROUP BY/aggregate dance anyway for no real benefit at this scale.
func (q *Queries) ListAgents(ctx context.Context, orgID pgtype.UUID) ([]ListAgentsRow, error) {
	rows, err := q.db.Query(ctx, listAgents, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentsRow
	for rows.Next() {
		var i ListAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.AgentType,
			&i.Model,
			&i.SystemPrompt,
			&i.ContextWindowTokens,
			&i.MaxOutputTokens,
			&i.Temperature,
			&i.PolicyScope,
			&i.AllowedMcpServers,
			&i.IsActive,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkflowCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    agent_type = COALESCE($3, agent_type),
    model = COALESCE($4, model),
    system_prompt = COALESCE($5, system_prompt),
    max_output_tokens = COALESCE($6, max_output_tokens),
    temperature = COALESCE($7, temperature),
    policy_scope = COALESCE($8, policy_scope),
    allowed_mcp_servers = COALESCE($9, allowed_mcp_servers),
    version = version + 1
WHERE org_id = $10 AND id = $11
RETURNING id, name, slug, description, agent_type, model, system_prompt,
    context_window_tokens, max_output_tokens, temperature,
    policy_scope, allowed_mcp_servers, is_active, version,
    created_at, updated_at
`

type UpdateAgentParams struct {
	Name              *string     `json:"name"`
	Description       *string     `json:"description"`
	AgentType         *string     `json:"agent_type"`
	Model             *string     `json:"model"`
	SystemPrompt      *string     `json:"system_prompt"`
	MaxOutputTokens   *int32      `json:"max_output_tokens"`
	Temperature       *float64    `json:"temperature"`
	PolicyScope       []byte      `json:"policy_scope"`
	AllowedMcpServers []byte      `json:"allowed_mcp_servers"`
	OrgID             pgtype.UUID `json:"org_id"`
	ID                pgtype.UUID `json:"id"`
}

type UpdateAgentRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	Slug                string             `json:"slug"`
	Description         *string            `json:"description"`
	AgentType           string             `json:"agent_type"`
	Model               *string            `json:"model"`
	SystemPrompt        string             `json:"system_prompt"`
	ContextWindowTokens *int32             `json:"context_window_tokens"`
	MaxOutputTokens     *int32             `json:"max_output_tokens"`
	Temperature         *float64           `json:"temperature"`
	PolicyScope         []byte             `json:"policy_scope"`
	AllowedMcpServers   []byte             `json:"allowed_mcp_servers"`
	IsActive            *bool              `json:"is_active"`
	Version             *int32             `json:"version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

// Partial update via COALESCE against sqlc.narg — every field is optional
// on the PATCH wire contract; only the ones actually present in the
// request are non-nil here. A rename that collides with another active
// agent's name still hits the 000006 partial unique index (COALESCE can't
// route around a real constraint), surfacing as a Postgres 23505 the
// handler translates the same way InsertAgent's ON CONFLICT branch does.
func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (UpdateAgentRow, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.Name,
		arg.Description,
		arg.AgentType,
		arg.Model,
		arg.SystemPrompt,
		arg.MaxOutputTokens,
		arg.Temperature,
		arg.PolicyScope,
		arg.AllowedMcpServers,
		arg.OrgID,
		arg.ID,
	)
	var i UpdateAgentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.AgentType,
		&i.Model,
		&i.SystemPrompt,
		&i.ContextWindowTokens,
		&i.MaxOutputTokens,
		&i.Temperature,
		&i.PolicyScope,
		&i.AllowedMcpServers,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
