// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCostLedger = `-- name: CountCostLedger :one
SELECT count(*) FROM cost_ledger WHERE org_id = $1
`

func (q *Queries) CountCostLedger(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCostLedger, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAgentCostShare = `-- name: GetAgentCostShare :many
SELECT
    COALESCE(a.name, 'Unattributed') AS agent_name,
    COALESCE(SUM(cl.estimated_cost_usd), 0)::double precision AS total_cost_usd
FROM cost_ledger cl
LEFT JOIN agents a ON a.id = cl.agent_id
WHERE cl.org_id = $1 AND cl.created_at >= $2
GROUP BY a.name
ORDER BY total_cost_usd DESC
`

type GetAgentCostShareParams struct {
	OrgID     pgtype.UUID        `json:"org_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GetAgentCostShareRow struct {
	AgentName    string  `json:"agent_name"`
	TotalCostUsd float64 `json:"total_cost_usd"`
}

// Per-agent cost share (last 30 days) for GET /billing/usage's bar chart.
// agent_id is nullable on cost_ledger (a run's tool-call/llm cost rows
// always set it, but nothing else does yet) — LEFT JOIN keeps those rows
// visible under a synthetic "Unattributed" bucket rather than silently
// dropping real spend from the total.
func (q *Queries) GetAgentCostShare(ctx context.Context, arg GetAgentCostShareParams) ([]GetAgentCostShareRow, error) {
	rows, err := q.db.Query(ctx, getAgentCostShare, arg.OrgID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAgentCostShareRow
	for rows.Next() {
		var i GetAgentCostShareRow
		if err := rows.Scan(&i.AgentName, &i.TotalCostUsd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAgentPerformance = `-- name: GetAgentPerformance :many
SELECT
    a.id AS agent_id,
    a.name AS agent_name,
    count(wr.id)::bigint AS total_runs,
    count(*) FILTER (WHERE wr.status = 'completed')::bigint AS success_count,
    count(*) FILTER (WHERE wr.status = 'failed')::bigint AS failure_count,
    COALESCE(AVG(wr.duration_ms) FILTER (WHERE wr.duration_ms IS NOT NULL), 0)::double precision AS avg_duration_ms,
    COALESCE(AVG(wr.cost_so_far_usd), 0)::double precision AS avg_cost_usd
FROM agents a
JOIN workflows w ON w.agent_id = a.id
JOIN workflow_runs wr ON wr.workflow_id = w.id
WHERE a.org_id = $1
GROUP BY a.id, a.name
ORDER BY total_runs DESC
`

type GetAgentPerformanceRow struct {
	AgentID       pgtype.UUID `json:"agent_id"`
	AgentName     string      `json:"agent_name"`
	TotalRuns     int64       `json:"total_runs"`
	SuccessCount  int64       `json:"success_count"`
	FailureCount  int64       `json:"failure_count"`
	AvgDurationMs float64     `json:"avg_duration_ms"`
	AvgCostUsd    float64     `json:"avg_cost_usd"`
}

// GET /analytics/agent-performance. success_count/failure_count are
// separate columns (not one status column) so the handler never has to
// special-case pending/running/awaiting_approval rows to compute a rate.
func (q *Queries) GetAgentPerformance(ctx context.Context, orgID pgtype.UUID) ([]GetAgentPerformanceRow, error) {
	rows, err := q.db.Query(ctx, getAgentPerformance, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAgentPerformanceRow
	for rows.Next() {
		var i GetAgentPerformanceRow
		if err := rows.Scan(
			&i.AgentID,
			&i.AgentName,
			&i.TotalRuns,
			&i.SuccessCount,
			&i.FailureCount,
			&i.AvgDurationMs,
			&i.AvgCostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCostUsageSince = `-- name: GetCostUsageSince :one

SELECT
    COALESCE(SUM(input_tokens), 0)::bigint AS input_tokens,
    COALESCE(SUM(output_tokens), 0)::bigint AS output_tokens,
    COALESCE(SUM(cached_tokens), 0)::bigint AS cached_tokens,
    COALESCE(SUM(thinking_tokens), 0)::bigint AS thinking_tokens,
    COALESCE(SUM(estimated_cost_usd), 0)::double precision AS total_estimated_usd
FROM cost_ledger
WHERE org_id = $1 AND created_at >= $2
`

type GetCostUsageSinceParams struct {
	OrgID     pgtype.UUID        `json:"org_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GetCostUsageSinceRow struct {
	InputTokens       int64   `json:"input_tokens"`
	OutputTokens      int64   `json:"output_tokens"`
	CachedTokens      int64   `json:"cached_tokens"`
	ThinkingTokens    int64   `json:"thinking_tokens"`
	TotalEstimatedUsd float64 `json:"total_estimated_usd"`
}

// Workflow 14 (token usage & analytics). All read-only, all against
// app_user/tenant.WithTx like every other tenant-scoped query in this
// codebase — RLS already scopes these by org, the explicit org_id
// parameter matches this codebase's existing belt-and-suspenders
// convention (see e.g. workflows.sql's ListWorkflows).
// Monthly aggregate for GET /settings/api-key/usage and the headline
// figures on GET /billing/usage.
func (q *Queries) GetCostUsageSince(ctx context.Context, arg GetCostUsageSinceParams) (GetCostUsageSinceRow, error) {
	row := q.db.QueryRow(ctx, getCostUsageSince, arg.OrgID, arg.CreatedAt)
	var i GetCostUsageSinceRow
	err := row.Scan(
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedTokens,
		&i.ThinkingTokens,
		&i.TotalEstimatedUsd,
	)
	return i, err
}

const getDailyCostUsage = `-- name: GetDailyCostUsage :many
SELECT
    date_trunc('day', created_at)::date AS day,
    COALESCE(SUM(input_tokens), 0)::bigint AS input_tokens,
    COALESCE(SUM(output_tokens), 0)::bigint AS output_tokens,
    COALESCE(SUM(cached_tokens), 0)::bigint AS cached_tokens,
    COALESCE(SUM(estimated_cost_usd), 0)::double precision AS estimated_cost_usd
FROM cost_ledger
WHERE org_id = $1 AND created_at >= $2
GROUP BY day
ORDER BY day
`

type GetDailyCostUsageParams struct {
	OrgID     pgtype.UUID        `json:"org_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GetDailyCostUsageRow struct {
	Day              pgtype.Date `json:"day"`
	InputTokens      int64       `json:"input_tokens"`
	OutputTokens     int64       `json:"output_tokens"`
	CachedTokens     int64       `json:"cached_tokens"`
	EstimatedCostUsd float64     `json:"estimated_cost_usd"`
}

// Daily breakdown (last 30 days) for GET /billing/usage's trend chart —
// one row per day that actually had activity, not a zero-filled series
// for every calendar day (the handler fills gaps itself, since a query
// can't easily manufacture rows for days with zero cost_ledger activity).
func (q *Queries) GetDailyCostUsage(ctx context.Context, arg GetDailyCostUsageParams) ([]GetDailyCostUsageRow, error) {
	rows, err := q.db.Query(ctx, getDailyCostUsage, arg.OrgID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyCostUsageRow
	for rows.Next() {
		var i GetDailyCostUsageRow
		if err := rows.Scan(
			&i.Day,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedTokens,
			&i.EstimatedCostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRagQualityStats = `-- name: GetRagQualityStats :one
SELECT
    COALESCE(AVG((metadata_info->>'avg_rerank_score')::double precision), 0)::double precision AS avg_rerank_score,
    COALESCE(AVG((metadata_info->>'result_count')::double precision), 0)::double precision AS avg_chunks_retrieved,
    COALESCE(
        AVG((metadata_info->>'from_cache')::boolean::int)::double precision,
        0
    )::double precision AS cache_hit_rate,
    count(*)::bigint AS total_searches
FROM audit_logs
WHERE org_id = $1 AND action = 'rag.search' AND created_at >= $2
`

type GetRagQualityStatsParams struct {
	OrgID     pgtype.UUID        `json:"org_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GetRagQualityStatsRow struct {
	AvgRerankScore     float64 `json:"avg_rerank_score"`
	AvgChunksRetrieved float64 `json:"avg_chunks_retrieved"`
	CacheHitRate       float64 `json:"cache_hit_rate"`
	TotalSearches      int64   `json:"total_searches"`
}

// GET /analytics/rag-quality. Sourced from audit_logs' rag.search rows —
// the only place avg_rerank_score/from_cache/result_count are recorded at
// all (see internal/api/documents/handler.go's auditSearch); a search
// with 0 results (the ACL-empty short-circuit) contributes a 0 to
// avg_rerank_score/avg_chunks_retrieved, which is the correct average,
// not a value worth excluding.
func (q *Queries) GetRagQualityStats(ctx context.Context, arg GetRagQualityStatsParams) (GetRagQualityStatsRow, error) {
	row := q.db.QueryRow(ctx, getRagQualityStats, arg.OrgID, arg.CreatedAt)
	var i GetRagQualityStatsRow
	err := row.Scan(
		&i.AvgRerankScore,
		&i.AvgChunksRetrieved,
		&i.CacheHitRate,
		&i.TotalSearches,
	)
	return i, err
}

const listCostLedgerPage = `-- name: ListCostLedgerPage :many
SELECT id, created_at, cost_type, provider, model, run_id, agent_id,
       input_tokens, output_tokens, cached_tokens, thinking_tokens, estimated_cost_usd
FROM cost_ledger
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCostLedgerPageParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListCostLedgerPageRow struct {
	ID               pgtype.UUID        `json:"id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	CostType         string             `json:"cost_type"`
	Provider         *string            `json:"provider"`
	Model            *string            `json:"model"`
	RunID            pgtype.UUID        `json:"run_id"`
	AgentID          pgtype.UUID        `json:"agent_id"`
	InputTokens      *int32             `json:"input_tokens"`
	OutputTokens     *int32             `json:"output_tokens"`
	CachedTokens     *int32             `json:"cached_tokens"`
	ThinkingTokens   *int32             `json:"thinking_tokens"`
	EstimatedCostUsd float64            `json:"estimated_cost_usd"`
}

// Paginated GET /billing/ledger.
func (q *Queries) ListCostLedgerPage(ctx context.Context, arg ListCostLedgerPageParams) ([]ListCostLedgerPageRow, error) {
	rows, err := q.db.Query(ctx, listCostLedgerPage, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCostLedgerPageRow
	for rows.Next() {
		var i ListCostLedgerPageRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.CostType,
			&i.Provider,
			&i.Model,
			&i.RunID,
			&i.AgentID,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedTokens,
			&i.ThinkingTokens,
			&i.EstimatedCostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
