// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearOrganizationActiveApiKey = `-- name: ClearOrganizationActiveApiKey :exec
UPDATE organizations SET active_api_key_id = NULL WHERE id = $1
`

func (q *Queries) ClearOrganizationActiveApiKey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearOrganizationActiveApiKey, id)
	return err
}

const deactivateAnthropicKey = `-- name: DeactivateAnthropicKey :execrows
UPDATE api_key_registry SET is_valid = false WHERE org_id = $1 AND provider = 'anthropic'
`

func (q *Queries) DeactivateAnthropicKey(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateAnthropicKey, orgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveAnthropicKeyByOrgID = `-- name: GetActiveAnthropicKeyByOrgID :one

SELECT id, encrypted_key, key_prefix, is_valid
FROM api_key_registry
WHERE org_id = $1 AND provider = 'anthropic' AND is_valid = true
`

type GetActiveAnthropicKeyByOrgIDRow struct {
	ID           pgtype.UUID `json:"id"`
	EncryptedKey string      `json:"encrypted_key"`
	KeyPrefix    string      `json:"key_prefix"`
	IsValid      *bool       `json:"is_valid"`
}

// Queries backing BYOK API key management (workflow 3). Run through
// app_user via tenant.WithTx — this is genuinely tenant-scoped data, not a
// system-context lookup like clerk_sync.sql or auth.sql.
func (q *Queries) GetActiveAnthropicKeyByOrgID(ctx context.Context, orgID pgtype.UUID) (GetActiveAnthropicKeyByOrgIDRow, error) {
	row := q.db.QueryRow(ctx, getActiveAnthropicKeyByOrgID, orgID)
	var i GetActiveAnthropicKeyByOrgIDRow
	err := row.Scan(
		&i.ID,
		&i.EncryptedKey,
		&i.KeyPrefix,
		&i.IsValid,
	)
	return i, err
}

const getAnthropicKeyStatus = `-- name: GetAnthropicKeyStatus :one
SELECT provider, is_valid, key_prefix, updated_at, last_used_at
FROM api_key_registry
WHERE org_id = $1 AND provider = 'anthropic'
`

type GetAnthropicKeyStatusRow struct {
	Provider   string             `json:"provider"`
	IsValid    *bool              `json:"is_valid"`
	KeyPrefix  string             `json:"key_prefix"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) GetAnthropicKeyStatus(ctx context.Context, orgID pgtype.UUID) (GetAnthropicKeyStatusRow, error) {
	row := q.db.QueryRow(ctx, getAnthropicKeyStatus, orgID)
	var i GetAnthropicKeyStatusRow
	err := row.Scan(
		&i.Provider,
		&i.IsValid,
		&i.KeyPrefix,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const setOrganizationActiveApiKey = `-- name: SetOrganizationActiveApiKey :exec
UPDATE organizations SET active_api_key_id = $2, onboarding_completed = true WHERE id = $1
`

type SetOrganizationActiveApiKeyParams struct {
	ID             pgtype.UUID `json:"id"`
	ActiveApiKeyID pgtype.UUID `json:"active_api_key_id"`
}

func (q *Queries) SetOrganizationActiveApiKey(ctx context.Context, arg SetOrganizationActiveApiKeyParams) error {
	_, err := q.db.Exec(ctx, setOrganizationActiveApiKey, arg.ID, arg.ActiveApiKeyID)
	return err
}

const upsertAnthropicKey = `-- name: UpsertAnthropicKey :one
INSERT INTO api_key_registry (org_id, provider, key_prefix, encrypted_key, kms_key_id, is_valid)
VALUES ($1, 'anthropic', $2, $3, $4, true)
ON CONFLICT (org_id, provider) DO UPDATE SET
    key_prefix = EXCLUDED.key_prefix,
    encrypted_key = EXCLUDED.encrypted_key,
    kms_key_id = EXCLUDED.kms_key_id,
    is_valid = true
RETURNING id
`

type UpsertAnthropicKeyParams struct {
	OrgID        pgtype.UUID `json:"org_id"`
	KeyPrefix    string      `json:"key_prefix"`
	EncryptedKey string      `json:"encrypted_key"`
	KmsKeyID     string      `json:"kms_key_id"`
}

func (q *Queries) UpsertAnthropicKey(ctx context.Context, arg UpsertAnthropicKeyParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertAnthropicKey,
		arg.OrgID,
		arg.KeyPrefix,
		arg.EncryptedKey,
		arg.KmsKeyID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
