// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: approvals.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePushSubscription = `-- name: DeletePushSubscription :exec
DELETE FROM push_subscriptions WHERE org_id = $1 AND user_id = $2 AND endpoint = $3
`

type DeletePushSubscriptionParams struct {
	OrgID    pgtype.UUID `json:"org_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Endpoint string      `json:"endpoint"`
}

func (q *Queries) DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deletePushSubscription, arg.OrgID, arg.UserID, arg.Endpoint)
	return err
}

const getApproval = `-- name: GetApproval :one
SELECT id, run_id, org_id, status, risk_level, context_data, expires_at, created_at
FROM approvals
WHERE org_id = $1 AND id = $2
`

type GetApprovalParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

type GetApprovalRow struct {
	ID          pgtype.UUID        `json:"id"`
	RunID       pgtype.UUID        `json:"run_id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Status      *string            `json:"status"`
	RiskLevel   *string            `json:"risk_level"`
	ContextData []byte             `json:"context_data"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetApproval(ctx context.Context, arg GetApprovalParams) (GetApprovalRow, error) {
	row := q.db.QueryRow(ctx, getApproval, arg.OrgID, arg.ID)
	var i GetApprovalRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.OrgID,
		&i.Status,
		&i.RiskLevel,
		&i.ContextData,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getApprovalSystemScoped = `-- name: GetApprovalSystemScoped :one
SELECT id, run_id, org_id, status, risk_level, context_data, expires_at, created_at
FROM approvals
WHERE id = $1
`

type GetApprovalSystemScopedRow struct {
	ID          pgtype.UUID        `json:"id"`
	RunID       pgtype.UUID        `json:"run_id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Status      *string            `json:"status"`
	RiskLevel   *string            `json:"risk_level"`
	ContextData []byte             `json:"context_data"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// GetApprovalSystemScoped runs on app_system (BYPASSRLS) — the
// action-token approve/reject path (internal/api/approvals/handler.go)
// has no tenant context yet at this point (an unauthenticated caller
// can't SET LOCAL app.current_org_id for an org it hasn't proven it
// belongs to), the same chicken-and-egg reasoning as
// internal/api/middleware/auth.go's RequireAuth resolving identity before
// any org context exists. Scoped by primary key only; every write that
// follows still goes through the normal org-scoped path once org_id is
// known from this row.
func (q *Queries) GetApprovalSystemScoped(ctx context.Context, id pgtype.UUID) (GetApprovalSystemScopedRow, error) {
	row := q.db.QueryRow(ctx, getApprovalSystemScoped, id)
	var i GetApprovalSystemScopedRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.OrgID,
		&i.Status,
		&i.RiskLevel,
		&i.ContextData,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgApprovalsSlackChannel = `-- name: GetOrgApprovalsSlackChannel :one
SELECT approvals_slack_channel_id FROM organizations WHERE id = $1
`

func (q *Queries) GetOrgApprovalsSlackChannel(ctx context.Context, id pgtype.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, getOrgApprovalsSlackChannel, id)
	var approvals_slack_channel_id *string
	err := row.Scan(&approvals_slack_channel_id)
	return approvals_slack_channel_id, err
}

const getUserApprovalPermissions = `-- name: GetUserApprovalPermissions :one
SELECT id, org_id, email, can_approve_workflows FROM users
WHERE id = $1 AND is_active = true
`

type GetUserApprovalPermissionsRow struct {
	ID                  pgtype.UUID `json:"id"`
	OrgID               pgtype.UUID `json:"org_id"`
	Email               string      `json:"email"`
	CanApproveWorkflows *bool       `json:"can_approve_workflows"`
}

// GetUserApprovalPermissions backs both the authenticated and the
// action-token approve/reject paths (internal/api/approvals/handler.go) —
// neither authctx.User nor a Clerk JWT carries can_approve_workflows, so
// this is looked up fresh at decision time rather than cached on the
// request context.
func (q *Queries) GetUserApprovalPermissions(ctx context.Context, id pgtype.UUID) (GetUserApprovalPermissionsRow, error) {
	row := q.db.QueryRow(ctx, getUserApprovalPermissions, id)
	var i GetUserApprovalPermissionsRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.CanApproveWorkflows,
	)
	return i, err
}

const insertApproval = `-- name: InsertApproval :one

INSERT INTO approvals (run_id, org_id, status, risk_level, context_data, expires_at)
VALUES ($1, $2, 'pending', $3, $4, $5)
RETURNING id
`

type InsertApprovalParams struct {
	RunID       pgtype.UUID        `json:"run_id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	RiskLevel   *string            `json:"risk_level"`
	ContextData []byte             `json:"context_data"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// Workflow 10: approvals/approval_decisions writes (internal/core/graph's
// writeApprovalGate, internal/api/approvals' handler), notification lookups
// (internal/core/notify), and the 24h expiry sweep
// (internal/core/workflows/approvalexpiry.go). InsertApproval/GetApproval/
// ListApprovalsForOrg/UpdateApprovalStatus/InsertApprovalDecision run
// through tenant.WithTx (app_user) except ListExpiredPendingApprovals,
// which is inherently cross-org and runs on app_system, same reasoning as
// every other background sweep in this codebase.
func (q *Queries) InsertApproval(ctx context.Context, arg InsertApprovalParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertApproval,
		arg.RunID,
		arg.OrgID,
		arg.RiskLevel,
		arg.ContextData,
		arg.ExpiresAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertApprovalDecision = `-- name: InsertApprovalDecision :exec
INSERT INTO approval_decisions (approval_id, user_id, decision, reason)
VALUES ($1, $2, $3, $4)
`

type InsertApprovalDecisionParams struct {
	ApprovalID pgtype.UUID `json:"approval_id"`
	UserID     pgtype.UUID `json:"user_id"`
	Decision   string      `json:"decision"`
	Reason     *string     `json:"reason"`
}

func (q *Queries) InsertApprovalDecision(ctx context.Context, arg InsertApprovalDecisionParams) error {
	_, err := q.db.Exec(ctx, insertApprovalDecision,
		arg.ApprovalID,
		arg.UserID,
		arg.Decision,
		arg.Reason,
	)
	return err
}

const listApprovalsForOrg = `-- name: ListApprovalsForOrg :many
SELECT id, run_id, org_id, status, risk_level, context_data, expires_at, created_at
FROM approvals
WHERE org_id = $1
  AND ($4::varchar IS NULL OR status = $4)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListApprovalsForOrgParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Status *string     `json:"status"`
}

type ListApprovalsForOrgRow struct {
	ID          pgtype.UUID        `json:"id"`
	RunID       pgtype.UUID        `json:"run_id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Status      *string            `json:"status"`
	RiskLevel   *string            `json:"risk_level"`
	ContextData []byte             `json:"context_data"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListApprovalsForOrg(ctx context.Context, arg ListApprovalsForOrgParams) ([]ListApprovalsForOrgRow, error) {
	rows, err := q.db.Query(ctx, listApprovalsForOrg,
		arg.OrgID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApprovalsForOrgRow
	for rows.Next() {
		var i ListApprovalsForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.OrgID,
			&i.Status,
			&i.RiskLevel,
			&i.ContextData,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApproverEmailsForOrg = `-- name: ListApproverEmailsForOrg :many
SELECT id, email FROM users
WHERE org_id = $1 AND can_approve_workflows = true AND is_active = true
`

type ListApproverEmailsForOrgRow struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
}

func (q *Queries) ListApproverEmailsForOrg(ctx context.Context, orgID pgtype.UUID) ([]ListApproverEmailsForOrgRow, error) {
	rows, err := q.db.Query(ctx, listApproverEmailsForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApproverEmailsForOrgRow
	for rows.Next() {
		var i ListApproverEmailsForOrgRow
		if err := rows.Scan(&i.ID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredPendingApprovals = `-- name: ListExpiredPendingApprovals :many
SELECT id, run_id, org_id FROM approvals
WHERE status = 'pending' AND expires_at IS NOT NULL AND expires_at < now()
`

type ListExpiredPendingApprovalsRow struct {
	ID    pgtype.UUID `json:"id"`
	RunID pgtype.UUID `json:"run_id"`
	OrgID pgtype.UUID `json:"org_id"`
}

// ListExpiredPendingApprovals runs on app_system (BYPASSRLS) — sweeping
// expirations across every org is inherently cross-tenant, same reasoning
// as internal/core/integrations/refresh.go's RunRefreshJob.
func (q *Queries) ListExpiredPendingApprovals(ctx context.Context) ([]ListExpiredPendingApprovalsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredPendingApprovals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredPendingApprovalsRow
	for rows.Next() {
		var i ListExpiredPendingApprovalsRow
		if err := rows.Scan(&i.ID, &i.RunID, &i.OrgID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushSubscriptionsForOrg = `-- name: ListPushSubscriptionsForOrg :many
SELECT id, user_id, endpoint, p256dh_key, auth_key FROM push_subscriptions WHERE org_id = $1
`

type ListPushSubscriptionsForOrgRow struct {
	ID        pgtype.UUID `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	Endpoint  string      `json:"endpoint"`
	P256dhKey string      `json:"p256dh_key"`
	AuthKey   string      `json:"auth_key"`
}

func (q *Queries) ListPushSubscriptionsForOrg(ctx context.Context, orgID pgtype.UUID) ([]ListPushSubscriptionsForOrgRow, error) {
	rows, err := q.db.Query(ctx, listPushSubscriptionsForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPushSubscriptionsForOrgRow
	for rows.Next() {
		var i ListPushSubscriptionsForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dhKey,
			&i.AuthKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApprovalStatus = `-- name: UpdateApprovalStatus :execrows
UPDATE approvals SET status = $3
WHERE org_id = $1 AND id = $2 AND status = 'pending'
`

type UpdateApprovalStatusParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	ID     pgtype.UUID `json:"id"`
	Status *string     `json:"status"`
}

func (q *Queries) UpdateApprovalStatus(ctx context.Context, arg UpdateApprovalStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateApprovalStatus, arg.OrgID, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOrgApprovalsSlackChannel = `-- name: UpdateOrgApprovalsSlackChannel :exec
UPDATE organizations SET approvals_slack_channel_id = $2 WHERE id = $1
`

type UpdateOrgApprovalsSlackChannelParams struct {
	ID                      pgtype.UUID `json:"id"`
	ApprovalsSlackChannelID *string     `json:"approvals_slack_channel_id"`
}

func (q *Queries) UpdateOrgApprovalsSlackChannel(ctx context.Context, arg UpdateOrgApprovalsSlackChannelParams) error {
	_, err := q.db.Exec(ctx, updateOrgApprovalsSlackChannel, arg.ID, arg.ApprovalsSlackChannelID)
	return err
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :exec
INSERT INTO push_subscriptions (org_id, user_id, endpoint, p256dh_key, auth_key)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (org_id, user_id, endpoint) DO UPDATE
SET p256dh_key = EXCLUDED.p256dh_key, auth_key = EXCLUDED.auth_key
`

type UpsertPushSubscriptionParams struct {
	OrgID     pgtype.UUID `json:"org_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Endpoint  string      `json:"endpoint"`
	P256dhKey string      `json:"p256dh_key"`
	AuthKey   string      `json:"auth_key"`
}

func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, upsertPushSubscription,
		arg.OrgID,
		arg.UserID,
		arg.Endpoint,
		arg.P256dhKey,
		arg.AuthKey,
	)
	return err
}
