// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auditlogs.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAuditLogsPage = `-- name: ListAuditLogsPage :many

SELECT
    al.id, al.created_at, al.actor_type, al.actor_id,
    COALESCE(u.full_name, u.email, a.name, 'System') AS actor_name,
    al.action, al.resource_type, al.resource_id, al.status
FROM audit_logs al
LEFT JOIN users u ON al.actor_type = 'user' AND u.id = al.actor_id AND u.org_id = al.org_id
LEFT JOIN agents a ON al.actor_type = 'agent' AND a.id = al.actor_id AND a.org_id = al.org_id
WHERE al.org_id = $1
  AND ($2::varchar IS NULL OR al.actor_type = $2)
  AND ($3::varchar IS NULL OR al.action LIKE $3::varchar || '%')
  AND ($4::varchar IS NULL OR al.status = $4)
  AND ($5::timestamptz IS NULL OR al.created_at >= $5)
  AND ($6::timestamptz IS NULL OR al.created_at <= $6)
  AND (
    $7::timestamptz IS NULL
    OR (al.created_at, al.id) < ($7::timestamptz, $8::uuid)
  )
ORDER BY al.created_at DESC, al.id DESC
LIMIT $9
`

type ListAuditLogsPageParams struct {
	OrgID           pgtype.UUID        `json:"org_id"`
	ActorType       *string            `json:"actor_type"`
	ActionPrefix    *string            `json:"action_prefix"`
	Status          *string            `json:"status"`
	DateFrom        pgtype.Timestamptz `json:"date_from"`
	DateTo          pgtype.Timestamptz `json:"date_to"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

type ListAuditLogsPageRow struct {
	ID           pgtype.UUID        `json:"id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ActorType    string             `json:"actor_type"`
	ActorID      pgtype.UUID        `json:"actor_id"`
	ActorName    string             `json:"actor_name"`
	Action       string             `json:"action"`
	ResourceType *string            `json:"resource_type"`
	ResourceID   pgtype.UUID        `json:"resource_id"`
	Status       *string            `json:"status"`
}

// Workflow 17 (view audit logs). audit_logs itself has existed since
// migration 000001 and has been written to since workflows 9/10/12 - this
// is the first query that ever reads it back.
// Cursor-based (created_at, id) pagination, newest first - a plain
// LIMIT/OFFSET would skip/repeat rows if new entries land between page
// fetches (a real, ongoing concern here: agents write audit_logs
// continuously). Every filter is optional (sqlc.narg + "IS NULL OR ..."),
// matching this codebase's existing pattern (see documents.sql's
// ListSearchableDocumentIDs).
//
// actor_name resolves against whichever of users/agents actually owns
// actor_id for that row's actor_type, falling back to the literal
// 'System' when neither join matches (no current writer sets
// actor_type='system', but it's a valid value per the plan). The fallback
// is baked into SQL, not left to the Go handler: sqlc infers COALESCE's
// result nullability from its *last* argument's column, which would make
// actor_name a non-nullable Go string even though it's genuinely
// NULL-able here - the first real 'system' row would crash pgx's scan.
func (q *Queries) ListAuditLogsPage(ctx context.Context, arg ListAuditLogsPageParams) ([]ListAuditLogsPageRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogsPage,
		arg.OrgID,
		arg.ActorType,
		arg.ActionPrefix,
		arg.Status,
		arg.DateFrom,
		arg.DateTo,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogsPageRow
	for rows.Next() {
		var i ListAuditLogsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ActorType,
			&i.ActorID,
			&i.ActorName,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
