// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveOrganizationByClerkOrgID = `-- name: GetActiveOrganizationByClerkOrgID :one
SELECT id, name, slug, clerk_org_id, organization_type, parent_practice_id
FROM organizations WHERE clerk_org_id = $1 AND is_active = true
`

type GetActiveOrganizationByClerkOrgIDRow struct {
	ID               pgtype.UUID `json:"id"`
	Name             string      `json:"name"`
	Slug             string      `json:"slug"`
	ClerkOrgID       string      `json:"clerk_org_id"`
	OrganizationType string      `json:"organization_type"`
	ParentPracticeID pgtype.UUID `json:"parent_practice_id"`
}

func (q *Queries) GetActiveOrganizationByClerkOrgID(ctx context.Context, clerkOrgID string) (GetActiveOrganizationByClerkOrgIDRow, error) {
	row := q.db.QueryRow(ctx, getActiveOrganizationByClerkOrgID, clerkOrgID)
	var i GetActiveOrganizationByClerkOrgIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ClerkOrgID,
		&i.OrganizationType,
		&i.ParentPracticeID,
	)
	return i, err
}

const getActiveOrganizationByID = `-- name: GetActiveOrganizationByID :one
SELECT id, name, slug, clerk_org_id, organization_type, parent_practice_id
FROM organizations WHERE id = $1 AND is_active = true
`

type GetActiveOrganizationByIDRow struct {
	ID               pgtype.UUID `json:"id"`
	Name             string      `json:"name"`
	Slug             string      `json:"slug"`
	ClerkOrgID       string      `json:"clerk_org_id"`
	OrganizationType string      `json:"organization_type"`
	ParentPracticeID pgtype.UUID `json:"parent_practice_id"`
}

func (q *Queries) GetActiveOrganizationByID(ctx context.Context, id pgtype.UUID) (GetActiveOrganizationByIDRow, error) {
	row := q.db.QueryRow(ctx, getActiveOrganizationByID, id)
	var i GetActiveOrganizationByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ClerkOrgID,
		&i.OrganizationType,
		&i.ParentPracticeID,
	)
	return i, err
}

const getActiveUserInOrg = `-- name: GetActiveUserInOrg :one

SELECT id, org_id, role, can_manage_api_keys, can_manage_integrations
FROM users WHERE org_id = $1 AND clerk_user_id = $2 AND is_active = true
`

type GetActiveUserInOrgParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	ClerkUserID string      `json:"clerk_user_id"`
}

type GetActiveUserInOrgRow struct {
	ID                    pgtype.UUID `json:"id"`
	OrgID                 pgtype.UUID `json:"org_id"`
	Role                  string      `json:"role"`
	CanManageApiKeys      *bool       `json:"can_manage_api_keys"`
	CanManageIntegrations *bool       `json:"can_manage_integrations"`
}

// Queries backing request authentication (internal/api/middleware/auth.go).
// Run through app_system (BYPASSRLS): resolving "who is this JWT for, and
// which org do they belong to" is inherently a lookup that happens before
// any tenant context exists to scope an RLS-restricted query by — the same
// chicken-and-egg reasoning as the Clerk webhook's org creation.
// A person can hold one users row per org, so identity is always the
// (org_id, clerk_user_id) pair, never clerk_user_id alone.
func (q *Queries) GetActiveUserInOrg(ctx context.Context, arg GetActiveUserInOrgParams) (GetActiveUserInOrgRow, error) {
	row := q.db.QueryRow(ctx, getActiveUserInOrg, arg.OrgID, arg.ClerkUserID)
	var i GetActiveUserInOrgRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Role,
		&i.CanManageApiKeys,
		&i.CanManageIntegrations,
	)
	return i, err
}

const listActiveMembershipsByClerkUserID = `-- name: ListActiveMembershipsByClerkUserID :many
SELECT u.org_id, COALESCE(o.is_active, false)::boolean AS org_is_active
FROM users u
JOIN organizations o ON o.id = u.org_id
WHERE u.clerk_user_id = $1 AND u.is_active = true
`

type ListActiveMembershipsByClerkUserIDRow struct {
	OrgID       pgtype.UUID `json:"org_id"`
	OrgIsActive bool        `json:"org_is_active"`
}

// Fallback for a token carrying no active-org claim: only unambiguous when
// exactly one membership is in a still-active org.
func (q *Queries) ListActiveMembershipsByClerkUserID(ctx context.Context, clerkUserID string) ([]ListActiveMembershipsByClerkUserIDRow, error) {
	rows, err := q.db.Query(ctx, listActiveMembershipsByClerkUserID, clerkUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveMembershipsByClerkUserIDRow
	for rows.Next() {
		var i ListActiveMembershipsByClerkUserIDRow
		if err := rows.Scan(&i.OrgID, &i.OrgIsActive); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchLastLogin = `-- name: TouchLastLogin :exec
UPDATE users SET last_login_at = now()
WHERE id = $1 AND (last_login_at IS NULL OR last_login_at < now() - interval '5 minutes')
`

// Best-effort, fire-and-forget from RequireAuth — the WHERE guard keeps
// this to one write per user per 5 minutes, not one per request.
func (q *Queries) TouchLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchLastLogin, id)
	return err
}
