// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveOrganizationByID = `-- name: GetActiveOrganizationByID :one
SELECT id, name, slug FROM organizations WHERE id = $1 AND is_active = true
`

type GetActiveOrganizationByIDRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	Slug string      `json:"slug"`
}

func (q *Queries) GetActiveOrganizationByID(ctx context.Context, id pgtype.UUID) (GetActiveOrganizationByIDRow, error) {
	row := q.db.QueryRow(ctx, getActiveOrganizationByID, id)
	var i GetActiveOrganizationByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const getActiveUserByClerkUserID = `-- name: GetActiveUserByClerkUserID :one

SELECT id, org_id, role FROM users WHERE clerk_user_id = $1 AND is_active = true
`

type GetActiveUserByClerkUserIDRow struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
	Role  string      `json:"role"`
}

// Queries backing request authentication (internal/api/middleware/auth.go).
// Run through app_system (BYPASSRLS): resolving "who is this JWT for, and
// which org do they belong to" is inherently a lookup that happens before
// any tenant context exists to scope an RLS-restricted query by — the same
// chicken-and-egg reasoning as the Clerk webhook's org creation.
func (q *Queries) GetActiveUserByClerkUserID(ctx context.Context, clerkUserID string) (GetActiveUserByClerkUserIDRow, error) {
	row := q.db.QueryRow(ctx, getActiveUserByClerkUserID, clerkUserID)
	var i GetActiveUserByClerkUserIDRow
	err := row.Scan(&i.ID, &i.OrgID, &i.Role)
	return i, err
}
