// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applySubscriptionState = `-- name: ApplySubscriptionState :exec
UPDATE organizations SET
    plan_tier = $2, subscription_status = $3, stripe_subscription_id = $4,
    current_period_end = $5, cancel_at_period_end = $6, trial_ends_at = $7,
    max_agents = $8, max_workflows = $9, max_rag_storage_gb = $10, max_mcp_integrations = $11
WHERE id = $1
`

type ApplySubscriptionStateParams struct {
	ID                   pgtype.UUID        `json:"id"`
	PlanTier             *string            `json:"plan_tier"`
	SubscriptionStatus   *string            `json:"subscription_status"`
	StripeSubscriptionID *string            `json:"stripe_subscription_id"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	CancelAtPeriodEnd    bool               `json:"cancel_at_period_end"`
	TrialEndsAt          pgtype.Timestamptz `json:"trial_ends_at"`
	MaxAgents            *int32             `json:"max_agents"`
	MaxWorkflows         *int32             `json:"max_workflows"`
	MaxRagStorageGb      *int32             `json:"max_rag_storage_gb"`
	MaxMcpIntegrations   *int32             `json:"max_mcp_integrations"`
}

func (q *Queries) ApplySubscriptionState(ctx context.Context, arg ApplySubscriptionStateParams) error {
	_, err := q.db.Exec(ctx, applySubscriptionState,
		arg.ID,
		arg.PlanTier,
		arg.SubscriptionStatus,
		arg.StripeSubscriptionID,
		arg.CurrentPeriodEnd,
		arg.CancelAtPeriodEnd,
		arg.TrialEndsAt,
		arg.MaxAgents,
		arg.MaxWorkflows,
		arg.MaxRagStorageGb,
		arg.MaxMcpIntegrations,
	)
	return err
}

const countActiveWorkflows = `-- name: CountActiveWorkflows :one
SELECT COUNT(*) FROM workflows WHERE org_id = $1 AND is_active = true
`

func (q *Queries) CountActiveWorkflows(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveWorkflows, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOrgBilling = `-- name: GetOrgBilling :one
SELECT id, name, organization_type, plan_tier, subscription_status, trial_ends_at,
       current_period_end, cancel_at_period_end, stripe_customer_id, stripe_subscription_id,
       max_agents, max_workflows, max_rag_storage_gb, max_mcp_integrations
FROM organizations WHERE id = $1
`

type GetOrgBillingRow struct {
	ID                   pgtype.UUID        `json:"id"`
	Name                 string             `json:"name"`
	OrganizationType     string             `json:"organization_type"`
	PlanTier             *string            `json:"plan_tier"`
	SubscriptionStatus   *string            `json:"subscription_status"`
	TrialEndsAt          pgtype.Timestamptz `json:"trial_ends_at"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	CancelAtPeriodEnd    bool               `json:"cancel_at_period_end"`
	StripeCustomerID     *string            `json:"stripe_customer_id"`
	StripeSubscriptionID *string            `json:"stripe_subscription_id"`
	MaxAgents            *int32             `json:"max_agents"`
	MaxWorkflows         *int32             `json:"max_workflows"`
	MaxRagStorageGb      *int32             `json:"max_rag_storage_gb"`
	MaxMcpIntegrations   *int32             `json:"max_mcp_integrations"`
}

func (q *Queries) GetOrgBilling(ctx context.Context, id pgtype.UUID) (GetOrgBillingRow, error) {
	row := q.db.QueryRow(ctx, getOrgBilling, id)
	var i GetOrgBillingRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrganizationType,
		&i.PlanTier,
		&i.SubscriptionStatus,
		&i.TrialEndsAt,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.MaxAgents,
		&i.MaxWorkflows,
		&i.MaxRagStorageGb,
		&i.MaxMcpIntegrations,
	)
	return i, err
}

const getOrgBillingUsage = `-- name: GetOrgBillingUsage :one
SELECT
    (SELECT COUNT(*) FROM agents a WHERE a.org_id = $1 AND a.is_active = true)::bigint AS agents,
    (SELECT COUNT(*) FROM workflows w WHERE w.org_id = $1 AND w.is_active = true)::bigint AS workflows,
    (SELECT COALESCE(SUM(d.byte_size), 0) FROM documents d
        WHERE d.org_id = $1 AND d.processing_status <> 'deleting')::bigint AS storage_bytes,
    (SELECT COUNT(*) FROM mcp_connections m
        WHERE m.org_id = $1 AND m.is_active = true AND m.oauth_status = 'connected')::bigint AS integrations
`

type GetOrgBillingUsageRow struct {
	Agents       int64 `json:"agents"`
	Workflows    int64 `json:"workflows"`
	StorageBytes int64 `json:"storage_bytes"`
	Integrations int64 `json:"integrations"`
}

func (q *Queries) GetOrgBillingUsage(ctx context.Context, orgID pgtype.UUID) (GetOrgBillingUsageRow, error) {
	row := q.db.QueryRow(ctx, getOrgBillingUsage, orgID)
	var i GetOrgBillingUsageRow
	err := row.Scan(
		&i.Agents,
		&i.Workflows,
		&i.StorageBytes,
		&i.Integrations,
	)
	return i, err
}

const getOrgIDByStripeCustomer = `-- name: GetOrgIDByStripeCustomer :one
SELECT id FROM organizations WHERE stripe_customer_id = $1
`

func (q *Queries) GetOrgIDByStripeCustomer(ctx context.Context, stripeCustomerID *string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getOrgIDByStripeCustomer, stripeCustomerID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getOrgStorageAllowance = `-- name: GetOrgStorageAllowance :one
SELECT
    o.max_rag_storage_gb,
    (SELECT COALESCE(SUM(d.byte_size), 0) FROM documents d
        WHERE d.org_id = o.id AND d.processing_status <> 'deleting')::bigint AS used_bytes
FROM organizations o WHERE o.id = $1
`

type GetOrgStorageAllowanceRow struct {
	MaxRagStorageGb *int32 `json:"max_rag_storage_gb"`
	UsedBytes       int64  `json:"used_bytes"`
}

func (q *Queries) GetOrgStorageAllowance(ctx context.Context, id pgtype.UUID) (GetOrgStorageAllowanceRow, error) {
	row := q.db.QueryRow(ctx, getOrgStorageAllowance, id)
	var i GetOrgStorageAllowanceRow
	err := row.Scan(&i.MaxRagStorageGb, &i.UsedBytes)
	return i, err
}

const getOrganizationMaxWorkflows = `-- name: GetOrganizationMaxWorkflows :one
SELECT max_workflows FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationMaxWorkflows(ctx context.Context, id pgtype.UUID) (*int32, error) {
	row := q.db.QueryRow(ctx, getOrganizationMaxWorkflows, id)
	var max_workflows *int32
	err := row.Scan(&max_workflows)
	return max_workflows, err
}

const listOrgBillingContacts = `-- name: ListOrgBillingContacts :many
SELECT email, full_name FROM users
WHERE org_id = $1 AND is_active = true AND role IN ('owner', 'admin')
`

type ListOrgBillingContactsRow struct {
	Email    string  `json:"email"`
	FullName *string `json:"full_name"`
}

func (q *Queries) ListOrgBillingContacts(ctx context.Context, orgID pgtype.UUID) ([]ListOrgBillingContactsRow, error) {
	rows, err := q.db.Query(ctx, listOrgBillingContacts, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgBillingContactsRow
	for rows.Next() {
		var i ListOrgBillingContactsRow
		if err := rows.Scan(&i.Email, &i.FullName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrgSubscription = `-- name: LockOrgSubscription :one
SELECT stripe_subscription_id, subscription_status FROM organizations WHERE id = $1 FOR UPDATE
`

type LockOrgSubscriptionRow struct {
	StripeSubscriptionID *string `json:"stripe_subscription_id"`
	SubscriptionStatus   *string `json:"subscription_status"`
}

// Serializes concurrent webhook deliveries for one org, so "which
// subscription is current" is decided against the latest row.
func (q *Queries) LockOrgSubscription(ctx context.Context, id pgtype.UUID) (LockOrgSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, lockOrgSubscription, id)
	var i LockOrgSubscriptionRow
	err := row.Scan(&i.StripeSubscriptionID, &i.SubscriptionStatus)
	return i, err
}

const recordStripeEvent = `-- name: RecordStripeEvent :one
INSERT INTO stripe_events (id, type) VALUES ($1, $2)
ON CONFLICT (id) DO NOTHING
RETURNING id
`

type RecordStripeEventParams struct {
	ID   string `json:"id"`
	Type string `json:"type"`
}

// Returns no row when the event was already processed (a redelivery).
func (q *Queries) RecordStripeEvent(ctx context.Context, arg RecordStripeEventParams) (string, error) {
	row := q.db.QueryRow(ctx, recordStripeEvent, arg.ID, arg.Type)
	var id string
	err := row.Scan(&id)
	return id, err
}

const setOrgStripeCustomer = `-- name: SetOrgStripeCustomer :exec
UPDATE organizations SET stripe_customer_id = $2 WHERE id = $1
`

type SetOrgStripeCustomerParams struct {
	ID               pgtype.UUID `json:"id"`
	StripeCustomerID *string     `json:"stripe_customer_id"`
}

func (q *Queries) SetOrgStripeCustomer(ctx context.Context, arg SetOrgStripeCustomerParams) error {
	_, err := q.db.Exec(ctx, setOrgStripeCustomer, arg.ID, arg.StripeCustomerID)
	return err
}
