// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clerk_sync.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrganizationIDByClerkOrgID = `-- name: GetOrganizationIDByClerkOrgID :one
SELECT id FROM organizations WHERE clerk_org_id = $1
`

func (q *Queries) GetOrganizationIDByClerkOrgID(ctx context.Context, clerkOrgID string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getOrganizationIDByClerkOrgID, clerkOrgID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const softDeleteMembership = `-- name: SoftDeleteMembership :execrows
UPDATE users SET is_active = false, clerk_event_at = GREATEST(clerk_event_at, $1::timestamptz)
WHERE clerk_user_id = $2
  AND org_id = (SELECT id FROM organizations WHERE clerk_org_id = $3)
  AND (clerk_event_at IS NULL OR $1::timestamptz IS NULL OR $1::timestamptz >= clerk_event_at)
`

type SoftDeleteMembershipParams struct {
	EventAt     pgtype.Timestamptz `json:"event_at"`
	ClerkUserID string             `json:"clerk_user_id"`
	ClerkOrgID  string             `json:"clerk_org_id"`
}

// A single membership removal: only this org's row, never the person's
// memberships elsewhere.
func (q *Queries) SoftDeleteMembership(ctx context.Context, arg SoftDeleteMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteMembership, arg.EventAt, arg.ClerkUserID, arg.ClerkOrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteOrganizationByClerkOrgID = `-- name: SoftDeleteOrganizationByClerkOrgID :execrows
UPDATE organizations SET is_active = false WHERE clerk_org_id = $1
`

func (q *Queries) SoftDeleteOrganizationByClerkOrgID(ctx context.Context, clerkOrgID string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteOrganizationByClerkOrgID, clerkOrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteUserByClerkUserID = `-- name: SoftDeleteUserByClerkUserID :execrows
UPDATE users SET is_active = false, clerk_event_at = GREATEST(clerk_event_at, $1::timestamptz)
WHERE clerk_user_id = $2
  AND (clerk_event_at IS NULL OR $1::timestamptz IS NULL OR $1::timestamptz >= clerk_event_at)
`

type SoftDeleteUserByClerkUserIDParams struct {
	EventAt     pgtype.Timestamptz `json:"event_at"`
	ClerkUserID string             `json:"clerk_user_id"`
}

// A full Clerk account deletion (user.deleted): every membership goes.
func (q *Queries) SoftDeleteUserByClerkUserID(ctx context.Context, arg SoftDeleteUserByClerkUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUserByClerkUserID, arg.EventAt, arg.ClerkUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserProfile = `-- name: UpdateUserProfile :execrows
UPDATE users SET full_name = $2, avatar_url = $3 WHERE clerk_user_id = $1
`

type UpdateUserProfileParams struct {
	ClerkUserID string  `json:"clerk_user_id"`
	FullName    *string `json:"full_name"`
	AvatarUrl   *string `json:"avatar_url"`
}

// Profile fields are per-person, so this deliberately updates every
// membership row the person holds, across all their orgs.
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserProfile, arg.ClerkUserID, arg.FullName, arg.AvatarUrl)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertOrganization = `-- name: UpsertOrganization :one

INSERT INTO organizations (clerk_org_id, name, slug, is_active)
VALUES ($1, $2, $3, true)
ON CONFLICT (clerk_org_id) DO UPDATE SET
    name = EXCLUDED.name,
    slug = CASE WHEN $4::boolean THEN EXCLUDED.slug ELSE organizations.slug END
RETURNING id
`

type UpsertOrganizationParams struct {
	ClerkOrgID    string `json:"clerk_org_id"`
	Name          string `json:"name"`
	Slug          string `json:"slug"`
	SlugFromClerk bool   `json:"slug_from_clerk"`
}

// Queries backing the Clerk webhook sync (POST /api/webhooks/clerk). Run
// through the app_system (BYPASSRLS) pool, never app_user — see
// internal/api/webhooks/clerk.go.
// is_active is deliberately left alone on conflict: an organization.updated
// (or a late-delivered organization.created) must never resurrect an org
// this backend has deactivated — e.g. a removed client workspace.
// The webhook substitutes a clerk_org_id-derived slug when Clerk sends none
// (org slugs disabled on the instance); that stand-in must never replace a
// real slug already stored, e.g. one a client workspace was created with.
func (q *Queries) UpsertOrganization(ctx context.Context, arg UpsertOrganizationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertOrganization,
		arg.ClerkOrgID,
		arg.Name,
		arg.Slug,
		arg.SlugFromClerk,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertUserForMembership = `-- name: UpsertUserForMembership :execrows
INSERT INTO users (org_id, clerk_user_id, email, full_name, role, can_approve_workflows, can_manage_api_keys, can_manage_integrations, is_active, clerk_event_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, true, $9::timestamptz)
ON CONFLICT (org_id, clerk_user_id) DO UPDATE SET
    role = EXCLUDED.role,
    is_active = true,
    can_approve_workflows = CASE WHEN users.is_active THEN users.can_approve_workflows ELSE EXCLUDED.can_approve_workflows END,
    can_manage_api_keys = CASE WHEN users.is_active THEN users.can_manage_api_keys ELSE EXCLUDED.can_manage_api_keys END,
    can_manage_integrations = CASE WHEN users.is_active THEN users.can_manage_integrations ELSE EXCLUDED.can_manage_integrations END,
    clerk_event_at = GREATEST(users.clerk_event_at, EXCLUDED.clerk_event_at)
WHERE users.clerk_event_at IS NULL OR EXCLUDED.clerk_event_at IS NULL OR EXCLUDED.clerk_event_at >= users.clerk_event_at
`

type UpsertUserForMembershipParams struct {
	OrgID                 pgtype.UUID        `json:"org_id"`
	ClerkUserID           string             `json:"clerk_user_id"`
	Email                 string             `json:"email"`
	FullName              *string            `json:"full_name"`
	Role                  string             `json:"role"`
	CanApproveWorkflows   *bool              `json:"can_approve_workflows"`
	CanManageApiKeys      *bool              `json:"can_manage_api_keys"`
	CanManageIntegrations *bool              `json:"can_manage_integrations"`
	EventAt               pgtype.Timestamptz `json:"event_at"`
}

// can_approve_workflows/can_manage_api_keys/can_manage_integrations are
// reset to the freshly computed role-derived default (EXCLUDED) only when
// the existing row is currently inactive — a genuine new membership after
// having been removed. An already-active member's flags are left
// untouched on conflict, since those may since have been hand-adjusted via
// workflow 13's PATCH .../role, which a routine Clerk membership re-sync
// (role unchanged, just metadata) must never silently clobber.
//
// Real bug this fixes, found live 2026-09-07: without the is_active
// branch, a former admin/owner who was removed and later re-invited as a
// plain member kept their old admin-era flags forever — the ON CONFLICT
// branch never touched these 3 columns at all, so ANY re-sync (including
// a brand-new membership) silently carried forward whatever a completely
// unrelated, already-terminated membership had left behind.
// event_at is the Clerk event's own timestamp (NULL when unknown, e.g. a row
// written by workspace creation): an event older than the newest one already
// applied to this membership changes nothing, so a retried "created" can't
// undo a later removal and a stale "updated" can't revert a role.
func (q *Queries) UpsertUserForMembership(ctx context.Context, arg UpsertUserForMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertUserForMembership,
		arg.OrgID,
		arg.ClerkUserID,
		arg.Email,
		arg.FullName,
		arg.Role,
		arg.CanApproveWorkflows,
		arg.CanManageApiKeys,
		arg.CanManageIntegrations,
		arg.EventAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
