// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clerk_sync.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrganizationIDByClerkOrgID = `-- name: GetOrganizationIDByClerkOrgID :one
SELECT id FROM organizations WHERE clerk_org_id = $1
`

func (q *Queries) GetOrganizationIDByClerkOrgID(ctx context.Context, clerkOrgID string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getOrganizationIDByClerkOrgID, clerkOrgID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const softDeleteOrganizationByClerkOrgID = `-- name: SoftDeleteOrganizationByClerkOrgID :execrows
UPDATE organizations SET is_active = false WHERE clerk_org_id = $1
`

func (q *Queries) SoftDeleteOrganizationByClerkOrgID(ctx context.Context, clerkOrgID string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteOrganizationByClerkOrgID, clerkOrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteUserByClerkUserID = `-- name: SoftDeleteUserByClerkUserID :execrows
UPDATE users SET is_active = false WHERE clerk_user_id = $1
`

func (q *Queries) SoftDeleteUserByClerkUserID(ctx context.Context, clerkUserID string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUserByClerkUserID, clerkUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserProfile = `-- name: UpdateUserProfile :execrows
UPDATE users SET full_name = $2, avatar_url = $3 WHERE clerk_user_id = $1
`

type UpdateUserProfileParams struct {
	ClerkUserID string  `json:"clerk_user_id"`
	FullName    *string `json:"full_name"`
	AvatarUrl   *string `json:"avatar_url"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserProfile, arg.ClerkUserID, arg.FullName, arg.AvatarUrl)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertOrganization = `-- name: UpsertOrganization :one

INSERT INTO organizations (clerk_org_id, name, slug, is_active)
VALUES ($1, $2, $3, true)
ON CONFLICT (clerk_org_id) DO UPDATE SET
    name = EXCLUDED.name,
    slug = EXCLUDED.slug,
    is_active = true
RETURNING id
`

type UpsertOrganizationParams struct {
	ClerkOrgID string `json:"clerk_org_id"`
	Name       string `json:"name"`
	Slug       string `json:"slug"`
}

// Queries backing the Clerk webhook sync (POST /api/webhooks/clerk). Run
// through the app_system (BYPASSRLS) pool, never app_user — see
// internal/api/webhooks/clerk.go.
func (q *Queries) UpsertOrganization(ctx context.Context, arg UpsertOrganizationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertOrganization, arg.ClerkOrgID, arg.Name, arg.Slug)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertUserForMembership = `-- name: UpsertUserForMembership :exec
INSERT INTO users (org_id, clerk_user_id, email, full_name, role, can_approve_workflows, is_active)
VALUES ($1, $2, $3, $4, $5, $6, true)
ON CONFLICT (clerk_user_id) DO UPDATE SET
    org_id = EXCLUDED.org_id,
    role = EXCLUDED.role,
    is_active = true
`

type UpsertUserForMembershipParams struct {
	OrgID               pgtype.UUID `json:"org_id"`
	ClerkUserID         string      `json:"clerk_user_id"`
	Email               string      `json:"email"`
	FullName            *string     `json:"full_name"`
	Role                string      `json:"role"`
	CanApproveWorkflows *bool       `json:"can_approve_workflows"`
}

// can_approve_workflows is set only on first INSERT, never touched by the
// ON CONFLICT branch (not listed in its SET clause) — a membership re-sync
// (role change, reactivation) must never silently reset a flag that could
// since have been granted or revoked by hand. Workflow 13 (team management)
// doesn't exist yet, so there's no in-app way for an org's own
// admin/owner to grant themselves this — defaulting it true for whoever
// created/administers the org is what lets Workflow 10's approval gate be
// usable at all before that UI exists.
func (q *Queries) UpsertUserForMembership(ctx context.Context, arg UpsertUserForMembershipParams) error {
	_, err := q.db.Exec(ctx, upsertUserForMembership,
		arg.OrgID,
		arg.ClerkUserID,
		arg.Email,
		arg.FullName,
		arg.Role,
		arg.CanApproveWorkflows,
	)
	return err
}
