// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clerk_sync.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrganizationIDByClerkOrgID = `-- name: GetOrganizationIDByClerkOrgID :one
SELECT id FROM organizations WHERE clerk_org_id = $1
`

func (q *Queries) GetOrganizationIDByClerkOrgID(ctx context.Context, clerkOrgID string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getOrganizationIDByClerkOrgID, clerkOrgID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const softDeleteOrganizationByClerkOrgID = `-- name: SoftDeleteOrganizationByClerkOrgID :execrows
UPDATE organizations SET is_active = false WHERE clerk_org_id = $1
`

func (q *Queries) SoftDeleteOrganizationByClerkOrgID(ctx context.Context, clerkOrgID string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteOrganizationByClerkOrgID, clerkOrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteUserByClerkUserID = `-- name: SoftDeleteUserByClerkUserID :execrows
UPDATE users SET is_active = false WHERE clerk_user_id = $1
`

func (q *Queries) SoftDeleteUserByClerkUserID(ctx context.Context, clerkUserID string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUserByClerkUserID, clerkUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserProfile = `-- name: UpdateUserProfile :execrows
UPDATE users SET full_name = $2, avatar_url = $3 WHERE clerk_user_id = $1
`

type UpdateUserProfileParams struct {
	ClerkUserID string  `json:"clerk_user_id"`
	FullName    *string `json:"full_name"`
	AvatarUrl   *string `json:"avatar_url"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserProfile, arg.ClerkUserID, arg.FullName, arg.AvatarUrl)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertOrganization = `-- name: UpsertOrganization :one

INSERT INTO organizations (clerk_org_id, name, slug, is_active)
VALUES ($1, $2, $3, true)
ON CONFLICT (clerk_org_id) DO UPDATE SET
    name = EXCLUDED.name,
    slug = EXCLUDED.slug,
    is_active = true
RETURNING id
`

type UpsertOrganizationParams struct {
	ClerkOrgID string `json:"clerk_org_id"`
	Name       string `json:"name"`
	Slug       string `json:"slug"`
}

// Queries backing the Clerk webhook sync (POST /api/webhooks/clerk). Run
// through the app_system (BYPASSRLS) pool, never app_user — see
// internal/api/webhooks/clerk.go.
func (q *Queries) UpsertOrganization(ctx context.Context, arg UpsertOrganizationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertOrganization, arg.ClerkOrgID, arg.Name, arg.Slug)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertUserForMembership = `-- name: UpsertUserForMembership :exec
INSERT INTO users (org_id, clerk_user_id, email, full_name, role, can_approve_workflows, can_manage_api_keys, can_manage_integrations, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, true)
ON CONFLICT (clerk_user_id) DO UPDATE SET
    org_id = EXCLUDED.org_id,
    role = EXCLUDED.role,
    is_active = true,
    can_approve_workflows = CASE WHEN users.is_active THEN users.can_approve_workflows ELSE EXCLUDED.can_approve_workflows END,
    can_manage_api_keys = CASE WHEN users.is_active THEN users.can_manage_api_keys ELSE EXCLUDED.can_manage_api_keys END,
    can_manage_integrations = CASE WHEN users.is_active THEN users.can_manage_integrations ELSE EXCLUDED.can_manage_integrations END
`

type UpsertUserForMembershipParams struct {
	OrgID                 pgtype.UUID `json:"org_id"`
	ClerkUserID           string      `json:"clerk_user_id"`
	Email                 string      `json:"email"`
	FullName              *string     `json:"full_name"`
	Role                  string      `json:"role"`
	CanApproveWorkflows   *bool       `json:"can_approve_workflows"`
	CanManageApiKeys      *bool       `json:"can_manage_api_keys"`
	CanManageIntegrations *bool       `json:"can_manage_integrations"`
}

// can_approve_workflows/can_manage_api_keys/can_manage_integrations are
// reset to the freshly computed role-derived default (EXCLUDED) only when
// the existing row is currently inactive — a genuine new membership after
// having been removed. An already-active member's flags are left
// untouched on conflict, since those may since have been hand-adjusted via
// workflow 13's PATCH .../role, which a routine Clerk membership re-sync
// (role unchanged, just metadata) must never silently clobber.
//
// Real bug this fixes, found live 2026-09-07: without the is_active
// branch, a former admin/owner who was removed and later re-invited as a
// plain member kept their old admin-era flags forever — the ON CONFLICT
// branch never touched these 3 columns at all, so ANY re-sync (including
// a brand-new membership) silently carried forward whatever a completely
// unrelated, already-terminated membership had left behind.
func (q *Queries) UpsertUserForMembership(ctx context.Context, arg UpsertUserForMembershipParams) error {
	_, err := q.db.Exec(ctx, upsertUserForMembership,
		arg.OrgID,
		arg.ClerkUserID,
		arg.Email,
		arg.FullName,
		arg.Role,
		arg.CanApproveWorkflows,
		arg.CanManageApiKeys,
		arg.CanManageIntegrations,
	)
	return err
}
