// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: digest.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const disableDigestForOrg = `-- name: DisableDigestForOrg :exec
UPDATE organizations SET digest_enabled = false WHERE id = $1
`

// Backs the no-login unsubscribe link — deliberately only ever turns the
// digest off, never on, so a leaked/replayed token can't be used to
// re-enable something a founder actively disabled some other way.
func (q *Queries) DisableDigestForOrg(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, disableDigestForOrg, id)
	return err
}

const getDigestCostUSD = `-- name: GetDigestCostUSD :one
SELECT COALESCE(SUM(estimated_cost_usd), 0)::double precision AS cost_usd
FROM cost_ledger
WHERE org_id = $1
  AND (created_at AT TIME ZONE $2::text)::date
      = (now() AT TIME ZONE $2::text)::date - 1
`

type GetDigestCostUSDParams struct {
	OrgID    pgtype.UUID `json:"org_id"`
	Timezone string      `json:"timezone"`
}

func (q *Queries) GetDigestCostUSD(ctx context.Context, arg GetDigestCostUSDParams) (float64, error) {
	row := q.db.QueryRow(ctx, getDigestCostUSD, arg.OrgID, arg.Timezone)
	var cost_usd float64
	err := row.Scan(&cost_usd)
	return cost_usd, err
}

const getDigestPendingApprovalsCount = `-- name: GetDigestPendingApprovalsCount :one
SELECT COUNT(*)::bigint FROM approvals WHERE org_id = $1 AND status = 'pending'
`

// Current state, not time-boxed to yesterday -- a founder needs to know
// what's waiting on them right now, not just what queued up yesterday.
func (q *Queries) GetDigestPendingApprovalsCount(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getDigestPendingApprovalsCount, orgID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getDigestRunStats = `-- name: GetDigestRunStats :one
SELECT
    COUNT(*)::bigint AS total_runs,
    COUNT(*) FILTER (WHERE status = 'completed')::bigint AS successful_runs,
    COUNT(*) FILTER (WHERE status = 'failed')::bigint AS failed_runs,
    COALESCE(SUM(hours_saved), 0)::double precision AS hours_saved
FROM workflow_runs
WHERE org_id = $1
  AND parent_run_id IS NULL
  AND (created_at AT TIME ZONE $2::text)::date
      = (now() AT TIME ZONE $2::text)::date - 1
`

type GetDigestRunStatsParams struct {
	OrgID    pgtype.UUID `json:"org_id"`
	Timezone string      `json:"timezone"`
}

type GetDigestRunStatsRow struct {
	TotalRuns      int64   `json:"total_runs"`
	SuccessfulRuns int64   `json:"successful_runs"`
	FailedRuns     int64   `json:"failed_runs"`
	HoursSaved     float64 `json:"hours_saved"`
}

// "Yesterday" is the previous calendar day in the org's own
// digest_timezone, not UTC -- matches what ListOrgsDueForDigest just
// fired on. parent_run_id IS NULL excludes workflow 18 specialist
// sub-runs from the count, same reasoning as FinalizeRunHoursSaved: only
// an orchestrator's own run represents one end-to-end task a founder
// would otherwise have done by hand.
func (q *Queries) GetDigestRunStats(ctx context.Context, arg GetDigestRunStatsParams) (GetDigestRunStatsRow, error) {
	row := q.db.QueryRow(ctx, getDigestRunStats, arg.OrgID, arg.Timezone)
	var i GetDigestRunStatsRow
	err := row.Scan(
		&i.TotalRuns,
		&i.SuccessfulRuns,
		&i.FailedRuns,
		&i.HoursSaved,
	)
	return i, err
}

const getDigestSettings = `-- name: GetDigestSettings :one
SELECT digest_enabled, digest_send_hour, digest_timezone FROM organizations WHERE id = $1
`

type GetDigestSettingsRow struct {
	DigestEnabled  bool   `json:"digest_enabled"`
	DigestSendHour int32  `json:"digest_send_hour"`
	DigestTimezone string `json:"digest_timezone"`
}

func (q *Queries) GetDigestSettings(ctx context.Context, id pgtype.UUID) (GetDigestSettingsRow, error) {
	row := q.db.QueryRow(ctx, getDigestSettings, id)
	var i GetDigestSettingsRow
	err := row.Scan(&i.DigestEnabled, &i.DigestSendHour, &i.DigestTimezone)
	return i, err
}

const getDigestTopAgent = `-- name: GetDigestTopAgent :one
SELECT a.name AS agent_name, COUNT(*)::bigint AS run_count
FROM workflow_runs wr
JOIN workflows w ON w.id = wr.workflow_id
JOIN agents a ON a.id = COALESCE(wr.agent_id, w.agent_id)
WHERE wr.org_id = $1
  AND wr.parent_run_id IS NULL
  AND (wr.created_at AT TIME ZONE $2::text)::date
      = (now() AT TIME ZONE $2::text)::date - 1
GROUP BY a.name
ORDER BY run_count DESC
LIMIT 1
`

type GetDigestTopAgentParams struct {
	OrgID    pgtype.UUID `json:"org_id"`
	Timezone string      `json:"timezone"`
}

type GetDigestTopAgentRow struct {
	AgentName string `json:"agent_name"`
	RunCount  int64  `json:"run_count"`
}

// COALESCE(wr.agent_id, w.agent_id): same "derive from workflow unless a
// team sub-run overrides it directly" convention as GetRunAgentID.
// Returns pgx.ErrNoRows when nothing ran yesterday -- callers treat that
// as "no top agent", not an error.
func (q *Queries) GetDigestTopAgent(ctx context.Context, arg GetDigestTopAgentParams) (GetDigestTopAgentRow, error) {
	row := q.db.QueryRow(ctx, getDigestTopAgent, arg.OrgID, arg.Timezone)
	var i GetDigestTopAgentRow
	err := row.Scan(&i.AgentName, &i.RunCount)
	return i, err
}

const getOrgNameAndTimezone = `-- name: GetOrgNameAndTimezone :one
SELECT name, digest_timezone FROM organizations WHERE id = $1
`

type GetOrgNameAndTimezoneRow struct {
	Name           string `json:"name"`
	DigestTimezone string `json:"digest_timezone"`
}

// Backs "send test email" -- BuildPayload needs both, and neither
// GetDigestSettings nor auth.sql's GetActiveOrganizationByID returns the
// pair together.
func (q *Queries) GetOrgNameAndTimezone(ctx context.Context, id pgtype.UUID) (GetOrgNameAndTimezoneRow, error) {
	row := q.db.QueryRow(ctx, getOrgNameAndTimezone, id)
	var i GetOrgNameAndTimezoneRow
	err := row.Scan(&i.Name, &i.DigestTimezone)
	return i, err
}

const getUserEmailByID = `-- name: GetUserEmailByID :one
SELECT email FROM users WHERE id = $1
`

func (q *Queries) GetUserEmailByID(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserEmailByID, id)
	var email string
	err := row.Scan(&email)
	return email, err
}

const listDigestRecipients = `-- name: ListDigestRecipients :many
SELECT email FROM users
WHERE org_id = $1 AND is_active = true AND role IN ('owner', 'admin')
`

// Owners/admins only, not every member -- same admin-role check
// (role IN ('owner','admin')) already used by org.handler.go/clerk
// webhook, reused here rather than invented fresh.
func (q *Queries) ListDigestRecipients(ctx context.Context, orgID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listDigestRecipients, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgsDueForDigest = `-- name: ListOrgsDueForDigest :many
SELECT id, name, digest_timezone
FROM organizations
WHERE digest_enabled = true
  AND is_active = true
  AND EXTRACT(HOUR FROM now() AT TIME ZONE digest_timezone)::int = digest_send_hour
  AND (
    digest_last_sent_at IS NULL
    OR (digest_last_sent_at AT TIME ZONE digest_timezone)::date < (now() AT TIME ZONE digest_timezone)::date
  )
  AND EXISTS (
    SELECT 1 FROM workflow_runs wr
    WHERE wr.org_id = organizations.id AND wr.created_at >= now() - interval '7 days'
  )
`

type ListOrgsDueForDigestRow struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	DigestTimezone string      `json:"digest_timezone"`
}

// Cross-tenant scan (system pool, BYPASSRLS) -- an org is due when its
// local hour matches digest_send_hour, it hasn't already gotten today's
// digest in its own timezone yet, and it's had some activity in the last
// 7 days (skips ghost emails to churned/empty orgs, per spec).
func (q *Queries) ListOrgsDueForDigest(ctx context.Context) ([]ListOrgsDueForDigestRow, error) {
	rows, err := q.db.Query(ctx, listOrgsDueForDigest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgsDueForDigestRow
	for rows.Next() {
		var i ListOrgsDueForDigestRow
		if err := rows.Scan(&i.ID, &i.Name, &i.DigestTimezone); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDigestSent = `-- name: MarkDigestSent :exec
UPDATE organizations SET digest_last_sent_at = now() WHERE id = $1
`

func (q *Queries) MarkDigestSent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markDigestSent, id)
	return err
}

const updateDigestSettings = `-- name: UpdateDigestSettings :exec
UPDATE organizations
SET digest_enabled = $2, digest_send_hour = $3, digest_timezone = $4
WHERE id = $1
`

type UpdateDigestSettingsParams struct {
	ID             pgtype.UUID `json:"id"`
	DigestEnabled  bool        `json:"digest_enabled"`
	DigestSendHour int32       `json:"digest_send_hour"`
	DigestTimezone string      `json:"digest_timezone"`
}

func (q *Queries) UpdateDigestSettings(ctx context.Context, arg UpdateDigestSettingsParams) error {
	_, err := q.db.Exec(ctx, updateDigestSettings,
		arg.ID,
		arg.DigestEnabled,
		arg.DigestSendHour,
		arg.DigestTimezone,
	)
	return err
}
