// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDocumentChunks = `-- name: DeleteDocumentChunks :exec
DELETE FROM document_chunks WHERE doc_id = $1
`

func (q *Queries) DeleteDocumentChunks(ctx context.Context, docID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocumentChunks, docID)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, filename, s3_path, mime_type, byte_size, category, processing_status, total_chunks, indexed_at, error_detail, created_at
FROM documents
WHERE org_id = $1 AND id = $2
`

type GetDocumentParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

type GetDocumentRow struct {
	ID               pgtype.UUID        `json:"id"`
	Filename         string             `json:"filename"`
	S3Path           string             `json:"s3_path"`
	MimeType         *string            `json:"mime_type"`
	ByteSize         *int32             `json:"byte_size"`
	Category         *string            `json:"category"`
	ProcessingStatus *string            `json:"processing_status"`
	TotalChunks      *int32             `json:"total_chunks"`
	IndexedAt        pgtype.Timestamptz `json:"indexed_at"`
	ErrorDetail      *string            `json:"error_detail"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (GetDocumentRow, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.OrgID, arg.ID)
	var i GetDocumentRow
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.S3Path,
		&i.MimeType,
		&i.ByteSize,
		&i.Category,
		&i.ProcessingStatus,
		&i.TotalChunks,
		&i.IndexedAt,
		&i.ErrorDetail,
		&i.CreatedAt,
	)
	return i, err
}

const hardDeleteDocument = `-- name: HardDeleteDocument :exec
DELETE FROM documents WHERE org_id = $1 AND id = $2
`

type HardDeleteDocumentParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

// Only called after purgeDocumentJob has successfully removed the
// Pinecone vectors and the S3 object — see internal/core/documents/purge.go.
func (q *Queries) HardDeleteDocument(ctx context.Context, arg HardDeleteDocumentParams) error {
	_, err := q.db.Exec(ctx, hardDeleteDocument, arg.OrgID, arg.ID)
	return err
}

const insertDocument = `-- name: InsertDocument :exec

INSERT INTO documents (id, org_id, filename, s3_path, mime_type, byte_size, category, processing_status, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'pending', $8)
`

type InsertDocumentParams struct {
	ID         pgtype.UUID `json:"id"`
	OrgID      pgtype.UUID `json:"org_id"`
	Filename   string      `json:"filename"`
	S3Path     string      `json:"s3_path"`
	MimeType   *string     `json:"mime_type"`
	ByteSize   *int32      `json:"byte_size"`
	Category   *string     `json:"category"`
	UploadedBy pgtype.UUID `json:"uploaded_by"`
}

// Queries backing workflow 6 (document upload / RAG). Tenant-scoped reads
// and writes run through app_user via tenant.WithTx, same convention as
// every other feature area in this file set. The recovery-sweep query
// (ListStuckDocuments) is the one deliberate exception — it scans across
// every org's documents, so it runs on app_system, matching
// internal/core/integrations/refresh.go's RunRefreshJob precedent for
// the same "this is inherently cross-tenant" reasoning.
// id is application-generated (not the column's gen_random_uuid()
// default) so the handler knows the S3 key (documents/{org_id}/{doc_id}/{filename})
// before uploading, rather than uploading first and updating s3_path
// after — one INSERT instead of an insert-then-update dance.
func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) error {
	_, err := q.db.Exec(ctx, insertDocument,
		arg.ID,
		arg.OrgID,
		arg.Filename,
		arg.S3Path,
		arg.MimeType,
		arg.ByteSize,
		arg.Category,
		arg.UploadedBy,
	)
	return err
}

const insertDocumentChunk = `-- name: InsertDocumentChunk :exec
INSERT INTO document_chunks (doc_id, chunk_index, pinecone_id) VALUES ($1, $2, $3)
`

type InsertDocumentChunkParams struct {
	DocID      pgtype.UUID `json:"doc_id"`
	ChunkIndex int32       `json:"chunk_index"`
	PineconeID string      `json:"pinecone_id"`
}

func (q *Queries) InsertDocumentChunk(ctx context.Context, arg InsertDocumentChunkParams) error {
	_, err := q.db.Exec(ctx, insertDocumentChunk, arg.DocID, arg.ChunkIndex, arg.PineconeID)
	return err
}

const listDocumentChunkPineconeIDs = `-- name: ListDocumentChunkPineconeIDs :many
SELECT pinecone_id FROM document_chunks WHERE doc_id = $1
`

func (q *Queries) ListDocumentChunkPineconeIDs(ctx context.Context, docID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listDocumentChunkPineconeIDs, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var pinecone_id string
		if err := rows.Scan(&pinecone_id); err != nil {
			return nil, err
		}
		items = append(items, pinecone_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, filename, category, processing_status, total_chunks, byte_size, created_at, indexed_at
FROM documents
WHERE org_id = $1 AND processing_status != 'deleting'
ORDER BY created_at DESC
`

type ListDocumentsRow struct {
	ID               pgtype.UUID        `json:"id"`
	Filename         string             `json:"filename"`
	Category         *string            `json:"category"`
	ProcessingStatus *string            `json:"processing_status"`
	TotalChunks      *int32             `json:"total_chunks"`
	ByteSize         *int32             `json:"byte_size"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	IndexedAt        pgtype.Timestamptz `json:"indexed_at"`
}

// Excludes 'deleting': once DELETE .../{id} has been called, the
// document shouldn't reappear in a normal list view while
// purgeDocumentJob finishes removing it (the row itself is only ever
// hard-deleted after that succeeds — see HardDeleteDocument).
func (q *Queries) ListDocuments(ctx context.Context, orgID pgtype.UUID) ([]ListDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listDocuments, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsRow
	for rows.Next() {
		var i ListDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Category,
			&i.ProcessingStatus,
			&i.TotalChunks,
			&i.ByteSize,
			&i.CreatedAt,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStuckDocuments = `-- name: ListStuckDocuments :many
SELECT id, org_id, processing_status
FROM documents
WHERE processing_status IN ('pending', 'processing', 'deleting')
  AND updated_at < $1
`

type ListStuckDocumentsRow struct {
	ID               pgtype.UUID `json:"id"`
	OrgID            pgtype.UUID `json:"org_id"`
	ProcessingStatus *string     `json:"processing_status"`
}

// Documents whose background job (processDocument or purgeDocumentJob)
// may have been running in a process that restarted mid-job — the
// goroutine-based tradeoff internal/core/documents.RecoverStuckJobs
// exists to cover. olderThan guards against re-kicking a job that's
// still genuinely in flight in *this* process, not actually stuck.
func (q *Queries) ListStuckDocuments(ctx context.Context, updatedAt pgtype.Timestamptz) ([]ListStuckDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listStuckDocuments, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStuckDocumentsRow
	for rows.Next() {
		var i ListStuckDocumentsRow
		if err := rows.Scan(&i.ID, &i.OrgID, &i.ProcessingStatus); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDocumentFailed = `-- name: MarkDocumentFailed :exec
UPDATE documents SET processing_status = 'failed', error_detail = $3 WHERE org_id = $1 AND id = $2
`

type MarkDocumentFailedParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	ID          pgtype.UUID `json:"id"`
	ErrorDetail *string     `json:"error_detail"`
}

func (q *Queries) MarkDocumentFailed(ctx context.Context, arg MarkDocumentFailedParams) error {
	_, err := q.db.Exec(ctx, markDocumentFailed, arg.OrgID, arg.ID, arg.ErrorDetail)
	return err
}

const markDocumentIndexed = `-- name: MarkDocumentIndexed :exec
UPDATE documents
SET processing_status = 'indexed', total_chunks = $3, indexed_at = now(), error_detail = NULL
WHERE org_id = $1 AND id = $2
`

type MarkDocumentIndexedParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	ID          pgtype.UUID `json:"id"`
	TotalChunks *int32      `json:"total_chunks"`
}

func (q *Queries) MarkDocumentIndexed(ctx context.Context, arg MarkDocumentIndexedParams) error {
	_, err := q.db.Exec(ctx, markDocumentIndexed, arg.OrgID, arg.ID, arg.TotalChunks)
	return err
}

const softDeleteDocument = `-- name: SoftDeleteDocument :exec
UPDATE documents SET processing_status = 'deleting' WHERE org_id = $1 AND id = $2
`

type SoftDeleteDocumentParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) SoftDeleteDocument(ctx context.Context, arg SoftDeleteDocumentParams) error {
	_, err := q.db.Exec(ctx, softDeleteDocument, arg.OrgID, arg.ID)
	return err
}

const updateDocumentProcessing = `-- name: UpdateDocumentProcessing :exec
UPDATE documents SET processing_status = $3 WHERE org_id = $1 AND id = $2
`

type UpdateDocumentProcessingParams struct {
	OrgID            pgtype.UUID `json:"org_id"`
	ID               pgtype.UUID `json:"id"`
	ProcessingStatus *string     `json:"processing_status"`
}

func (q *Queries) UpdateDocumentProcessing(ctx context.Context, arg UpdateDocumentProcessingParams) error {
	_, err := q.db.Exec(ctx, updateDocumentProcessing, arg.OrgID, arg.ID, arg.ProcessingStatus)
	return err
}
