// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: graph.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finalizeRun = `-- name: FinalizeRun :exec
UPDATE workflow_runs
SET output = $3, input_tokens = $4, output_tokens = $5, cached_tokens = $6,
    completed_at = now(),
    duration_ms = (EXTRACT(EPOCH FROM (now() - COALESCE(started_at, created_at))) * 1000)::int
WHERE org_id = $1 AND id = $2
`

type FinalizeRunParams struct {
	OrgID        pgtype.UUID `json:"org_id"`
	ID           pgtype.UUID `json:"id"`
	Output       *string     `json:"output"`
	InputTokens  int32       `json:"input_tokens"`
	OutputTokens int32       `json:"output_tokens"`
	CachedTokens int32       `json:"cached_tokens"`
}

// Fills in the completion-summary fields checkpoint() itself doesn't own
// (status stays checkpoint()'s alone) — only called once a run reaches a
// genuinely terminal status, never for awaiting_approval.
func (q *Queries) FinalizeRun(ctx context.Context, arg FinalizeRunParams) error {
	_, err := q.db.Exec(ctx, finalizeRun,
		arg.OrgID,
		arg.ID,
		arg.Output,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CachedTokens,
	)
	return err
}

const finalizeRunHoursSaved = `-- name: FinalizeRunHoursSaved :one
UPDATE workflow_runs
SET hours_saved = COALESCE(
    (SELECT w.estimated_manual_minutes FROM workflows w WHERE w.id = workflow_runs.workflow_id),
    15
)::double precision / 60.0
WHERE workflow_runs.org_id = $1 AND workflow_runs.id = $2
RETURNING hours_saved
`

type FinalizeRunHoursSavedParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

// Only ever called once, right after FinalizeRun, guarded on the run
// having just reached status='completed' -- see finalizeIfTerminal.
// estimated_manual_minutes defaults to 15 (a conservative baseline) when
// the workflow never had one set.
func (q *Queries) FinalizeRunHoursSaved(ctx context.Context, arg FinalizeRunHoursSavedParams) (*float64, error) {
	row := q.db.QueryRow(ctx, finalizeRunHoursSaved, arg.OrgID, arg.ID)
	var hours_saved *float64
	err := row.Scan(&hours_saved)
	return hours_saved, err
}

const getHoursSavedSince = `-- name: GetHoursSavedSince :one
SELECT COALESCE(SUM(hours_saved), 0)::double precision AS hours_saved
FROM workflow_runs
WHERE org_id = $1 AND completed_at >= $2
`

type GetHoursSavedSinceParams struct {
	OrgID       pgtype.UUID        `json:"org_id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) GetHoursSavedSince(ctx context.Context, arg GetHoursSavedSinceParams) (float64, error) {
	row := q.db.QueryRow(ctx, getHoursSavedSince, arg.OrgID, arg.CompletedAt)
	var hours_saved float64
	err := row.Scan(&hours_saved)
	return hours_saved, err
}

const getOrgRunSettings = `-- name: GetOrgRunSettings :one

SELECT llm_provider, agents_paused FROM organizations WHERE id = $1
`

type GetOrgRunSettingsRow struct {
	LlmProvider  *string `json:"llm_provider"`
	AgentsPaused bool    `json:"agents_paused"`
}

// graph.Launcher's run lifecycle (POST /workflows/{id}/run's async goroutine
// — see internal/core/graph/launch.go) and the read-only HTTP endpoints
// (GET /runs, GET /runs/{id}).
// Preflight (kill switch) + provider resolution for Launcher.Launch.
func (q *Queries) GetOrgRunSettings(ctx context.Context, id pgtype.UUID) (GetOrgRunSettingsRow, error) {
	row := q.db.QueryRow(ctx, getOrgRunSettings, id)
	var i GetOrgRunSettingsRow
	err := row.Scan(&i.LlmProvider, &i.AgentsPaused)
	return i, err
}

const getOrgTotalHoursSaved = `-- name: GetOrgTotalHoursSaved :one
SELECT total_hours_saved FROM organizations WHERE id = $1
`

func (q *Queries) GetOrgTotalHoursSaved(ctx context.Context, id pgtype.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getOrgTotalHoursSaved, id)
	var total_hours_saved float64
	err := row.Scan(&total_hours_saved)
	return total_hours_saved, err
}

const getRunAgentID = `-- name: GetRunAgentID :one
SELECT w.agent_id
FROM workflow_runs wr
JOIN workflows w ON w.id = wr.workflow_id
WHERE wr.org_id = $1 AND wr.id = $2
`

type GetRunAgentIDParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

// Resolves a run's agent_id via its workflow — Launcher.Resume needs this
// before it can rebuild the RunDeps/Nodes a suspended run's checkpoint
// alone doesn't carry (agent_id isn't part of RunState's own JSON).
func (q *Queries) GetRunAgentID(ctx context.Context, arg GetRunAgentIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getRunAgentID, arg.OrgID, arg.ID)
	var agent_id pgtype.UUID
	err := row.Scan(&agent_id)
	return agent_id, err
}

const getRunCheckpoint = `-- name: GetRunCheckpoint :one
SELECT checkpoint_state, current_node, cost_so_far_usd, tool_call_count, status
FROM workflow_runs
WHERE org_id = $1 AND id = $2
`

type GetRunCheckpointParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

type GetRunCheckpointRow struct {
	CheckpointState []byte  `json:"checkpoint_state"`
	CurrentNode     *string `json:"current_node"`
	CostSoFarUsd    float64 `json:"cost_so_far_usd"`
	ToolCallCount   int32   `json:"tool_call_count"`
	Status          string  `json:"status"`
}

func (q *Queries) GetRunCheckpoint(ctx context.Context, arg GetRunCheckpointParams) (GetRunCheckpointRow, error) {
	row := q.db.QueryRow(ctx, getRunCheckpoint, arg.OrgID, arg.ID)
	var i GetRunCheckpointRow
	err := row.Scan(
		&i.CheckpointState,
		&i.CurrentNode,
		&i.CostSoFarUsd,
		&i.ToolCallCount,
		&i.Status,
	)
	return i, err
}

const getRunCostBreakdown = `-- name: GetRunCostBreakdown :many
SELECT cost_type,
       COALESCE(SUM(estimated_cost_usd), 0)::double precision AS total_usd,
       COALESCE(SUM(input_tokens), 0)::bigint AS input_tokens,
       COALESCE(SUM(output_tokens), 0)::bigint AS output_tokens,
       COALESCE(SUM(cached_tokens), 0)::bigint AS cached_tokens
FROM cost_ledger
WHERE org_id = $1 AND run_id = $2
GROUP BY cost_type
`

type GetRunCostBreakdownParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	RunID pgtype.UUID `json:"run_id"`
}

type GetRunCostBreakdownRow struct {
	CostType     string  `json:"cost_type"`
	TotalUsd     float64 `json:"total_usd"`
	InputTokens  int64   `json:"input_tokens"`
	OutputTokens int64   `json:"output_tokens"`
	CachedTokens int64   `json:"cached_tokens"`
}

func (q *Queries) GetRunCostBreakdown(ctx context.Context, arg GetRunCostBreakdownParams) ([]GetRunCostBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getRunCostBreakdown, arg.OrgID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRunCostBreakdownRow
	for rows.Next() {
		var i GetRunCostBreakdownRow
		if err := rows.Scan(
			&i.CostType,
			&i.TotalUsd,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRunDetail = `-- name: GetRunDetail :one
SELECT id, workflow_id, status, current_node, triggered_by, output, input_tokens,
       output_tokens, cached_tokens, cost_so_far_usd, tool_call_count, started_at,
       completed_at, duration_ms, created_at
FROM workflow_runs
WHERE org_id = $1 AND id = $2
`

type GetRunDetailParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

type GetRunDetailRow struct {
	ID            pgtype.UUID        `json:"id"`
	WorkflowID    pgtype.UUID        `json:"workflow_id"`
	Status        string             `json:"status"`
	CurrentNode   *string            `json:"current_node"`
	TriggeredBy   pgtype.UUID        `json:"triggered_by"`
	Output        *string            `json:"output"`
	InputTokens   int32              `json:"input_tokens"`
	OutputTokens  int32              `json:"output_tokens"`
	CachedTokens  int32              `json:"cached_tokens"`
	CostSoFarUsd  float64            `json:"cost_so_far_usd"`
	ToolCallCount int32              `json:"tool_call_count"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	DurationMs    *int32             `json:"duration_ms"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetRunDetail(ctx context.Context, arg GetRunDetailParams) (GetRunDetailRow, error) {
	row := q.db.QueryRow(ctx, getRunDetail, arg.OrgID, arg.ID)
	var i GetRunDetailRow
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Status,
		&i.CurrentNode,
		&i.TriggeredBy,
		&i.Output,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedTokens,
		&i.CostSoFarUsd,
		&i.ToolCallCount,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const getRunStatus = `-- name: GetRunStatus :one
SELECT status FROM workflow_runs WHERE org_id = $1 AND id = $2
`

type GetRunStatusParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

// Read back the definitive status Engine's own checkpoint() already
// wrote (completed/failed/cancelled/awaiting_approval) — Launcher can't
// infer this from Engine.Run's returned error alone, since a suspended
// run also returns a nil error.
func (q *Queries) GetRunStatus(ctx context.Context, arg GetRunStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, getRunStatus, arg.OrgID, arg.ID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const incrementOrgTotalHoursSaved = `-- name: IncrementOrgTotalHoursSaved :exec
UPDATE organizations SET total_hours_saved = total_hours_saved + $2 WHERE id = $1
`

type IncrementOrgTotalHoursSavedParams struct {
	ID              pgtype.UUID `json:"id"`
	TotalHoursSaved float64     `json:"total_hours_saved"`
}

func (q *Queries) IncrementOrgTotalHoursSaved(ctx context.Context, arg IncrementOrgTotalHoursSavedParams) error {
	_, err := q.db.Exec(ctx, incrementOrgTotalHoursSaved, arg.ID, arg.TotalHoursSaved)
	return err
}

const insertWorkflowStep = `-- name: InsertWorkflowStep :exec

INSERT INTO workflow_steps (run_id, node_name, step_type, agent_name, input_data,
                             output_data, input_tokens, output_tokens, duration_ms, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertWorkflowStepParams struct {
	RunID        pgtype.UUID `json:"run_id"`
	NodeName     string      `json:"node_name"`
	StepType     string      `json:"step_type"`
	AgentName    *string     `json:"agent_name"`
	InputData    []byte      `json:"input_data"`
	OutputData   []byte      `json:"output_data"`
	InputTokens  *int32      `json:"input_tokens"`
	OutputTokens *int32      `json:"output_tokens"`
	DurationMs   *int32      `json:"duration_ms"`
	Status       *string     `json:"status"`
}

// Workflow 11 (run trace + cost). writeWorkflowStep (internal/core/graph/
// observability.go) is the one place InsertWorkflowStep is called from,
// fired at each of the 5 node functions plus once per LLM turn and once
// per tool call inside executorNode -- see BuildNodes' doc comment.
func (q *Queries) InsertWorkflowStep(ctx context.Context, arg InsertWorkflowStepParams) error {
	_, err := q.db.Exec(ctx, insertWorkflowStep,
		arg.RunID,
		arg.NodeName,
		arg.StepType,
		arg.AgentName,
		arg.InputData,
		arg.OutputData,
		arg.InputTokens,
		arg.OutputTokens,
		arg.DurationMs,
		arg.Status,
	)
	return err
}

const listRunsForOrg = `-- name: ListRunsForOrg :many
SELECT id, workflow_id, status, output, cost_so_far_usd, started_at, completed_at,
       duration_ms, created_at
FROM workflow_runs
WHERE org_id = $1
  AND ($4::varchar IS NULL OR status = $4)
  AND ($5::uuid IS NULL OR workflow_id = $5)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRunsForOrgParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	Status     *string     `json:"status"`
	WorkflowID pgtype.UUID `json:"workflow_id"`
}

type ListRunsForOrgRow struct {
	ID           pgtype.UUID        `json:"id"`
	WorkflowID   pgtype.UUID        `json:"workflow_id"`
	Status       string             `json:"status"`
	Output       *string            `json:"output"`
	CostSoFarUsd float64            `json:"cost_so_far_usd"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	DurationMs   *int32             `json:"duration_ms"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListRunsForOrg(ctx context.Context, arg ListRunsForOrgParams) ([]ListRunsForOrgRow, error) {
	rows, err := q.db.Query(ctx, listRunsForOrg,
		arg.OrgID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.WorkflowID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunsForOrgRow
	for rows.Next() {
		var i ListRunsForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.Status,
			&i.Output,
			&i.CostSoFarUsd,
			&i.StartedAt,
			&i.CompletedAt,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowSteps = `-- name: ListWorkflowSteps :many
SELECT ws.id, ws.node_name, ws.step_type, ws.agent_name, ws.input_data, ws.output_data,
       ws.input_tokens, ws.output_tokens, ws.duration_ms, ws.status, ws.created_at
FROM workflow_steps ws
JOIN workflow_runs r ON r.id = ws.run_id
WHERE r.org_id = $1 AND r.id = $2
ORDER BY ws.created_at ASC
`

type ListWorkflowStepsParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

type ListWorkflowStepsRow struct {
	ID           pgtype.UUID        `json:"id"`
	NodeName     string             `json:"node_name"`
	StepType     string             `json:"step_type"`
	AgentName    *string            `json:"agent_name"`
	InputData    []byte             `json:"input_data"`
	OutputData   []byte             `json:"output_data"`
	InputTokens  *int32             `json:"input_tokens"`
	OutputTokens *int32             `json:"output_tokens"`
	DurationMs   *int32             `json:"duration_ms"`
	Status       *string            `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// Joins workflow_runs for org-scoping (workflow_steps itself has no
// org_id column) -- same shape as GetRunAgentID's join above.
func (q *Queries) ListWorkflowSteps(ctx context.Context, arg ListWorkflowStepsParams) ([]ListWorkflowStepsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowSteps, arg.OrgID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowStepsRow
	for rows.Next() {
		var i ListWorkflowStepsRow
		if err := rows.Scan(
			&i.ID,
			&i.NodeName,
			&i.StepType,
			&i.AgentName,
			&i.InputData,
			&i.OutputData,
			&i.InputTokens,
			&i.OutputTokens,
			&i.DurationMs,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRunFailedPreflight = `-- name: MarkRunFailedPreflight :exec
UPDATE workflow_runs SET status = 'failed', completed_at = now() WHERE org_id = $1 AND id = $2
`

type MarkRunFailedPreflightParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

// Used only when dependency resolution itself fails before Engine.Run
// ever starts (a bad policy_scope, a registry error, ...) — there's no
// checkpoint yet for a normal Engine-driven "failed" transition to have
// written, so this writes the terminal status directly.
func (q *Queries) MarkRunFailedPreflight(ctx context.Context, arg MarkRunFailedPreflightParams) error {
	_, err := q.db.Exec(ctx, markRunFailedPreflight, arg.OrgID, arg.ID)
	return err
}

const markRunStarted = `-- name: MarkRunStarted :exec
UPDATE workflow_runs SET status = 'running', started_at = now() WHERE org_id = $1 AND id = $2
`

type MarkRunStartedParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) MarkRunStarted(ctx context.Context, arg MarkRunStartedParams) error {
	_, err := q.db.Exec(ctx, markRunStarted, arg.OrgID, arg.ID)
	return err
}

const updateRunCheckpoint = `-- name: UpdateRunCheckpoint :exec

UPDATE workflow_runs
SET checkpoint_state = $3,
    current_node     = $4,
    cost_so_far_usd  = $5,
    tool_call_count  = $6,
    status           = $7
WHERE org_id = $1 AND id = $2
`

type UpdateRunCheckpointParams struct {
	OrgID           pgtype.UUID `json:"org_id"`
	ID              pgtype.UUID `json:"id"`
	CheckpointState []byte      `json:"checkpoint_state"`
	CurrentNode     *string     `json:"current_node"`
	CostSoFarUsd    float64     `json:"cost_so_far_usd"`
	ToolCallCount   int32       `json:"tool_call_count"`
	Status          string      `json:"status"`
}

// internal/core/graph's checkpoint read/write — the engine.Run/Resume/checkpoint
// calls added workflow9_engine_guardrails.up.sql for. Always run through
// tenant.WithTx (a fresh transaction per call, org-scoped) — never held open across
// a node's tool-call loop or an approval-gate pause. See WORKFLOW_PLAN_GO.md's
// Workflow 9 harness planning notes for the full reasoning.
func (q *Queries) UpdateRunCheckpoint(ctx context.Context, arg UpdateRunCheckpointParams) error {
	_, err := q.db.Exec(ctx, updateRunCheckpoint,
		arg.OrgID,
		arg.ID,
		arg.CheckpointState,
		arg.CurrentNode,
		arg.CostSoFarUsd,
		arg.ToolCallCount,
		arg.Status,
	)
	return err
}
