// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: graph.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finalizeRun = `-- name: FinalizeRun :exec
UPDATE workflow_runs
SET output = $3, input_tokens = $4, output_tokens = $5, cached_tokens = $6,
    completed_at = now(),
    duration_ms = (EXTRACT(EPOCH FROM (now() - COALESCE(started_at, created_at))) * 1000)::int
WHERE org_id = $1 AND id = $2
`

type FinalizeRunParams struct {
	OrgID        pgtype.UUID `json:"org_id"`
	ID           pgtype.UUID `json:"id"`
	Output       *string     `json:"output"`
	InputTokens  int32       `json:"input_tokens"`
	OutputTokens int32       `json:"output_tokens"`
	CachedTokens int32       `json:"cached_tokens"`
}

// Fills in the completion-summary fields checkpoint() itself doesn't own
// (status stays checkpoint()'s alone) — only called once a run reaches a
// genuinely terminal status, never for awaiting_approval.
func (q *Queries) FinalizeRun(ctx context.Context, arg FinalizeRunParams) error {
	_, err := q.db.Exec(ctx, finalizeRun,
		arg.OrgID,
		arg.ID,
		arg.Output,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CachedTokens,
	)
	return err
}

const getOrgRunSettings = `-- name: GetOrgRunSettings :one

SELECT llm_provider, agents_paused FROM organizations WHERE id = $1
`

type GetOrgRunSettingsRow struct {
	LlmProvider  *string `json:"llm_provider"`
	AgentsPaused bool    `json:"agents_paused"`
}

// graph.Launcher's run lifecycle (POST /workflows/{id}/run's async goroutine
// — see internal/core/graph/launch.go) and the read-only HTTP endpoints
// (GET /runs, GET /runs/{id}).
// Preflight (kill switch) + provider resolution for Launcher.Launch.
func (q *Queries) GetOrgRunSettings(ctx context.Context, id pgtype.UUID) (GetOrgRunSettingsRow, error) {
	row := q.db.QueryRow(ctx, getOrgRunSettings, id)
	var i GetOrgRunSettingsRow
	err := row.Scan(&i.LlmProvider, &i.AgentsPaused)
	return i, err
}

const getRunCheckpoint = `-- name: GetRunCheckpoint :one
SELECT checkpoint_state, current_node, cost_so_far_usd, tool_call_count, status
FROM workflow_runs
WHERE org_id = $1 AND id = $2
`

type GetRunCheckpointParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

type GetRunCheckpointRow struct {
	CheckpointState []byte  `json:"checkpoint_state"`
	CurrentNode     *string `json:"current_node"`
	CostSoFarUsd    float64 `json:"cost_so_far_usd"`
	ToolCallCount   int32   `json:"tool_call_count"`
	Status          string  `json:"status"`
}

func (q *Queries) GetRunCheckpoint(ctx context.Context, arg GetRunCheckpointParams) (GetRunCheckpointRow, error) {
	row := q.db.QueryRow(ctx, getRunCheckpoint, arg.OrgID, arg.ID)
	var i GetRunCheckpointRow
	err := row.Scan(
		&i.CheckpointState,
		&i.CurrentNode,
		&i.CostSoFarUsd,
		&i.ToolCallCount,
		&i.Status,
	)
	return i, err
}

const getRunDetail = `-- name: GetRunDetail :one
SELECT id, workflow_id, status, triggered_by, output, input_tokens, output_tokens,
       cached_tokens, cost_so_far_usd, tool_call_count, started_at, completed_at,
       duration_ms, created_at
FROM workflow_runs
WHERE org_id = $1 AND id = $2
`

type GetRunDetailParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

type GetRunDetailRow struct {
	ID            pgtype.UUID        `json:"id"`
	WorkflowID    pgtype.UUID        `json:"workflow_id"`
	Status        string             `json:"status"`
	TriggeredBy   pgtype.UUID        `json:"triggered_by"`
	Output        *string            `json:"output"`
	InputTokens   int32              `json:"input_tokens"`
	OutputTokens  int32              `json:"output_tokens"`
	CachedTokens  int32              `json:"cached_tokens"`
	CostSoFarUsd  float64            `json:"cost_so_far_usd"`
	ToolCallCount int32              `json:"tool_call_count"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	DurationMs    *int32             `json:"duration_ms"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetRunDetail(ctx context.Context, arg GetRunDetailParams) (GetRunDetailRow, error) {
	row := q.db.QueryRow(ctx, getRunDetail, arg.OrgID, arg.ID)
	var i GetRunDetailRow
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Status,
		&i.TriggeredBy,
		&i.Output,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedTokens,
		&i.CostSoFarUsd,
		&i.ToolCallCount,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const getRunStatus = `-- name: GetRunStatus :one
SELECT status FROM workflow_runs WHERE org_id = $1 AND id = $2
`

type GetRunStatusParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

// Read back the definitive status Engine's own checkpoint() already
// wrote (completed/failed/cancelled/awaiting_approval) — Launcher can't
// infer this from Engine.Run's returned error alone, since a suspended
// run also returns a nil error.
func (q *Queries) GetRunStatus(ctx context.Context, arg GetRunStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, getRunStatus, arg.OrgID, arg.ID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const listRunsForOrg = `-- name: ListRunsForOrg :many
SELECT id, workflow_id, status, output, cost_so_far_usd, started_at, completed_at,
       duration_ms, created_at
FROM workflow_runs
WHERE org_id = $1
  AND ($4::varchar IS NULL OR status = $4)
  AND ($5::uuid IS NULL OR workflow_id = $5)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRunsForOrgParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	Status     *string     `json:"status"`
	WorkflowID pgtype.UUID `json:"workflow_id"`
}

type ListRunsForOrgRow struct {
	ID           pgtype.UUID        `json:"id"`
	WorkflowID   pgtype.UUID        `json:"workflow_id"`
	Status       string             `json:"status"`
	Output       *string            `json:"output"`
	CostSoFarUsd float64            `json:"cost_so_far_usd"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	DurationMs   *int32             `json:"duration_ms"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListRunsForOrg(ctx context.Context, arg ListRunsForOrgParams) ([]ListRunsForOrgRow, error) {
	rows, err := q.db.Query(ctx, listRunsForOrg,
		arg.OrgID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.WorkflowID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunsForOrgRow
	for rows.Next() {
		var i ListRunsForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.Status,
			&i.Output,
			&i.CostSoFarUsd,
			&i.StartedAt,
			&i.CompletedAt,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRunFailedPreflight = `-- name: MarkRunFailedPreflight :exec
UPDATE workflow_runs SET status = 'failed', completed_at = now() WHERE org_id = $1 AND id = $2
`

type MarkRunFailedPreflightParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

// Used only when dependency resolution itself fails before Engine.Run
// ever starts (a bad policy_scope, a registry error, ...) — there's no
// checkpoint yet for a normal Engine-driven "failed" transition to have
// written, so this writes the terminal status directly.
func (q *Queries) MarkRunFailedPreflight(ctx context.Context, arg MarkRunFailedPreflightParams) error {
	_, err := q.db.Exec(ctx, markRunFailedPreflight, arg.OrgID, arg.ID)
	return err
}

const markRunStarted = `-- name: MarkRunStarted :exec
UPDATE workflow_runs SET status = 'running', started_at = now() WHERE org_id = $1 AND id = $2
`

type MarkRunStartedParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) MarkRunStarted(ctx context.Context, arg MarkRunStartedParams) error {
	_, err := q.db.Exec(ctx, markRunStarted, arg.OrgID, arg.ID)
	return err
}

const updateRunCheckpoint = `-- name: UpdateRunCheckpoint :exec

UPDATE workflow_runs
SET checkpoint_state = $3,
    current_node     = $4,
    cost_so_far_usd  = $5,
    tool_call_count  = $6,
    status           = $7
WHERE org_id = $1 AND id = $2
`

type UpdateRunCheckpointParams struct {
	OrgID           pgtype.UUID `json:"org_id"`
	ID              pgtype.UUID `json:"id"`
	CheckpointState []byte      `json:"checkpoint_state"`
	CurrentNode     *string     `json:"current_node"`
	CostSoFarUsd    float64     `json:"cost_so_far_usd"`
	ToolCallCount   int32       `json:"tool_call_count"`
	Status          string      `json:"status"`
}

// internal/core/graph's checkpoint read/write — the engine.Run/Resume/checkpoint
// calls added workflow9_engine_guardrails.up.sql for. Always run through
// tenant.WithTx (a fresh transaction per call, org-scoped) — never held open across
// a node's tool-call loop or an approval-gate pause. See WORKFLOW_PLAN_GO.md's
// Workflow 9 harness planning notes for the full reasoning.
func (q *Queries) UpdateRunCheckpoint(ctx context.Context, arg UpdateRunCheckpointParams) error {
	_, err := q.db.Exec(ctx, updateRunCheckpoint,
		arg.OrgID,
		arg.ID,
		arg.CheckpointState,
		arg.CurrentNode,
		arg.CostSoFarUsd,
		arg.ToolCallCount,
		arg.Status,
	)
	return err
}
