// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integrations.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConnectionByOrgService = `-- name: GetConnectionByOrgService :one
SELECT id, service_name, display_name, credential_provider, encrypted_credentials,
       oauth_status, oauth_scopes, token_expires_at, is_active, created_at
FROM mcp_connections
WHERE org_id = $1 AND service_name = $2
`

type GetConnectionByOrgServiceParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	ServiceName string      `json:"service_name"`
}

type GetConnectionByOrgServiceRow struct {
	ID                   pgtype.UUID        `json:"id"`
	ServiceName          string             `json:"service_name"`
	DisplayName          *string            `json:"display_name"`
	CredentialProvider   *string            `json:"credential_provider"`
	EncryptedCredentials *string            `json:"encrypted_credentials"`
	OauthStatus          *string            `json:"oauth_status"`
	OauthScopes          []byte             `json:"oauth_scopes"`
	TokenExpiresAt       pgtype.Timestamptz `json:"token_expires_at"`
	IsActive             *bool              `json:"is_active"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetConnectionByOrgService(ctx context.Context, arg GetConnectionByOrgServiceParams) (GetConnectionByOrgServiceRow, error) {
	row := q.db.QueryRow(ctx, getConnectionByOrgService, arg.OrgID, arg.ServiceName)
	var i GetConnectionByOrgServiceRow
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.DisplayName,
		&i.CredentialProvider,
		&i.EncryptedCredentials,
		&i.OauthStatus,
		&i.OauthScopes,
		&i.TokenExpiresAt,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listConnectionsByOrg = `-- name: ListConnectionsByOrg :many
SELECT service_name, oauth_status, oauth_scopes, is_active, created_at
FROM mcp_connections
WHERE org_id = $1
`

type ListConnectionsByOrgRow struct {
	ServiceName string             `json:"service_name"`
	OauthStatus *string            `json:"oauth_status"`
	OauthScopes []byte             `json:"oauth_scopes"`
	IsActive    *bool              `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListConnectionsByOrg(ctx context.Context, orgID pgtype.UUID) ([]ListConnectionsByOrgRow, error) {
	rows, err := q.db.Query(ctx, listConnectionsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConnectionsByOrgRow
	for rows.Next() {
		var i ListConnectionsByOrgRow
		if err := rows.Scan(
			&i.ServiceName,
			&i.OauthStatus,
			&i.OauthScopes,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringConnectionsSystem = `-- name: ListExpiringConnectionsSystem :many
SELECT id, org_id, service_name, encrypted_credentials
FROM mcp_connections
WHERE is_active = true
  AND oauth_status = 'connected'
  AND token_expires_at IS NOT NULL
  AND token_expires_at < $1
`

type ListExpiringConnectionsSystemRow struct {
	ID                   pgtype.UUID `json:"id"`
	OrgID                pgtype.UUID `json:"org_id"`
	ServiceName          string      `json:"service_name"`
	EncryptedCredentials *string     `json:"encrypted_credentials"`
}

// Used only by the background refresh job (app_system pool). Scoped to
// oauth_status = 'connected' so a already-expired or revoked connection
// isn't retried every 30 minutes forever.
func (q *Queries) ListExpiringConnectionsSystem(ctx context.Context, tokenExpiresAt pgtype.Timestamptz) ([]ListExpiringConnectionsSystemRow, error) {
	rows, err := q.db.Query(ctx, listExpiringConnectionsSystem, tokenExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiringConnectionsSystemRow
	for rows.Next() {
		var i ListExpiringConnectionsSystemRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ServiceName,
			&i.EncryptedCredentials,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConnectionExpired = `-- name: MarkConnectionExpired :execrows
UPDATE mcp_connections
SET oauth_status = 'expired'
WHERE org_id = $1 AND service_name = $2
`

type MarkConnectionExpiredParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	ServiceName string      `json:"service_name"`
}

func (q *Queries) MarkConnectionExpired(ctx context.Context, arg MarkConnectionExpiredParams) (int64, error) {
	result, err := q.db.Exec(ctx, markConnectionExpired, arg.OrgID, arg.ServiceName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markConnectionExpiredByIDSystem = `-- name: MarkConnectionExpiredByIDSystem :execrows
UPDATE mcp_connections
SET oauth_status = 'expired'
WHERE id = $1
`

func (q *Queries) MarkConnectionExpiredByIDSystem(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markConnectionExpiredByIDSystem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeConnection = `-- name: RevokeConnection :execrows
UPDATE mcp_connections
SET is_active = false, oauth_status = 'revoked'
WHERE org_id = $1 AND service_name = $2
`

type RevokeConnectionParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	ServiceName string      `json:"service_name"`
}

func (q *Queries) RevokeConnection(ctx context.Context, arg RevokeConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeConnection, arg.OrgID, arg.ServiceName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateConnectionTokens = `-- name: UpdateConnectionTokens :execrows
UPDATE mcp_connections
SET encrypted_credentials = $3, token_expires_at = $4, oauth_status = 'connected'
WHERE org_id = $1 AND service_name = $2
`

type UpdateConnectionTokensParams struct {
	OrgID                pgtype.UUID        `json:"org_id"`
	ServiceName          string             `json:"service_name"`
	EncryptedCredentials *string            `json:"encrypted_credentials"`
	TokenExpiresAt       pgtype.Timestamptz `json:"token_expires_at"`
}

func (q *Queries) UpdateConnectionTokens(ctx context.Context, arg UpdateConnectionTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateConnectionTokens,
		arg.OrgID,
		arg.ServiceName,
		arg.EncryptedCredentials,
		arg.TokenExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateConnectionTokensByIDSystem = `-- name: UpdateConnectionTokensByIDSystem :execrows
UPDATE mcp_connections
SET encrypted_credentials = $2, token_expires_at = $3, oauth_status = 'connected'
WHERE id = $1
`

type UpdateConnectionTokensByIDSystemParams struct {
	ID                   pgtype.UUID        `json:"id"`
	EncryptedCredentials *string            `json:"encrypted_credentials"`
	TokenExpiresAt       pgtype.Timestamptz `json:"token_expires_at"`
}

// Used only by the background refresh job (app_system pool) — targets a
// specific connection by id, already scoped to the right org by virtue of
// having come from ListExpiringConnectionsSystem's own row.
func (q *Queries) UpdateConnectionTokensByIDSystem(ctx context.Context, arg UpdateConnectionTokensByIDSystemParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateConnectionTokensByIDSystem, arg.ID, arg.EncryptedCredentials, arg.TokenExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertConnection = `-- name: UpsertConnection :one

INSERT INTO mcp_connections (
    org_id, service_name, display_name, credential_provider,
    encrypted_credentials, oauth_status, oauth_scopes, token_expires_at, is_active
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, true)
ON CONFLICT (org_id, service_name) DO UPDATE SET
    display_name          = EXCLUDED.display_name,
    credential_provider    = EXCLUDED.credential_provider,
    encrypted_credentials  = EXCLUDED.encrypted_credentials,
    oauth_status           = EXCLUDED.oauth_status,
    oauth_scopes           = EXCLUDED.oauth_scopes,
    token_expires_at       = EXCLUDED.token_expires_at,
    is_active               = true
RETURNING id
`

type UpsertConnectionParams struct {
	OrgID                pgtype.UUID        `json:"org_id"`
	ServiceName          string             `json:"service_name"`
	DisplayName          *string            `json:"display_name"`
	CredentialProvider   *string            `json:"credential_provider"`
	EncryptedCredentials *string            `json:"encrypted_credentials"`
	OauthStatus          *string            `json:"oauth_status"`
	OauthScopes          []byte             `json:"oauth_scopes"`
	TokenExpiresAt       pgtype.Timestamptz `json:"token_expires_at"`
}

// Queries backing third-party integration connections (workflow 4),
// against the mcp_connections table. Per-org reads/writes (connect,
// callback, api-key, status, delete) run through app_user via
// tenant.WithTx, same as api_key_registry in api_keys.sql. The two
// "System" queries below are the exception — the background token-refresh
// job scans expiring connections across every org, which is inherently a
// cross-tenant system-context operation (same reasoning as clerk_sync.sql),
// so those run against app_system (BYPASSRLS) directly, never through
// tenant.WithTx.
func (q *Queries) UpsertConnection(ctx context.Context, arg UpsertConnectionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertConnection,
		arg.OrgID,
		arg.ServiceName,
		arg.DisplayName,
		arg.CredentialProvider,
		arg.EncryptedCredentials,
		arg.OauthStatus,
		arg.OauthScopes,
		arg.TokenExpiresAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
