// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID                     pgtype.UUID        `json:"id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	OrgID                  pgtype.UUID        `json:"org_id"`
	Name                   string             `json:"name"`
	Slug                   string             `json:"slug"`
	Description            *string            `json:"description"`
	AgentType              string             `json:"agent_type"`
	Model                  *string            `json:"model"`
	SystemPrompt           string             `json:"system_prompt"`
	ContextWindowTokens    *int32             `json:"context_window_tokens"`
	MaxOutputTokens        *int32             `json:"max_output_tokens"`
	Temperature            *float64           `json:"temperature"`
	A2aEndpoint            *string            `json:"a2a_endpoint"`
	TeamRole               *string            `json:"team_role"`
	A2aManifest            []byte             `json:"a2a_manifest"`
	ExtendedThinking       *bool              `json:"extended_thinking"`
	ExtendedThinkingConfig []byte             `json:"extended_thinking_config"`
	PolicyScope            []byte             `json:"policy_scope"`
	AllowedMcpServers      []byte             `json:"allowed_mcp_servers"`
	IsActive               *bool              `json:"is_active"`
	Version                *int32             `json:"version"`
	CreatedBy              pgtype.UUID        `json:"created_by"`
}

type AgentTeam struct {
	ID                  pgtype.UUID        `json:"id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	OrgID               pgtype.UUID        `json:"org_id"`
	Name                string             `json:"name"`
	Description         *string            `json:"description"`
	OrchestratorAgentID pgtype.UUID        `json:"orchestrator_agent_id"`
	A2aManifest         []byte             `json:"a2a_manifest"`
	MaxAgentHops        *int32             `json:"max_agent_hops"`
	ParallelExecution   *bool              `json:"parallel_execution"`
	TimeoutSeconds      *int32             `json:"timeout_seconds"`
	IsActive            *bool              `json:"is_active"`
}

type AgentTeamMember struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	TeamID    pgtype.UUID        `json:"team_id"`
	AgentID   pgtype.UUID        `json:"agent_id"`
	Role      string             `json:"role"`
	Priority  *int32             `json:"priority"`
}

type ApiKeyRegistry struct {
	ID           pgtype.UUID        `json:"id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	OrgID        pgtype.UUID        `json:"org_id"`
	Provider     string             `json:"provider"`
	KeyPrefix    string             `json:"key_prefix"`
	EncryptedKey string             `json:"encrypted_key"`
	KmsKeyID     string             `json:"kms_key_id"`
	IsValid      *bool              `json:"is_valid"`
	LastUsedAt   pgtype.Timestamptz `json:"last_used_at"`
}

type Approval struct {
	ID          pgtype.UUID        `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	RunID       pgtype.UUID        `json:"run_id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Status      *string            `json:"status"`
	ContextData []byte             `json:"context_data"`
}

type ApprovalDecision struct {
	ID         pgtype.UUID        `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ApprovalID pgtype.UUID        `json:"approval_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Decision   string             `json:"decision"`
	Reason     *string            `json:"reason"`
}

type AuditLog struct {
	ID           pgtype.UUID        `json:"id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	OrgID        pgtype.UUID        `json:"org_id"`
	ActorID      pgtype.UUID        `json:"actor_id"`
	ActorType    string             `json:"actor_type"`
	Action       string             `json:"action"`
	ResourceType *string            `json:"resource_type"`
	ResourceID   pgtype.UUID        `json:"resource_id"`
	Status       *string            `json:"status"`
	IpAddress    *string            `json:"ip_address"`
	MetadataInfo []byte             `json:"metadata_info"`
}

type CostLedger struct {
	ID               pgtype.UUID        `json:"id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	OrgID            pgtype.UUID        `json:"org_id"`
	RunID            pgtype.UUID        `json:"run_id"`
	AgentID          pgtype.UUID        `json:"agent_id"`
	CostType         string             `json:"cost_type"`
	Provider         *string            `json:"provider"`
	Model            *string            `json:"model"`
	InputTokens      *int32             `json:"input_tokens"`
	OutputTokens     *int32             `json:"output_tokens"`
	CachedTokens     *int32             `json:"cached_tokens"`
	ThinkingTokens   *int32             `json:"thinking_tokens"`
	EstimatedCostUsd float64            `json:"estimated_cost_usd"`
}

type Document struct {
	ID               pgtype.UUID        `json:"id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	OrgID            pgtype.UUID        `json:"org_id"`
	Filename         string             `json:"filename"`
	S3Path           string             `json:"s3_path"`
	MimeType         *string            `json:"mime_type"`
	ByteSize         *int32             `json:"byte_size"`
	Category         *string            `json:"category"`
	ProcessingStatus *string            `json:"processing_status"`
	TotalChunks      *int32             `json:"total_chunks"`
	IndexedAt        pgtype.Timestamptz `json:"indexed_at"`
	ErrorDetail      *string            `json:"error_detail"`
	VectorID         *string            `json:"vector_id"`
	UploadedBy       pgtype.UUID        `json:"uploaded_by"`
}

type DocumentChunk struct {
	ID         pgtype.UUID        `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DocID      pgtype.UUID        `json:"doc_id"`
	ChunkIndex int32              `json:"chunk_index"`
	PineconeID string             `json:"pinecone_id"`
}

type McpConnection struct {
	ID                   pgtype.UUID        `json:"id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	OrgID                pgtype.UUID        `json:"org_id"`
	ServiceName          string             `json:"service_name"`
	DisplayName          *string            `json:"display_name"`
	CredentialProvider   *string            `json:"credential_provider"`
	EncryptedCredentials *string            `json:"encrypted_credentials"`
	OauthStatus          *string            `json:"oauth_status"`
	OauthScopes          []byte             `json:"oauth_scopes"`
	TokenExpiresAt       pgtype.Timestamptz `json:"token_expires_at"`
	IsActive             *bool              `json:"is_active"`
	LastUsedAt           pgtype.Timestamptz `json:"last_used_at"`
}

type Organization struct {
	ID                   pgtype.UUID        `json:"id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	Name                 string             `json:"name"`
	Slug                 string             `json:"slug"`
	ClerkOrgID           string             `json:"clerk_org_id"`
	ActiveApiKeyID       pgtype.UUID        `json:"active_api_key_id"`
	LlmProvider          *string            `json:"llm_provider"`
	PlanTier             *string            `json:"plan_tier"`
	MaxAgents            *int32             `json:"max_agents"`
	MaxWorkflows         *int32             `json:"max_workflows"`
	MaxRagStorageGb      *int32             `json:"max_rag_storage_gb"`
	MaxMcpIntegrations   *int32             `json:"max_mcp_integrations"`
	StripeCustomerID     *string            `json:"stripe_customer_id"`
	StripeSubscriptionID *string            `json:"stripe_subscription_id"`
	SubscriptionStatus   *string            `json:"subscription_status"`
	TrialEndsAt          pgtype.Timestamptz `json:"trial_ends_at"`
	Settings             []byte             `json:"settings"`
	OnboardingCompleted  *bool              `json:"onboarding_completed"`
	IsActive             *bool              `json:"is_active"`
}

type Session struct {
	ID             pgtype.UUID        `json:"id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	UserID         pgtype.UUID        `json:"user_id"`
	OrgID          pgtype.UUID        `json:"org_id"`
	ClerkSessionID *string            `json:"clerk_session_id"`
	IpAddress      *netip.Addr        `json:"ip_address"`
	UserAgent      *string            `json:"user_agent"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

type User struct {
	ID                    pgtype.UUID        `json:"id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	OrgID                 pgtype.UUID        `json:"org_id"`
	ClerkUserID           string             `json:"clerk_user_id"`
	Email                 string             `json:"email"`
	FullName              *string            `json:"full_name"`
	AvatarUrl             *string            `json:"avatar_url"`
	Role                  string             `json:"role"`
	CanManageApiKeys      *bool              `json:"can_manage_api_keys"`
	CanManageIntegrations *bool              `json:"can_manage_integrations"`
	CanApproveWorkflows   *bool              `json:"can_approve_workflows"`
	IsActive              *bool              `json:"is_active"`
	LastLoginAt           pgtype.Timestamptz `json:"last_login_at"`
}

type VectorNamespace struct {
	ID          pgtype.UUID        `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Namespace   string             `json:"namespace"`
	Description *string            `json:"description"`
}

type Workflow struct {
	ID                     pgtype.UUID        `json:"id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	OrgID                  pgtype.UUID        `json:"org_id"`
	AgentID                pgtype.UUID        `json:"agent_id"`
	TeamID                 pgtype.UUID        `json:"team_id"`
	Name                   string             `json:"name"`
	Description            *string            `json:"description"`
	TriggerType            string             `json:"trigger_type"`
	GraphDefinition        []byte             `json:"graph_definition"`
	InputSchema            []byte             `json:"input_schema"`
	OutputSchema           []byte             `json:"output_schema"`
	MaxAgentHops           *int32             `json:"max_agent_hops"`
	A2aEnabled             *bool              `json:"a2a_enabled"`
	RequiresApproval       *bool              `json:"requires_approval"`
	ApprovalConditions     []byte             `json:"approval_conditions"`
	CronExpression         *string            `json:"cron_expression"`
	Timezone               *string            `json:"timezone"`
	NextRunAt              pgtype.Timestamptz `json:"next_run_at"`
	IsActive               *bool              `json:"is_active"`
	Version                *int32             `json:"version"`
	CreatedBy              pgtype.UUID        `json:"created_by"`
	TaskInputTemplate      *string            `json:"task_input_template"`
	EstimatedManualMinutes *int32             `json:"estimated_manual_minutes"`
}

type WorkflowRun struct {
	ID          pgtype.UUID        `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	WorkflowID  pgtype.UUID        `json:"workflow_id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	TriggeredBy pgtype.UUID        `json:"triggered_by"`
	Status      string             `json:"status"`
	RunTrace    []byte             `json:"run_trace"`
}

type WorkflowStep struct {
	ID         pgtype.UUID        `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	RunID      pgtype.UUID        `json:"run_id"`
	NodeName   string             `json:"node_name"`
	StepType   string             `json:"step_type"`
	InputData  []byte             `json:"input_data"`
	OutputData []byte             `json:"output_data"`
	DurationMs *int32             `json:"duration_ms"`
	Status     *string            `json:"status"`
}
