// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: observability.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :exec

INSERT INTO audit_logs (org_id, actor_id, actor_type, action, resource_type, resource_id, status, metadata_info)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAuditLogParams struct {
	OrgID        pgtype.UUID `json:"org_id"`
	ActorID      pgtype.UUID `json:"actor_id"`
	ActorType    string      `json:"actor_type"`
	Action       string      `json:"action"`
	ResourceType *string     `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
	Status       *string     `json:"status"`
	MetadataInfo []byte      `json:"metadata_info"`
}

// Written from internal/core/graph/observability.go — every tool call
// and every LLM call the executor makes writes one row to each of these,
// closing the "nothing existing to reuse" gap flagged in the Workflow 9
// harness planning notes. Real per-token dollar pricing is workflow 11's
// job (see WORKFLOW_PLAN_GO.md) — estimated_cost_usd is written as 0 for
// now; token counts themselves are real and useful on their own.
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.OrgID,
		arg.ActorID,
		arg.ActorType,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Status,
		arg.MetadataInfo,
	)
	return err
}

const insertCostLedgerEntry = `-- name: InsertCostLedgerEntry :exec
INSERT INTO cost_ledger (org_id, run_id, agent_id, cost_type, provider, model, input_tokens, output_tokens, cached_tokens, estimated_cost_usd)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertCostLedgerEntryParams struct {
	OrgID            pgtype.UUID `json:"org_id"`
	RunID            pgtype.UUID `json:"run_id"`
	AgentID          pgtype.UUID `json:"agent_id"`
	CostType         string      `json:"cost_type"`
	Provider         *string     `json:"provider"`
	Model            *string     `json:"model"`
	InputTokens      *int32      `json:"input_tokens"`
	OutputTokens     *int32      `json:"output_tokens"`
	CachedTokens     *int32      `json:"cached_tokens"`
	EstimatedCostUsd float64     `json:"estimated_cost_usd"`
}

func (q *Queries) InsertCostLedgerEntry(ctx context.Context, arg InsertCostLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, insertCostLedgerEntry,
		arg.OrgID,
		arg.RunID,
		arg.AgentID,
		arg.CostType,
		arg.Provider,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CachedTokens,
		arg.EstimatedCostUsd,
	)
	return err
}
