// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: org.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deactivateMember = `-- name: DeactivateMember :exec
UPDATE users SET is_active = false WHERE org_id = $1 AND id = $2
`

type DeactivateMemberParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

// Only ever called after the real Clerk-side removal already succeeded —
// see Handler.Remove's doc comment for why the ordering matters.
func (q *Queries) DeactivateMember(ctx context.Context, arg DeactivateMemberParams) error {
	_, err := q.db.Exec(ctx, deactivateMember, arg.OrgID, arg.ID)
	return err
}

const getOrgMemberForUpdate = `-- name: GetOrgMemberForUpdate :one
SELECT id, clerk_user_id, role FROM users
WHERE org_id = $1 AND id = $2 AND is_active = true
`

type GetOrgMemberForUpdateParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

type GetOrgMemberForUpdateRow struct {
	ID          pgtype.UUID `json:"id"`
	ClerkUserID string      `json:"clerk_user_id"`
	Role        string      `json:"role"`
}

// Confirms the target member belongs to the caller's own org (cross-org
// access is a 404 here, same "wrong org is indistinguishable from doesn't
// exist" convention as every other tenant-scoped lookup in this codebase)
// and returns clerk_user_id, needed for the Clerk-side sync call.
func (q *Queries) GetOrgMemberForUpdate(ctx context.Context, arg GetOrgMemberForUpdateParams) (GetOrgMemberForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getOrgMemberForUpdate, arg.OrgID, arg.ID)
	var i GetOrgMemberForUpdateRow
	err := row.Scan(&i.ID, &i.ClerkUserID, &i.Role)
	return i, err
}

const listOrgMembers = `-- name: ListOrgMembers :many

SELECT id, clerk_user_id, email, full_name, avatar_url, role,
       can_manage_api_keys, can_manage_integrations, can_approve_workflows,
       last_login_at, created_at
FROM users
WHERE org_id = $1 AND is_active = true
ORDER BY created_at ASC
`

type ListOrgMembersRow struct {
	ID                    pgtype.UUID        `json:"id"`
	ClerkUserID           string             `json:"clerk_user_id"`
	Email                 string             `json:"email"`
	FullName              *string            `json:"full_name"`
	AvatarUrl             *string            `json:"avatar_url"`
	Role                  string             `json:"role"`
	CanManageApiKeys      *bool              `json:"can_manage_api_keys"`
	CanManageIntegrations *bool              `json:"can_manage_integrations"`
	CanApproveWorkflows   *bool              `json:"can_approve_workflows"`
	LastLoginAt           pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

// Workflow 13 (team members & roles). Postgres — kept in sync by the Clerk
// webhook (clerk_sync.sql) — is this app's own source of truth for role
// display; internal/api/org/handler.go doesn't call out to Clerk's API on
// every list, only on a role change or removal (see that package's own
// doc comment for why).
func (q *Queries) ListOrgMembers(ctx context.Context, orgID pgtype.UUID) ([]ListOrgMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrgMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgMembersRow
	for rows.Next() {
		var i ListOrgMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.ClerkUserID,
			&i.Email,
			&i.FullName,
			&i.AvatarUrl,
			&i.Role,
			&i.CanManageApiKeys,
			&i.CanManageIntegrations,
			&i.CanApproveWorkflows,
			&i.LastLoginAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberRoleAndPermissions = `-- name: UpdateMemberRoleAndPermissions :exec
UPDATE users
SET role = $3, can_manage_api_keys = $4, can_manage_integrations = $5, can_approve_workflows = $6
WHERE org_id = $1 AND id = $2
`

type UpdateMemberRoleAndPermissionsParams struct {
	OrgID                 pgtype.UUID `json:"org_id"`
	ID                    pgtype.UUID `json:"id"`
	Role                  string      `json:"role"`
	CanManageApiKeys      *bool       `json:"can_manage_api_keys"`
	CanManageIntegrations *bool       `json:"can_manage_integrations"`
	CanApproveWorkflows   *bool       `json:"can_approve_workflows"`
}

// Permission flags are recomputed from the new role (see
// internal/api/org/handler.go's defaultPermissionsForRole), not passed
// through as independent client input — the schema's can_manage_* columns
// exist for other code (can_approve_workflows is already read directly by
// internal/api/approvals) to check without needing to know this app's role
// hierarchy, but they're derived, not separately settable.
func (q *Queries) UpdateMemberRoleAndPermissions(ctx context.Context, arg UpdateMemberRoleAndPermissionsParams) error {
	_, err := q.db.Exec(ctx, updateMemberRoleAndPermissions,
		arg.OrgID,
		arg.ID,
		arg.Role,
		arg.CanManageApiKeys,
		arg.CanManageIntegrations,
		arg.CanApproveWorkflows,
	)
	return err
}
