// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: practice.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveClientWorkspaces = `-- name: CountActiveClientWorkspaces :one
SELECT count(*) FROM organizations WHERE parent_practice_id = $1 AND is_active = true
`

func (q *Queries) CountActiveClientWorkspaces(ctx context.Context, parentPracticeID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveClientWorkspaces, parentPracticeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deactivateClientWorkspace = `-- name: DeactivateClientWorkspace :execrows
UPDATE organizations SET is_active = false, deactivated_at = now()
WHERE id = $1 AND parent_practice_id = $2 AND is_active = true
`

type DeactivateClientWorkspaceParams struct {
	ID               pgtype.UUID `json:"id"`
	ParentPracticeID pgtype.UUID `json:"parent_practice_id"`
}

func (q *Queries) DeactivateClientWorkspace(ctx context.Context, arg DeactivateClientWorkspaceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateClientWorkspace, arg.ID, arg.ParentPracticeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getClientWorkspaceForCaller = `-- name: GetClientWorkspaceForCaller :one
SELECT o.id, o.clerk_org_id, o.name, o.is_active, o.deactivated_at
FROM organizations o
JOIN users u ON u.org_id = o.id AND u.clerk_user_id = $3 AND u.is_active = true
WHERE o.id = $1 AND o.parent_practice_id = $2
`

type GetClientWorkspaceForCallerParams struct {
	ID               pgtype.UUID `json:"id"`
	ParentPracticeID pgtype.UUID `json:"parent_practice_id"`
	ClerkUserID      string      `json:"clerk_user_id"`
}

type GetClientWorkspaceForCallerRow struct {
	ID            pgtype.UUID        `json:"id"`
	ClerkOrgID    string             `json:"clerk_org_id"`
	Name          string             `json:"name"`
	IsActive      *bool              `json:"is_active"`
	DeactivatedAt pgtype.Timestamptz `json:"deactivated_at"`
}

func (q *Queries) GetClientWorkspaceForCaller(ctx context.Context, arg GetClientWorkspaceForCallerParams) (GetClientWorkspaceForCallerRow, error) {
	row := q.db.QueryRow(ctx, getClientWorkspaceForCaller, arg.ID, arg.ParentPracticeID, arg.ClerkUserID)
	var i GetClientWorkspaceForCallerRow
	err := row.Scan(
		&i.ID,
		&i.ClerkOrgID,
		&i.Name,
		&i.IsActive,
		&i.DeactivatedAt,
	)
	return i, err
}

const getPortfolioSummary = `-- name: GetPortfolioSummary :one
SELECT
    count(*)::bigint AS active_workspaces,
    COALESCE(SUM(o.total_hours_saved), 0)::double precision AS hours_saved,
    COALESCE(SUM((SELECT count(*) FROM workflow_runs wr
        WHERE wr.org_id = o.id AND wr.parent_run_id IS NULL
          AND wr.status IN ('pending', 'running', 'awaiting_approval'))), 0)::bigint AS active_runs,
    COALESCE(SUM((SELECT count(*) FROM approvals ap
        WHERE ap.org_id = o.id AND ap.status = 'pending')), 0)::bigint AS pending_approvals,
    COALESCE(SUM((SELECT COALESCE(SUM(cl.estimated_cost_usd), 0) FROM cost_ledger cl
        WHERE cl.org_id = o.id)), 0)::double precision AS total_cost_usd
FROM organizations o
JOIN users u ON u.org_id = o.id AND u.clerk_user_id = $2 AND u.is_active = true
WHERE o.parent_practice_id = $1 AND o.is_active = true
`

type GetPortfolioSummaryParams struct {
	ParentPracticeID pgtype.UUID `json:"parent_practice_id"`
	ClerkUserID      string      `json:"clerk_user_id"`
}

type GetPortfolioSummaryRow struct {
	ActiveWorkspaces int64   `json:"active_workspaces"`
	HoursSaved       float64 `json:"hours_saved"`
	ActiveRuns       int64   `json:"active_runs"`
	PendingApprovals int64   `json:"pending_approvals"`
	TotalCostUsd     float64 `json:"total_cost_usd"`
}

func (q *Queries) GetPortfolioSummary(ctx context.Context, arg GetPortfolioSummaryParams) (GetPortfolioSummaryRow, error) {
	row := q.db.QueryRow(ctx, getPortfolioSummary, arg.ParentPracticeID, arg.ClerkUserID)
	var i GetPortfolioSummaryRow
	err := row.Scan(
		&i.ActiveWorkspaces,
		&i.HoursSaved,
		&i.ActiveRuns,
		&i.PendingApprovals,
		&i.TotalCostUsd,
	)
	return i, err
}

const getPracticeForUpdate = `-- name: GetPracticeForUpdate :one
SELECT id, organization_type, max_client_workspaces
FROM organizations WHERE id = $1 AND is_active = true
FOR UPDATE
`

type GetPracticeForUpdateRow struct {
	ID                  pgtype.UUID `json:"id"`
	OrganizationType    string      `json:"organization_type"`
	MaxClientWorkspaces int32       `json:"max_client_workspaces"`
}

// Row lock serializes concurrent creates against the same practice, so two
// simultaneous requests can't both pass the max_client_workspaces check.
func (q *Queries) GetPracticeForUpdate(ctx context.Context, id pgtype.UUID) (GetPracticeForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getPracticeForUpdate, id)
	var i GetPracticeForUpdateRow
	err := row.Scan(&i.ID, &i.OrganizationType, &i.MaxClientWorkspaces)
	return i, err
}

const getPracticeLimit = `-- name: GetPracticeLimit :one
SELECT max_client_workspaces FROM organizations WHERE id = $1
`

func (q *Queries) GetPracticeLimit(ctx context.Context, id pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getPracticeLimit, id)
	var max_client_workspaces int32
	err := row.Scan(&max_client_workspaces)
	return max_client_workspaces, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT email, full_name FROM users WHERE id = $1
`

type GetUserProfileRow struct {
	Email    string  `json:"email"`
	FullName *string `json:"full_name"`
}

// Copies the caller's own profile onto the membership row created for a new
// client workspace (users.email is NOT NULL; the session JWT doesn't carry it).
func (q *Queries) GetUserProfile(ctx context.Context, id pgtype.UUID) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, id)
	var i GetUserProfileRow
	err := row.Scan(&i.Email, &i.FullName)
	return i, err
}

const listClientWorkspacesWithStats = `-- name: ListClientWorkspacesWithStats :many
SELECT
    o.id, o.clerk_org_id, o.name, o.slug, o.is_active, o.deactivated_at, o.created_at,
    o.settings,
    o.total_hours_saved::double precision AS hours_saved,
    (SELECT count(*) FROM workflow_runs wr
        WHERE wr.org_id = o.id AND wr.parent_run_id IS NULL
          AND wr.status IN ('pending', 'running', 'awaiting_approval'))::bigint AS active_runs,
    (SELECT count(*) FROM approvals ap
        WHERE ap.org_id = o.id AND ap.status = 'pending')::bigint AS pending_approvals,
    (SELECT COALESCE(SUM(cl.estimated_cost_usd), 0) FROM cost_ledger cl
        WHERE cl.org_id = o.id)::double precision AS total_cost_usd
FROM organizations o
JOIN users u ON u.org_id = o.id AND u.clerk_user_id = $2 AND u.is_active = true
WHERE o.parent_practice_id = $1
ORDER BY o.is_active DESC, o.name
`

type ListClientWorkspacesWithStatsParams struct {
	ParentPracticeID pgtype.UUID `json:"parent_practice_id"`
	ClerkUserID      string      `json:"clerk_user_id"`
}

type ListClientWorkspacesWithStatsRow struct {
	ID               pgtype.UUID        `json:"id"`
	ClerkOrgID       string             `json:"clerk_org_id"`
	Name             string             `json:"name"`
	Slug             string             `json:"slug"`
	IsActive         *bool              `json:"is_active"`
	DeactivatedAt    pgtype.Timestamptz `json:"deactivated_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Settings         []byte             `json:"settings"`
	HoursSaved       float64            `json:"hours_saved"`
	ActiveRuns       int64              `json:"active_runs"`
	PendingApprovals int64              `json:"pending_approvals"`
	TotalCostUsd     float64            `json:"total_cost_usd"`
}

// Includes deactivated workspaces (still inside or past their restore
// window) so the portfolio page can offer a restore; the handler decides
// restorability from deactivated_at.
func (q *Queries) ListClientWorkspacesWithStats(ctx context.Context, arg ListClientWorkspacesWithStatsParams) ([]ListClientWorkspacesWithStatsRow, error) {
	rows, err := q.db.Query(ctx, listClientWorkspacesWithStats, arg.ParentPracticeID, arg.ClerkUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClientWorkspacesWithStatsRow
	for rows.Next() {
		var i ListClientWorkspacesWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClerkOrgID,
			&i.Name,
			&i.Slug,
			&i.IsActive,
			&i.DeactivatedAt,
			&i.CreatedAt,
			&i.Settings,
			&i.HoursSaved,
			&i.ActiveRuns,
			&i.PendingApprovals,
			&i.TotalCostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForClerkUser = `-- name: ListWorkspacesForClerkUser :many

SELECT o.id, o.clerk_org_id, o.name, o.slug, o.organization_type, o.parent_practice_id, u.role
FROM organizations o
JOIN users u ON u.org_id = o.id AND u.clerk_user_id = $1 AND u.is_active = true
WHERE o.is_active = true
ORDER BY (o.organization_type = 'client_workspace'), o.name
`

type ListWorkspacesForClerkUserRow struct {
	ID               pgtype.UUID `json:"id"`
	ClerkOrgID       string      `json:"clerk_org_id"`
	Name             string      `json:"name"`
	Slug             string      `json:"slug"`
	OrganizationType string      `json:"organization_type"`
	ParentPracticeID pgtype.UUID `json:"parent_practice_id"`
	Role             string      `json:"role"`
}

// Workflow 21 (Practice & Client Workspace Model). Every query here runs on
// app_system (BYPASSRLS), because a portfolio view is inherently
// cross-tenant — RLS can only ever scope to one org at a time. What stands
// in for RLS is the users join every read carries: a workspace is only ever
// visible to a caller holding an active users row in that exact workspace
// (clerk_user_id = the verified JWT subject). Don't add a query to this file
// without that join.
// Backs the workspace switcher: every active org the person belongs to.
func (q *Queries) ListWorkspacesForClerkUser(ctx context.Context, clerkUserID string) ([]ListWorkspacesForClerkUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForClerkUser, clerkUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspacesForClerkUserRow
	for rows.Next() {
		var i ListWorkspacesForClerkUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ClerkOrgID,
			&i.Name,
			&i.Slug,
			&i.OrganizationType,
			&i.ParentPracticeID,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrganizationAsPractice = `-- name: MarkOrganizationAsPractice :exec
UPDATE organizations SET organization_type = 'practice'
WHERE id = $1 AND organization_type = 'standard'
`

// A standard org becomes a practice the first time it creates a client workspace.
func (q *Queries) MarkOrganizationAsPractice(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOrganizationAsPractice, id)
	return err
}

const restoreClientWorkspace = `-- name: RestoreClientWorkspace :execrows
UPDATE organizations SET is_active = true, deactivated_at = NULL
WHERE id = $1 AND parent_practice_id = $2 AND is_active = false
  AND deactivated_at > now() - interval '30 days'
`

type RestoreClientWorkspaceParams struct {
	ID               pgtype.UUID `json:"id"`
	ParentPracticeID pgtype.UUID `json:"parent_practice_id"`
}

func (q *Queries) RestoreClientWorkspace(ctx context.Context, arg RestoreClientWorkspaceParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreClientWorkspace, arg.ID, arg.ParentPracticeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertClientWorkspace = `-- name: UpsertClientWorkspace :one
INSERT INTO organizations (clerk_org_id, name, slug, organization_type, parent_practice_id, settings, is_active)
VALUES ($1, $2, $3, 'client_workspace', $4, $5, true)
ON CONFLICT (clerk_org_id) DO UPDATE SET
    organization_type = 'client_workspace',
    parent_practice_id = EXCLUDED.parent_practice_id,
    settings = EXCLUDED.settings
RETURNING id
`

type UpsertClientWorkspaceParams struct {
	ClerkOrgID       string      `json:"clerk_org_id"`
	Name             string      `json:"name"`
	Slug             string      `json:"slug"`
	ParentPracticeID pgtype.UUID `json:"parent_practice_id"`
	Settings         []byte      `json:"settings"`
}

// ON CONFLICT covers Clerk's organization.created webhook racing ahead of
// this insert: the webhook creates a plain standard row, and this turns it
// into the client workspace it actually is.
func (q *Queries) UpsertClientWorkspace(ctx context.Context, arg UpsertClientWorkspaceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertClientWorkspace,
		arg.ClerkOrgID,
		arg.Name,
		arg.Slug,
		arg.ParentPracticeID,
		arg.Settings,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
