// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Only clears active_api_key_id/llm_provider when provider is the org's
	// *currently active* provider — with multiple providers now storable per
	// org, deactivating a non-active provider's key must not clobber a
	// different, still-active provider's pointer.
	ClearOrganizationActiveApiKeyForProvider(ctx context.Context, arg ClearOrganizationActiveApiKeyForProviderParams) error
	CountActiveAgents(ctx context.Context, orgID pgtype.UUID) (int64, error)
	CountCostLedger(ctx context.Context, orgID pgtype.UUID) (int64, error)
	// Soft delete — is_active=false, row stays for run history (Workflow 9+).
	// :execrows (not :exec) so the handler can distinguish "deactivated" from
	// "no such agent in this org" (0 rows) and return a real 404.
	DeactivateAgent(ctx context.Context, arg DeactivateAgentParams) (int64, error)
	// One-way, unlike workflows' pause/resume DeactivateWorkflow — a team has
	// no equivalent "reactivate" endpoint (see GetAgentTeam's own note).
	DeactivateAgentTeam(ctx context.Context, arg DeactivateAgentTeamParams) (int64, error)
	DeactivateKeyByProvider(ctx context.Context, arg DeactivateKeyByProviderParams) (int64, error)
	// Only ever called after the real Clerk-side removal already succeeded —
	// see Handler.Remove's doc comment for why the ordering matters.
	DeactivateMember(ctx context.Context, arg DeactivateMemberParams) error
	// Semantically identical to PATCH {is_active: false} (pause) — kept as its
	// own endpoint only for symmetry with every other resource's DELETE verb
	// in this codebase, not because it does anything a pause doesn't already
	// do. See CLAUDE.md's workflow 8 section for why workflows don't have a
	// separate "really gone" state the way documents/agents effectively do.
	DeactivateWorkflow(ctx context.Context, arg DeactivateWorkflowParams) (int64, error)
	DeleteDocumentChunks(ctx context.Context, docID pgtype.UUID) error
	DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) error
	// Backs the no-login unsubscribe link — deliberately only ever turns the
	// digest off, never on, so a leaked/replayed token can't be used to
	// re-enable something a founder actively disabled some other way.
	DisableDigestForOrg(ctx context.Context, id pgtype.UUID) error
	// Fills in the completion-summary fields checkpoint() itself doesn't own
	// (status stays checkpoint()'s alone) — only called once a run reaches a
	// genuinely terminal status, never for awaiting_approval.
	FinalizeRun(ctx context.Context, arg FinalizeRunParams) error
	// Only ever called once, right after FinalizeRun, guarded on the run
	// having just reached status='completed' -- see finalizeIfTerminal.
	// estimated_manual_minutes defaults to 15 (a conservative baseline) when
	// the workflow never had one set. parent_run_id IS NOT NULL (workflow 18's
	// specialist sub-runs) instead sets an explicit NULL, not a computed
	// estimate -- only the orchestrator's own run represents the end-to-end
	// task a founder would otherwise have done by hand; accruing hours_saved
	// per specialist too would double- (or N-times-) count the same task.
	// accrueHoursSaved's existing "hoursSaved == nil -> nothing to accrue"
	// check already handles that NULL correctly, so no Go-side change is
	// needed for this guard.
	FinalizeRunHoursSaved(ctx context.Context, arg FinalizeRunHoursSavedParams) (*float64, error)
	// Queries backing BYOK API key management (workflow 3). Run through
	// app_user via tenant.WithTx — this is genuinely tenant-scoped data, not a
	// system-context lookup like clerk_sync.sql or auth.sql. Provider is a
	// caller-supplied parameter (llm.ProviderID), not baked into the SQL —
	// generalized 2026-08-21 from an Anthropic-only literal to support all 5
	// catalog providers (see internal/core/llm/catalog.go).
	GetActiveKeyByOrgIDAndProvider(ctx context.Context, arg GetActiveKeyByOrgIDAndProviderParams) (GetActiveKeyByOrgIDAndProviderRow, error)
	GetActiveOrganizationByID(ctx context.Context, id pgtype.UUID) (GetActiveOrganizationByIDRow, error)
	// Queries backing request authentication (internal/api/middleware/auth.go).
	// Run through app_system (BYPASSRLS): resolving "who is this JWT for, and
	// which org do they belong to" is inherently a lookup that happens before
	// any tenant context exists to scope an RLS-restricted query by — the same
	// chicken-and-egg reasoning as the Clerk webhook's org creation.
	GetActiveUserByClerkUserID(ctx context.Context, clerkUserID string) (GetActiveUserByClerkUserIDRow, error)
	GetAgent(ctx context.Context, arg GetAgentParams) (GetAgentRow, error)
	// Per-agent cost share (last 30 days) for GET /billing/usage's bar chart.
	// agent_id is nullable on cost_ledger (a run's tool-call/llm cost rows
	// always set it, but nothing else does yet) — LEFT JOIN keeps those rows
	// visible under a synthetic "Unattributed" bucket rather than silently
	// dropping real spend from the total.
	GetAgentCostShare(ctx context.Context, arg GetAgentCostShareParams) ([]GetAgentCostShareRow, error)
	// The fields internal/core/a2a/manifest.go needs to build an A2A agent
	// card — name/description/model for display, policy_scope's allowed_tools
	// for the card's declared "skills" (an external caller should be able to
	// see what a specialist can actually do before dispatching a task to it).
	GetAgentForA2AManifest(ctx context.Context, arg GetAgentForA2AManifestParams) (GetAgentForA2AManifestRow, error)
	// GET /analytics/agent-performance. success_count/failure_count are
	// separate columns (not one status column) so the handler never has to
	// special-case pending/running/awaiting_approval rows to compute a rate.
	GetAgentPerformance(ctx context.Context, orgID pgtype.UUID) ([]GetAgentPerformanceRow, error)
	// is_active = true, unlike GetWorkflow's deliberate "show it either way"
	// choice — a deactivated team has no equivalent of a workflow's
	// pause/resume toggle (DeactivateAgentTeam is a one-way soft delete, see
	// its own doc comment), so a founder should never be able to Get or Run
	// one again after deleting it.
	GetAgentTeam(ctx context.Context, arg GetAgentTeamParams) (GetAgentTeamRow, error)
	// The real authorization check behind POST .../a2a/agents/{agent_id}/tasks/send:
	// an orchestrator's dispatching run resolves its own team via
	// GetRunTeamID, then this confirms the requested target agent is actually
	// a member of *that* team (pgx.ErrNoRows if not, treated as 403) — never
	// trusts a client-supplied role or team id.
	GetAgentTeamMemberRole(ctx context.Context, arg GetAgentTeamMemberRoleParams) (string, error)
	GetAgentTemplate(ctx context.Context, id pgtype.UUID) (GetAgentTemplateRow, error)
	GetApproval(ctx context.Context, arg GetApprovalParams) (GetApprovalRow, error)
	// GetApprovalSystemScoped runs on app_system (BYPASSRLS) — the
	// action-token approve/reject path (internal/api/approvals/handler.go)
	// has no tenant context yet at this point (an unauthenticated caller
	// can't SET LOCAL app.current_org_id for an org it hasn't proven it
	// belongs to), the same chicken-and-egg reasoning as
	// internal/api/middleware/auth.go's RequireAuth resolving identity before
	// any org context exists. Scoped by primary key only; every write that
	// follows still goes through the normal org-scoped path once org_id is
	// known from this row.
	GetApprovalSystemScoped(ctx context.Context, id pgtype.UUID) (GetApprovalSystemScopedRow, error)
	GetConnectionByOrgService(ctx context.Context, arg GetConnectionByOrgServiceParams) (GetConnectionByOrgServiceRow, error)
	// Workflow 14 (token usage & analytics). All read-only, all against
	// app_user/tenant.WithTx like every other tenant-scoped query in this
	// codebase — RLS already scopes these by org, the explicit org_id
	// parameter matches this codebase's existing belt-and-suspenders
	// convention (see e.g. workflows.sql's ListWorkflows).
	// Monthly aggregate for GET /settings/api-key/usage and the headline
	// figures on GET /billing/usage.
	GetCostUsageSince(ctx context.Context, arg GetCostUsageSinceParams) (GetCostUsageSinceRow, error)
	// Daily breakdown (last 30 days) for GET /billing/usage's trend chart —
	// one row per day that actually had activity, not a zero-filled series
	// for every calendar day (the handler fills gaps itself, since a query
	// can't easily manufacture rows for days with zero cost_ledger activity).
	GetDailyCostUsage(ctx context.Context, arg GetDailyCostUsageParams) ([]GetDailyCostUsageRow, error)
	GetDigestCostUSD(ctx context.Context, arg GetDigestCostUSDParams) (float64, error)
	// Current state, not time-boxed to yesterday -- a founder needs to know
	// what's waiting on them right now, not just what queued up yesterday.
	GetDigestPendingApprovalsCount(ctx context.Context, orgID pgtype.UUID) (int64, error)
	// "Yesterday" is the previous calendar day in the org's own
	// digest_timezone, not UTC -- matches what ListOrgsDueForDigest just
	// fired on. parent_run_id IS NULL excludes workflow 18 specialist
	// sub-runs from the count, same reasoning as FinalizeRunHoursSaved: only
	// an orchestrator's own run represents one end-to-end task a founder
	// would otherwise have done by hand.
	GetDigestRunStats(ctx context.Context, arg GetDigestRunStatsParams) (GetDigestRunStatsRow, error)
	GetDigestSettings(ctx context.Context, id pgtype.UUID) (GetDigestSettingsRow, error)
	// COALESCE(wr.agent_id, w.agent_id): same "derive from workflow unless a
	// team sub-run overrides it directly" convention as GetRunAgentID.
	// Returns pgx.ErrNoRows when nothing ran yesterday -- callers treat that
	// as "no top agent", not an error.
	GetDigestTopAgent(ctx context.Context, arg GetDigestTopAgentParams) (GetDigestTopAgentRow, error)
	GetDocument(ctx context.Context, arg GetDocumentParams) (GetDocumentRow, error)
	// Batch-hydrates a page of search results' filename/category — Pinecone's
	// own vector metadata only carries doc_id/chunk_index/text (see
	// processor.go), not display fields.
	GetDocumentsByIDs(ctx context.Context, arg GetDocumentsByIDsParams) ([]GetDocumentsByIDsRow, error)
	GetHoursSavedSince(ctx context.Context, arg GetHoursSavedSinceParams) (float64, error)
	GetKeyStatusByProvider(ctx context.Context, arg GetKeyStatusByProviderParams) (GetKeyStatusByProviderRow, error)
	GetOrgApprovalsSlackChannel(ctx context.Context, id pgtype.UUID) (*string, error)
	// Confirms the target member belongs to the caller's own org (cross-org
	// access is a 404 here, same "wrong org is indistinguishable from doesn't
	// exist" convention as every other tenant-scoped lookup in this codebase)
	// and returns clerk_user_id, needed for the Clerk-side sync call.
	GetOrgMemberForUpdate(ctx context.Context, arg GetOrgMemberForUpdateParams) (GetOrgMemberForUpdateRow, error)
	// Backs "send test email" -- BuildPayload needs both, and neither
	// GetDigestSettings nor auth.sql's GetActiveOrganizationByID returns the
	// pair together.
	GetOrgNameAndTimezone(ctx context.Context, id pgtype.UUID) (GetOrgNameAndTimezoneRow, error)
	// graph.Launcher's run lifecycle (POST /workflows/{id}/run's async goroutine
	// — see internal/core/graph/launch.go) and the read-only HTTP endpoints
	// (GET /runs, GET /runs/{id}).
	// Preflight (kill switch) + provider resolution for Launcher.Launch.
	GetOrgRunSettings(ctx context.Context, id pgtype.UUID) (GetOrgRunSettingsRow, error)
	GetOrgTotalHoursSaved(ctx context.Context, id pgtype.UUID) (float64, error)
	GetOrganizationIDByClerkOrgID(ctx context.Context, clerkOrgID string) (pgtype.UUID, error)
	GetOrganizationMaxAgents(ctx context.Context, id pgtype.UUID) (*int32, error)
	// GET /analytics/rag-quality. Sourced from audit_logs' rag.search rows —
	// the only place avg_rerank_score/from_cache/result_count are recorded at
	// all (see internal/api/documents/handler.go's auditSearch); a search
	// with 0 results (the ACL-empty short-circuit) contributes a 0 to
	// avg_rerank_score/avg_chunks_retrieved, which is the correct average,
	// not a value worth excluding.
	GetRagQualityStats(ctx context.Context, arg GetRagQualityStatsParams) (GetRagQualityStatsRow, error)
	// Resolves a run's agent_id via its workflow — Launcher.Resume needs this
	// before it can rebuild the RunDeps/Nodes a suspended run's checkpoint
	// alone doesn't carry (agent_id isn't part of RunState's own JSON).
	// COALESCE(wr.agent_id, ...) is workflow 18's addition: a team's specialist
	// sub-runs all share the team's one `workflows` row (whose agent_id is the
	// orchestrator's, not theirs), so their real agent is stored directly on
	// workflow_runs.agent_id instead — NULL there for every ordinary run
	// (and the orchestrator's own run), which falls through to the original
	// workflow-derived lookup unchanged.
	GetRunAgentID(ctx context.Context, arg GetRunAgentIDParams) (pgtype.UUID, error)
	GetRunCheckpoint(ctx context.Context, arg GetRunCheckpointParams) (GetRunCheckpointRow, error)
	GetRunCostBreakdown(ctx context.Context, arg GetRunCostBreakdownParams) ([]GetRunCostBreakdownRow, error)
	// w.team_id (workflow 18) lets the frontend tell a team's orchestrator run
	// apart from an ordinary single-agent run when someone lands on the plain
	// GET /runs/{id} page directly (an old bookmark, a shared link, or the
	// founder just browsing /runs — that list has no other way to distinguish
	// them either, see ListRunsForOrg below) — the run page redirects to the
	// correct /agents/teams/{team_id}/runs/{id} view instead of rendering a
	// single-agent pipeline that doesn't know what a "delegate" node is.
	GetRunDetail(ctx context.Context, arg GetRunDetailParams) (GetRunDetailRow, error)
	// Read back the definitive status Engine's own checkpoint() already
	// wrote (completed/failed/cancelled/awaiting_approval) — Launcher can't
	// infer this from Engine.Run's returned error alone, since a suspended
	// run also returns a nil error.
	GetRunStatus(ctx context.Context, arg GetRunStatusParams) (string, error)
	// Resolves a run's team (and the one workflow row every run in that team
	// shares — see InsertTeamWorkflow) via its own workflow_id — the a2a
	// tasks/send handler uses this (via the request's sessionId, the
	// dispatching orchestrator's own run) to find which team the target agent
	// must belong to, rather than trusting a client-supplied team id, and
	// which workflow_id to insert the specialist's own sub-run row against.
	GetRunTeamAndWorkflow(ctx context.Context, arg GetRunTeamAndWorkflowParams) (GetRunTeamAndWorkflowRow, error)
	GetTeamWorkflow(ctx context.Context, arg GetTeamWorkflowParams) (pgtype.UUID, error)
	// GetUserApprovalPermissions backs both the authenticated and the
	// action-token approve/reject paths (internal/api/approvals/handler.go) —
	// neither authctx.User nor a Clerk JWT carries can_approve_workflows, so
	// this is looked up fresh at decision time rather than cached on the
	// request context.
	GetUserApprovalPermissions(ctx context.Context, id pgtype.UUID) (GetUserApprovalPermissionsRow, error)
	GetUserEmailByID(ctx context.Context, id pgtype.UUID) (string, error)
	GetWorkflow(ctx context.Context, arg GetWorkflowParams) (GetWorkflowRow, error)
	GetWorkflowRun(ctx context.Context, arg GetWorkflowRunParams) (GetWorkflowRunRow, error)
	// Only called after purgeDocumentJob has successfully removed the
	// Pinecone vectors and the S3 object — see internal/core/documents/purge.go.
	HardDeleteDocument(ctx context.Context, arg HardDeleteDocumentParams) error
	IncrementOrgTotalHoursSaved(ctx context.Context, arg IncrementOrgTotalHoursSavedParams) error
	// ON CONFLICT ... DO NOTHING against the partial unique index added in
	// 000006_agents_unique_org_name_active: a real duplicate name returns 0
	// rows (pgx.ErrNoRows on the :one Scan), which the handler translates to a
	// 400 DUPLICATE_AGENT_NAME rather than a generic 500.
	InsertAgent(ctx context.Context, arg InsertAgentParams) (InsertAgentRow, error)
	// Queries backing workflow 18 (Multi-Agent Team Run / A2A). agent_teams
	// and agent_team_members have existed, RLS-covered, since 000001/000002 —
	// these are the first queries ever written against them. All tenant-scoped
	// through app_user via tenant.WithTx, same as every other feature area in
	// this file set — team membership and A2A dispatch never cross an org
	// boundary.
	InsertAgentTeam(ctx context.Context, arg InsertAgentTeamParams) (InsertAgentTeamRow, error)
	InsertAgentTeamMember(ctx context.Context, arg InsertAgentTeamMemberParams) (InsertAgentTeamMemberRow, error)
	// Workflow 10: approvals/approval_decisions writes (internal/core/graph's
	// writeApprovalGate, internal/api/approvals' handler), notification lookups
	// (internal/core/notify), and the 24h expiry sweep
	// (internal/core/workflows/approvalexpiry.go). InsertApproval/GetApproval/
	// ListApprovalsForOrg/UpdateApprovalStatus/InsertApprovalDecision run
	// through tenant.WithTx (app_user) except ListExpiredPendingApprovals,
	// which is inherently cross-org and runs on app_system, same reasoning as
	// every other background sweep in this codebase.
	InsertApproval(ctx context.Context, arg InsertApprovalParams) (pgtype.UUID, error)
	InsertApprovalDecision(ctx context.Context, arg InsertApprovalDecisionParams) error
	// Written from internal/core/graph/observability.go — every tool call
	// and every LLM call the executor makes writes one row to each of these,
	// closing the "nothing existing to reuse" gap flagged in the Workflow 9
	// harness planning notes. Real per-token dollar pricing is workflow 11's
	// job (see WORKFLOW_PLAN_GO.md) — estimated_cost_usd is written as 0 for
	// now; token counts themselves are real and useful on their own.
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertCostLedgerEntry(ctx context.Context, arg InsertCostLedgerEntryParams) error
	// Queries backing workflow 6 (document upload / RAG). Tenant-scoped reads
	// and writes run through app_user via tenant.WithTx, same convention as
	// every other feature area in this file set. The recovery-sweep query
	// (ListStuckDocuments) is the one deliberate exception — it scans across
	// every org's documents, so it runs on app_system, matching
	// internal/core/integrations/refresh.go's RunRefreshJob precedent for
	// the same "this is inherently cross-tenant" reasoning.
	// id is application-generated (not the column's gen_random_uuid()
	// default) so the handler knows the S3 key (documents/{org_id}/{doc_id}/{filename})
	// before uploading, rather than uploading first and updating s3_path
	// after — one INSERT instead of an insert-then-update dance.
	InsertDocument(ctx context.Context, arg InsertDocumentParams) error
	InsertDocumentChunk(ctx context.Context, arg InsertDocumentChunkParams) error
	// Workflow 18's own auto-created companion row, one per agent_teams row —
	// see the note on ListWorkflows above. graph_definition mirrors
	// InsertWorkflow's own fixed marker; trigger_type is always 'manual' since
	// nothing schedules a team run yet.
	InsertTeamWorkflow(ctx context.Context, arg InsertTeamWorkflowParams) (pgtype.UUID, error)
	// Workflow 18's variant of InsertWorkflowRun — used for both the
	// orchestrator's own run (id server-generated, parent_run_id NULL) and
	// each specialist's delegated sub-run (id explicit — see below),
	// always with an explicit agent_id rather than InsertWorkflowRun's
	// workflow-derived one. See GetRunAgentID's and
	// workflow_runs.parent_run_id's doc comments above. id is
	// sqlc.narg(id): NULL lets Postgres's own gen_random_uuid() default fill
	// it (the orchestrator's own run); a specialist's sub-run instead reuses
	// the exact id its delegate node already minted client-side (see
	// graph.RunDeps.A2AClient.Dispatch's doc comment) before dispatch, so the
	// id EventBus.LinkChild registered for matches the id the specialist's
	// own engine run actually publishes events under.
	InsertTeamWorkflowRun(ctx context.Context, arg InsertTeamWorkflowRunParams) (InsertTeamWorkflowRunRow, error)
	// graph_definition is fixed, not user-configurable — every workflow runs
	// the same planner -> rag_retriever -> executor -> validator -> reporter
	// pipeline (Workflow 9's node list); nothing in this workflow's spec lets
	// a founder customize the graph shape itself, only the trigger/schedule
	// and the agent + task input that pipeline runs against.
	InsertWorkflow(ctx context.Context, arg InsertWorkflowParams) (InsertWorkflowRow, error)
	// "Run Now" and the scheduler both stop here — INSERT a pending run row,
	// nothing consumes it yet. See CLAUDE.md's workflow 8 section: turning
	// 'pending' rows into actual execution is Workflow 9's job
	// (internal/core/graph, not built).
	InsertWorkflowRun(ctx context.Context, arg InsertWorkflowRunParams) (InsertWorkflowRunRow, error)
	// Workflow 11 (run trace + cost). writeWorkflowStep (internal/core/graph/
	// observability.go) is the one place InsertWorkflowStep is called from,
	// fired at each of the 5 node functions plus once per LLM turn and once
	// per tool call inside executorNode -- see BuildNodes' doc comment.
	InsertWorkflowStep(ctx context.Context, arg InsertWorkflowStepParams) error
	// Gates internal/core/a2a's manifest/tasks-send endpoints: only an agent
	// that is (still) a member of at least one active team is A2A-addressable.
	// Checked live against agent_team_members/agent_teams, not a cached flag —
	// same "don't trust a second source of truth" reasoning as workflow 9's
	// policy_scope decision (see CLAUDE.md's Agent Execution Engine section) —
	// a member removed from every team loses A2A reachability immediately, not
	// whenever some denormalized column next happens to get refreshed.
	IsAgentOnActiveTeam(ctx context.Context, arg IsAgentOnActiveTeamParams) (bool, error)
	// Joined against agents for display (name, description, model) — the
	// specialist card the team page and the multi-agent pipeline UI both need,
	// without a second round trip per member.
	ListAgentTeamMembers(ctx context.Context, teamID pgtype.UUID) ([]ListAgentTeamMembersRow, error)
	// member_count is a correlated subquery, same reasoning as ListAgents'
	// workflow_count — a team with 0 members (mid-setup, or every member
	// since removed) must still appear exactly once.
	ListAgentTeamsForOrg(ctx context.Context, orgID pgtype.UUID) ([]ListAgentTeamsForOrgRow, error)
	// Queries backing workflow 19 (Agent Templates Marketplace). Deliberately
	// run through app_user like everything else in this file set — not
	// app_system — even though agent_templates has no org_id/RLS of its own:
	// a request handler already runs inside tenant.WithTx for its other work
	// (the install path also touches agents, which IS RLS-scoped), and there
	// is no cross-tenant write here that would need app_system's bypass.
	ListAgentTemplates(ctx context.Context, category *string) ([]ListAgentTemplatesRow, error)
	// Queries backing workflow 7 (agent configuration CRUD). All tenant-scoped,
	// run through app_user via tenant.WithTx like every other feature area in
	// this file set — nothing here is cross-tenant, unlike the recovery-sweep
	// style queries elsewhere.
	// workflow_count (added for workflow 8's "deleting an agent that has
	// workflows shows a warning" acceptance criterion) is a correlated
	// subquery, not a JOIN + GROUP BY — an agent with 0 workflows must still
	// appear exactly once, and a JOIN would either drop it (INNER) or need the
	// GROUP BY/aggregate dance anyway for no real benefit at this scale.
	ListAgents(ctx context.Context, orgID pgtype.UUID) ([]ListAgentsRow, error)
	ListApprovalsForOrg(ctx context.Context, arg ListApprovalsForOrgParams) ([]ListApprovalsForOrgRow, error)
	ListApproverEmailsForOrg(ctx context.Context, orgID pgtype.UUID) ([]ListApproverEmailsForOrgRow, error)
	// Workflow 17 (view audit logs). audit_logs itself has existed since
	// migration 000001 and has been written to since workflows 9/10/12 - this
	// is the first query that ever reads it back.
	// Cursor-based (created_at, id) pagination, newest first - a plain
	// LIMIT/OFFSET would skip/repeat rows if new entries land between page
	// fetches (a real, ongoing concern here: agents write audit_logs
	// continuously). Every filter is optional (sqlc.narg + "IS NULL OR ..."),
	// matching this codebase's existing pattern (see documents.sql's
	// ListSearchableDocumentIDs).
	//
	// actor_name resolves against whichever of users/agents actually owns
	// actor_id for that row's actor_type, falling back to the literal
	// 'System' when neither join matches (no current writer sets
	// actor_type='system', but it's a valid value per the plan). The fallback
	// is baked into SQL, not left to the Go handler: sqlc infers COALESCE's
	// result nullability from its *last* argument's column, which would make
	// actor_name a non-nullable Go string even though it's genuinely
	// NULL-able here - the first real 'system' row would crash pgx's scan.
	ListAuditLogsPage(ctx context.Context, arg ListAuditLogsPageParams) ([]ListAuditLogsPageRow, error)
	// The specialist sub-runs a team's orchestrator run dispatched — how
	// GET /teams/{id}/runs/{run_id} builds its aggregated, per-specialist
	// trace. delegated_role/agent_id are always set on these rows (see
	// InsertTeamWorkflowRun), so no join back to agent_team_members is needed
	// (and wouldn't survive a member later being removed from the team).
	ListChildRuns(ctx context.Context, arg ListChildRunsParams) ([]ListChildRunsRow, error)
	ListConnectionsByOrg(ctx context.Context, orgID pgtype.UUID) ([]ListConnectionsByOrgRow, error)
	// Paginated GET /billing/ledger.
	ListCostLedgerPage(ctx context.Context, arg ListCostLedgerPageParams) ([]ListCostLedgerPageRow, error)
	// Owners/admins only, not every member -- same admin-role check
	// (role IN ('owner','admin')) already used by org.handler.go/clerk
	// webhook, reused here rather than invented fresh.
	ListDigestRecipients(ctx context.Context, orgID pgtype.UUID) ([]string, error)
	ListDocumentChunkPineconeIDs(ctx context.Context, docID pgtype.UUID) ([]string, error)
	// Excludes 'deleting': once DELETE .../{id} has been called, the
	// document shouldn't reappear in a normal list view while
	// purgeDocumentJob finishes removing it (the row itself is only ever
	// hard-deleted after that succeeds — see HardDeleteDocument).
	ListDocuments(ctx context.Context, orgID pgtype.UUID) ([]ListDocumentsRow, error)
	// Background scheduler (internal/core/workflows/scheduler.go) — app_system,
	// never tenant.WithTx; see the file-level comment above.
	ListDueScheduledWorkflows(ctx context.Context) ([]ListDueScheduledWorkflowsRow, error)
	// ListExpiredPendingApprovals runs on app_system (BYPASSRLS) — sweeping
	// expirations across every org is inherently cross-tenant, same reasoning
	// as internal/core/integrations/refresh.go's RunRefreshJob.
	ListExpiredPendingApprovals(ctx context.Context) ([]ListExpiredPendingApprovalsRow, error)
	// Used only by the background refresh job (app_system pool). Scoped to
	// oauth_status = 'connected' so a already-expired or revoked connection
	// isn't retried every 30 minutes forever.
	ListExpiringConnectionsSystem(ctx context.Context, tokenExpiresAt pgtype.Timestamptz) ([]ListExpiringConnectionsSystemRow, error)
	// Every provider the org has ever submitted a key for (valid or not),
	// annotated with whether it's the org's *currently active* provider —
	// backs GET /api/v1/settings/api-key/providers, which merges this with
	// llm.Catalog so the frontend gets one request for "every supported
	// provider, plus this org's status for each." COALESCE forces a real
	// false (not SQL NULL) when llm_provider is unset, so the generated Go
	// field is a plain bool, not a nullable pointer.
	ListKeyStatuses(ctx context.Context, orgID pgtype.UUID) ([]ListKeyStatusesRow, error)
	// Workflow 13 (team members & roles). Postgres — kept in sync by the Clerk
	// webhook (clerk_sync.sql) — is this app's own source of truth for role
	// display; internal/api/org/handler.go doesn't call out to Clerk's API on
	// every list, only on a role change or removal (see that package's own
	// doc comment for why).
	ListOrgMembers(ctx context.Context, orgID pgtype.UUID) ([]ListOrgMembersRow, error)
	// Cross-tenant scan (system pool, BYPASSRLS) -- an org is due when its
	// local hour matches digest_send_hour, it hasn't already gotten today's
	// digest in its own timezone yet, and it's had some activity in the last
	// 7 days (skips ghost emails to churned/empty orgs, per spec).
	ListOrgsDueForDigest(ctx context.Context) ([]ListOrgsDueForDigestRow, error)
	ListPushSubscriptionsForOrg(ctx context.Context, orgID pgtype.UUID) ([]ListPushSubscriptionsForOrgRow, error)
	// parent_run_id IS NULL excludes a team's specialist sub-runs from the
	// flat run list — a founder browsing "my runs" sees the team run as one
	// row; its specialists only surface via GET /teams/{id}/runs/{run_id}'s
	// aggregated trace (workflow 18). w.team_id (also workflow 18) is what
	// lets that one row actually be *labeled* as a team run and link
	// correctly — before this, a team run looked identical to any other row
	// here, and clicking it opened the wrong page entirely (a real, reported
	// confusion, not a hypothetical).
	ListRunsForOrg(ctx context.Context, arg ListRunsForOrgParams) ([]ListRunsForOrgRow, error)
	// Workflow 12 (RAG search). ListSearchableDocumentIDs is the ACL + category
	// filter, resolved *before* any embedding/Pinecone call so a query that
	// can't match anything (e.g. a member with only owner_only docs uploaded)
	// skips the expensive calls entirely. include_owner_only is the
	// requesting user's own role check (role IN ('owner','admin')), computed
	// in Go, not SQL — see internal/api/documents/handler.go's Search.
	ListSearchableDocumentIDs(ctx context.Context, arg ListSearchableDocumentIDsParams) ([]pgtype.UUID, error)
	// Documents whose background job (processDocument or purgeDocumentJob)
	// may have been running in a process that restarted mid-job — the
	// goroutine-based tradeoff internal/core/documents.RecoverStuckJobs
	// exists to cover. olderThan guards against re-kicking a job that's
	// still genuinely in flight in *this* process, not actually stuck.
	ListStuckDocuments(ctx context.Context, updatedAt pgtype.Timestamptz) ([]ListStuckDocumentsRow, error)
	// One team's own run history — the "Recent runs" list workflow 18's team
	// detail page needs (there was no way to get back to a past run's page
	// before this; the only route in was the URL Launch's own response
	// handed back right after triggering it, gone the moment you navigated
	// away). team_id resolves through the team's one shared `workflows` row
	// (see InsertTeamWorkflow) rather than a direct column on workflow_runs —
	// consistent with how every other team-scoped run query in this file
	// reaches team_id.
	ListTeamRuns(ctx context.Context, arg ListTeamRunsParams) ([]ListTeamRunsRow, error)
	// Joins workflow_runs for org-scoping (workflow_steps itself has no
	// org_id column) -- same shape as GetRunAgentID's join above.
	ListWorkflowSteps(ctx context.Context, arg ListWorkflowStepsParams) ([]ListWorkflowStepsRow, error)
	// Deliberately NOT filtered by is_active, unlike ListAgents/ListDocuments
	// — pausing a workflow (PATCH is_active=false) must keep it visible so the
	// founder can toggle it back on; is_active in the response drives the
	// pause/resume toggle and "Paused" badge client-side. agent_name comes via
	// a plain JOIN, not a nullable LEFT JOIN: agent_id is NOT NULL and agents
	// are only ever soft-deleted (never actually removed), so the referenced
	// row always exists. team_id IS NULL excludes the one companion `workflows`
	// row workflow 18's POST /teams auto-creates per team (see teams.sql's
	// InsertTeamWorkflow) — that row exists only to satisfy workflow_runs.
	// workflow_id's NOT NULL constraint for team runs, it's not something a
	// founder configured here and shouldn't show up as an orphan single-agent
	// workflow.
	ListWorkflows(ctx context.Context, orgID pgtype.UUID) ([]ListWorkflowsRow, error)
	MarkConnectionExpired(ctx context.Context, arg MarkConnectionExpiredParams) (int64, error)
	MarkConnectionExpiredByIDSystem(ctx context.Context, id pgtype.UUID) (int64, error)
	MarkDigestSent(ctx context.Context, id pgtype.UUID) error
	MarkDocumentFailed(ctx context.Context, arg MarkDocumentFailedParams) error
	MarkDocumentIndexed(ctx context.Context, arg MarkDocumentIndexedParams) error
	// Used only when dependency resolution itself fails before Engine.Run
	// ever starts (a bad policy_scope, a registry error, ...) — there's no
	// checkpoint yet for a normal Engine-driven "failed" transition to have
	// written, so this writes the terminal status directly.
	MarkRunFailedPreflight(ctx context.Context, arg MarkRunFailedPreflightParams) error
	MarkRunStarted(ctx context.Context, arg MarkRunStartedParams) error
	RevokeConnection(ctx context.Context, arg RevokeConnectionParams) (int64, error)
	SetOrganizationActiveApiKey(ctx context.Context, arg SetOrganizationActiveApiKeyParams) error
	SoftDeleteDocument(ctx context.Context, arg SoftDeleteDocumentParams) error
	SoftDeleteOrganizationByClerkOrgID(ctx context.Context, clerkOrgID string) (int64, error)
	SoftDeleteUserByClerkUserID(ctx context.Context, clerkUserID string) (int64, error)
	// Same shape as InsertWorkflowRun (triggered_by is NULL — the system, not
	// a user, triggered this one), used because the scheduler has no
	// per-request user/org session to run InsertWorkflowRun's tenant.WithTx
	// variant under.
	SystemInsertWorkflowRun(ctx context.Context, arg SystemInsertWorkflowRunParams) error
	// Best-effort, fire-and-forget from RequireAuth — the WHERE guard keeps
	// this to one write per user per 5 minutes, not one per request.
	TouchLastLogin(ctx context.Context, id pgtype.UUID) error
	// Partial update via COALESCE against sqlc.narg — every field is optional
	// on the PATCH wire contract; only the ones actually present in the
	// request are non-nil here. A rename that collides with another active
	// agent's name still hits the 000006 partial unique index (COALESCE can't
	// route around a real constraint), surfacing as a Postgres 23505 the
	// handler translates the same way InsertAgent's ON CONFLICT branch does.
	UpdateAgent(ctx context.Context, arg UpdateAgentParams) (UpdateAgentRow, error)
	UpdateApprovalStatus(ctx context.Context, arg UpdateApprovalStatusParams) (int64, error)
	UpdateConnectionTokens(ctx context.Context, arg UpdateConnectionTokensParams) (int64, error)
	// Used only by the background refresh job (app_system pool) — targets a
	// specific connection by id, already scoped to the right org by virtue of
	// having come from ListExpiringConnectionsSystem's own row.
	UpdateConnectionTokensByIDSystem(ctx context.Context, arg UpdateConnectionTokensByIDSystemParams) (int64, error)
	UpdateDigestSettings(ctx context.Context, arg UpdateDigestSettingsParams) error
	UpdateDocumentProcessing(ctx context.Context, arg UpdateDocumentProcessingParams) error
	// Permission flags are recomputed from the new role (see
	// internal/api/org/handler.go's defaultPermissionsForRole), not passed
	// through as independent client input — the schema's can_manage_* columns
	// exist for other code (can_approve_workflows is already read directly by
	// internal/api/approvals) to check without needing to know this app's role
	// hierarchy, but they're derived, not separately settable.
	UpdateMemberRoleAndPermissions(ctx context.Context, arg UpdateMemberRoleAndPermissionsParams) error
	UpdateOrgApprovalsSlackChannel(ctx context.Context, arg UpdateOrgApprovalsSlackChannelParams) error
	// internal/core/graph's checkpoint read/write — the engine.Run/Resume/checkpoint
	// calls added workflow9_engine_guardrails.up.sql for. Always run through
	// tenant.WithTx (a fresh transaction per call, org-scoped) — never held open across
	// a node's tool-call loop or an approval-gate pause. See WORKFLOW_PLAN_GO.md's
	// Workflow 9 harness planning notes for the full reasoning.
	UpdateRunCheckpoint(ctx context.Context, arg UpdateRunCheckpointParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (int64, error)
	// Partial update via COALESCE, same convention as UpdateAgent — but
	// trigger_type/cron_expression/next_run_at are 3 fields the *handler*
	// treats as one coupled unit (see internal/api/workflows/handler.go's
	// Update): it always passes explicit values for all 3 together, computed
	// from the effective (existing-unless-overridden) trigger config, rather
	// than relying on COALESCE to reconcile them independently — a bare
	// COALESCE per-field could otherwise land on a state like
	// trigger_type='scheduled' with a stale or absent cron_expression.
	// agent_id is intentionally not updatable here — reassigning a workflow to
	// a different agent isn't part of this workflow's spec.
	UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (UpdateWorkflowRow, error)
	UpdateWorkflowNextRunAt(ctx context.Context, arg UpdateWorkflowNextRunAtParams) error
	UpsertAPIKey(ctx context.Context, arg UpsertAPIKeyParams) (pgtype.UUID, error)
	// Queries backing third-party integration connections (workflow 4),
	// against the mcp_connections table. Per-org reads/writes (connect,
	// callback, api-key, status, delete) run through app_user via
	// tenant.WithTx, same as api_key_registry in api_keys.sql. The two
	// "System" queries below are the exception — the background token-refresh
	// job scans expiring connections across every org, which is inherently a
	// cross-tenant system-context operation (same reasoning as clerk_sync.sql),
	// so those run against app_system (BYPASSRLS) directly, never through
	// tenant.WithTx.
	UpsertConnection(ctx context.Context, arg UpsertConnectionParams) (pgtype.UUID, error)
	// Queries backing the Clerk webhook sync (POST /api/webhooks/clerk). Run
	// through the app_system (BYPASSRLS) pool, never app_user — see
	// internal/api/webhooks/clerk.go.
	UpsertOrganization(ctx context.Context, arg UpsertOrganizationParams) (pgtype.UUID, error)
	UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) error
	// can_approve_workflows/can_manage_api_keys/can_manage_integrations are
	// reset to the freshly computed role-derived default (EXCLUDED) only when
	// the existing row is currently inactive — a genuine new membership after
	// having been removed. An already-active member's flags are left
	// untouched on conflict, since those may since have been hand-adjusted via
	// workflow 13's PATCH .../role, which a routine Clerk membership re-sync
	// (role unchanged, just metadata) must never silently clobber.
	//
	// Real bug this fixes, found live 2026-09-07: without the is_active
	// branch, a former admin/owner who was removed and later re-invited as a
	// plain member kept their old admin-era flags forever — the ON CONFLICT
	// branch never touched these 3 columns at all, so ANY re-sync (including
	// a brand-new membership) silently carried forward whatever a completely
	// unrelated, already-terminated membership had left behind.
	UpsertUserForMembership(ctx context.Context, arg UpsertUserForMembershipParams) error
	// Queries backing workflow 8 (workflow config CRUD + scheduling). Most are
	// tenant-scoped through app_user via tenant.WithTx, like every other
	// feature area in this file set. The 3 queries under "background
	// scheduler" are the deliberate exception — the scheduler scans due
	// workflows across every org, which is inherently a cross-tenant
	// system-context operation, so those run on app_system directly, same
	// reasoning as internal/core/integrations/refresh.go's RunRefreshJob and
	// internal/core/documents/recover.go's RecoverStuckJobs.
	// Used at create time to confirm the agent_id a workflow is being pointed
	// at both belongs to this org and is still active — you shouldn't be able
	// to assign a workflow to a deactivated agent. Also returns name so the
	// Create response can embed agent_name without a second query.
	ValidateAgentForOrg(ctx context.Context, arg ValidateAgentForOrgParams) (ValidateAgentForOrgRow, error)
	// Same "must belong to this org and be active" guard InsertWorkflow's
	// ValidateAgentForOrg already applies to workflows — a team's orchestrator
	// and every specialist must pass it too.
	ValidateAgentForTeamMembership(ctx context.Context, arg ValidateAgentForTeamMembershipParams) (ValidateAgentForTeamMembershipRow, error)
}

var _ Querier = (*Queries)(nil)
