// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetOrganizationIDByClerkOrgID(ctx context.Context, clerkOrgID string) (pgtype.UUID, error)
	SoftDeleteOrganizationByClerkOrgID(ctx context.Context, clerkOrgID string) (int64, error)
	SoftDeleteUserByClerkUserID(ctx context.Context, clerkUserID string) (int64, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (int64, error)
	// Queries backing the Clerk webhook sync (POST /api/webhooks/clerk). Run
	// through the app_system (BYPASSRLS) pool, never app_user — see
	// internal/api/webhooks/clerk.go.
	UpsertOrganization(ctx context.Context, arg UpsertOrganizationParams) (pgtype.UUID, error)
	UpsertUserForMembership(ctx context.Context, arg UpsertUserForMembershipParams) error
}

var _ Querier = (*Queries)(nil)
