// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countClientReportsForOrg = `-- name: CountClientReportsForOrg :one
SELECT count(*) FROM client_reports
WHERE org_id = $1 AND is_revoked = false AND expires_at > now()
`

// Reports not yet revoked or expired; backs the per-workspace cap.
func (q *Queries) CountClientReportsForOrg(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countClientReportsForOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getClientReportByToken = `-- name: GetClientReportByToken :one
SELECT r.id, r.title, r.date_from, r.date_to, r.timezone, r.visible_sections, r.snapshot,
       r.expires_at, r.is_revoked, o.is_active AS org_active
FROM client_reports r
JOIN organizations o ON o.id = r.org_id
WHERE r.share_token = $1
`

type GetClientReportByTokenRow struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	DateFrom        pgtype.Date        `json:"date_from"`
	DateTo          pgtype.Date        `json:"date_to"`
	Timezone        string             `json:"timezone"`
	VisibleSections []byte             `json:"visible_sections"`
	Snapshot        []byte             `json:"snapshot"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	IsRevoked       bool               `json:"is_revoked"`
	OrgActive       *bool              `json:"org_active"`
}

// Public, unauthenticated lookup. The handler treats missing, revoked,
// expired, and deactivated-workspace identically.
func (q *Queries) GetClientReportByToken(ctx context.Context, shareToken string) (GetClientReportByTokenRow, error) {
	row := q.db.QueryRow(ctx, getClientReportByToken, shareToken)
	var i GetClientReportByTokenRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.DateFrom,
		&i.DateTo,
		&i.Timezone,
		&i.VisibleSections,
		&i.Snapshot,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.OrgActive,
	)
	return i, err
}

const getClientReportForUser = `-- name: GetClientReportForUser :one
SELECT r.id, r.org_id, o.name AS org_name, r.title, r.date_from, r.date_to, r.timezone,
       r.visible_sections, r.snapshot, r.share_token, r.expires_at, r.view_count,
       r.last_viewed_at, r.is_revoked, r.created_at
FROM client_reports r
JOIN organizations o ON o.id = r.org_id AND o.is_active = true
JOIN users u ON u.org_id = r.org_id AND u.clerk_user_id = $2
            AND u.is_active = true AND u.role IN ('owner', 'admin')
WHERE r.id = $1
`

type GetClientReportForUserParams struct {
	ID          pgtype.UUID `json:"id"`
	ClerkUserID string      `json:"clerk_user_id"`
}

type GetClientReportForUserRow struct {
	ID              pgtype.UUID        `json:"id"`
	OrgID           pgtype.UUID        `json:"org_id"`
	OrgName         string             `json:"org_name"`
	Title           string             `json:"title"`
	DateFrom        pgtype.Date        `json:"date_from"`
	DateTo          pgtype.Date        `json:"date_to"`
	Timezone        string             `json:"timezone"`
	VisibleSections []byte             `json:"visible_sections"`
	Snapshot        []byte             `json:"snapshot"`
	ShareToken      string             `json:"share_token"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	ViewCount       int32              `json:"view_count"`
	LastViewedAt    pgtype.Timestamptz `json:"last_viewed_at"`
	IsRevoked       bool               `json:"is_revoked"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetClientReportForUser(ctx context.Context, arg GetClientReportForUserParams) (GetClientReportForUserRow, error) {
	row := q.db.QueryRow(ctx, getClientReportForUser, arg.ID, arg.ClerkUserID)
	var i GetClientReportForUserRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OrgName,
		&i.Title,
		&i.DateFrom,
		&i.DateTo,
		&i.Timezone,
		&i.VisibleSections,
		&i.Snapshot,
		&i.ShareToken,
		&i.ExpiresAt,
		&i.ViewCount,
		&i.LastViewedAt,
		&i.IsRevoked,
		&i.CreatedAt,
	)
	return i, err
}

const getReportCostTotals = `-- name: GetReportCostTotals :one
SELECT
    COALESCE(SUM(estimated_cost_usd), 0)::double precision AS total_cost_usd,
    COALESCE(SUM(input_tokens), 0)::bigint AS input_tokens,
    COALESCE(SUM(output_tokens), 0)::bigint AS output_tokens,
    COALESCE(SUM(cached_tokens), 0)::bigint AS cached_tokens
FROM cost_ledger
WHERE org_id = $1 AND created_at >= $2 AND created_at < $3
`

type GetReportCostTotalsParams struct {
	OrgID       pgtype.UUID        `json:"org_id"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
	WindowEnd   pgtype.Timestamptz `json:"window_end"`
}

type GetReportCostTotalsRow struct {
	TotalCostUsd float64 `json:"total_cost_usd"`
	InputTokens  int64   `json:"input_tokens"`
	OutputTokens int64   `json:"output_tokens"`
	CachedTokens int64   `json:"cached_tokens"`
}

func (q *Queries) GetReportCostTotals(ctx context.Context, arg GetReportCostTotalsParams) (GetReportCostTotalsRow, error) {
	row := q.db.QueryRow(ctx, getReportCostTotals, arg.OrgID, arg.WindowStart, arg.WindowEnd)
	var i GetReportCostTotalsRow
	err := row.Scan(
		&i.TotalCostUsd,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedTokens,
	)
	return i, err
}

const getReportOrgInfo = `-- name: GetReportOrgInfo :one

SELECT o.name, o.digest_timezone,
       COALESCE(p.name, o.name)::text AS prepared_by
FROM organizations o
LEFT JOIN organizations p ON p.id = o.parent_practice_id
WHERE o.id = $1 AND o.is_active = true
`

type GetReportOrgInfoRow struct {
	Name           string `json:"name"`
	DigestTimezone string `json:"digest_timezone"`
	PreparedBy     string `json:"prepared_by"`
}

// System pool (app_system) below.
// prepared_by: the practice a client workspace belongs to, else the org itself.
func (q *Queries) GetReportOrgInfo(ctx context.Context, id pgtype.UUID) (GetReportOrgInfoRow, error) {
	row := q.db.QueryRow(ctx, getReportOrgInfo, id)
	var i GetReportOrgInfoRow
	err := row.Scan(&i.Name, &i.DigestTimezone, &i.PreparedBy)
	return i, err
}

const getReportRunSummary = `-- name: GetReportRunSummary :one

SELECT
    count(*) FILTER (WHERE status = 'completed')::bigint AS runs_completed,
    count(*) FILTER (WHERE status = 'failed')::bigint AS runs_failed,
    count(*)::bigint AS runs_total,
    COALESCE(SUM(hours_saved), 0)::double precision AS hours_saved,
    count(DISTINCT workflow_id)::bigint AS workflows_active
FROM workflow_runs
WHERE org_id = $1 AND parent_run_id IS NULL AND created_at >= $2 AND created_at < $3
`

type GetReportRunSummaryParams struct {
	OrgID       pgtype.UUID        `json:"org_id"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
	WindowEnd   pgtype.Timestamptz `json:"window_end"`
}

type GetReportRunSummaryRow struct {
	RunsCompleted   int64   `json:"runs_completed"`
	RunsFailed      int64   `json:"runs_failed"`
	RunsTotal       int64   `json:"runs_total"`
	HoursSaved      float64 `json:"hours_saved"`
	WorkflowsActive int64   `json:"workflows_active"`
}

// Workflow 23 (Client-Facing Reports & Sharing).
//
// Report *data* is aggregated under tenant.WithTx on the reported workspace
// (app_user + RLS), so a report can only ever contain that tenant's rows.
// Windows are half-open [from, to) timestamps the handler computes from the
// report's date range in the workspace's own timezone.
// parent_run_id IS NULL counts each end-to-end task once (a team run's
// specialist sub-runs aren't separate outcomes), same as the digest.
func (q *Queries) GetReportRunSummary(ctx context.Context, arg GetReportRunSummaryParams) (GetReportRunSummaryRow, error) {
	row := q.db.QueryRow(ctx, getReportRunSummary, arg.OrgID, arg.WindowStart, arg.WindowEnd)
	var i GetReportRunSummaryRow
	err := row.Scan(
		&i.RunsCompleted,
		&i.RunsFailed,
		&i.RunsTotal,
		&i.HoursSaved,
		&i.WorkflowsActive,
	)
	return i, err
}

const insertClientReport = `-- name: InsertClientReport :one
INSERT INTO client_reports (org_id, created_by_user_id, title, date_from, date_to, timezone,
                            visible_sections, snapshot, share_token, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, created_at
`

type InsertClientReportParams struct {
	OrgID           pgtype.UUID        `json:"org_id"`
	CreatedByUserID pgtype.UUID        `json:"created_by_user_id"`
	Title           string             `json:"title"`
	DateFrom        pgtype.Date        `json:"date_from"`
	DateTo          pgtype.Date        `json:"date_to"`
	Timezone        string             `json:"timezone"`
	VisibleSections []byte             `json:"visible_sections"`
	Snapshot        []byte             `json:"snapshot"`
	ShareToken      string             `json:"share_token"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

type InsertClientReportRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertClientReport(ctx context.Context, arg InsertClientReportParams) (InsertClientReportRow, error) {
	row := q.db.QueryRow(ctx, insertClientReport,
		arg.OrgID,
		arg.CreatedByUserID,
		arg.Title,
		arg.DateFrom,
		arg.DateTo,
		arg.Timezone,
		arg.VisibleSections,
		arg.Snapshot,
		arg.ShareToken,
		arg.ExpiresAt,
	)
	var i InsertClientReportRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listClientReportsForUser = `-- name: ListClientReportsForUser :many
SELECT r.id, r.org_id, o.name AS org_name, r.title, r.date_from, r.date_to, r.visible_sections,
       r.share_token, r.expires_at, r.view_count, r.last_viewed_at, r.is_revoked, r.created_at
FROM client_reports r
JOIN organizations o ON o.id = r.org_id AND o.is_active = true
JOIN users u ON u.org_id = r.org_id AND u.clerk_user_id = $1
            AND u.is_active = true AND u.role IN ('owner', 'admin')
WHERE $2::uuid IS NULL OR r.org_id = $2::uuid
ORDER BY r.created_at DESC
`

type ListClientReportsForUserParams struct {
	ClerkUserID string      `json:"clerk_user_id"`
	TargetOrgID pgtype.UUID `json:"target_org_id"`
}

type ListClientReportsForUserRow struct {
	ID              pgtype.UUID        `json:"id"`
	OrgID           pgtype.UUID        `json:"org_id"`
	OrgName         string             `json:"org_name"`
	Title           string             `json:"title"`
	DateFrom        pgtype.Date        `json:"date_from"`
	DateTo          pgtype.Date        `json:"date_to"`
	VisibleSections []byte             `json:"visible_sections"`
	ShareToken      string             `json:"share_token"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	ViewCount       int32              `json:"view_count"`
	LastViewedAt    pgtype.Timestamptz `json:"last_viewed_at"`
	IsRevoked       bool               `json:"is_revoked"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

// Operator-side list: only reports of workspaces where the caller is an
// active owner/admin. target_org_id NULL lists across all of them.
func (q *Queries) ListClientReportsForUser(ctx context.Context, arg ListClientReportsForUserParams) ([]ListClientReportsForUserRow, error) {
	rows, err := q.db.Query(ctx, listClientReportsForUser, arg.ClerkUserID, arg.TargetOrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClientReportsForUserRow
	for rows.Next() {
		var i ListClientReportsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.OrgName,
			&i.Title,
			&i.DateFrom,
			&i.DateTo,
			&i.VisibleSections,
			&i.ShareToken,
			&i.ExpiresAt,
			&i.ViewCount,
			&i.LastViewedAt,
			&i.IsRevoked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportCostByAgent = `-- name: ListReportCostByAgent :many
SELECT COALESCE(a.name, 'Unattributed') AS agent_name,
       COALESCE(SUM(cl.estimated_cost_usd), 0)::double precision AS cost_usd
FROM cost_ledger cl
LEFT JOIN agents a ON a.id = cl.agent_id
WHERE cl.org_id = $1 AND cl.created_at >= $2 AND cl.created_at < $3
GROUP BY a.name
ORDER BY cost_usd DESC
`

type ListReportCostByAgentParams struct {
	OrgID       pgtype.UUID        `json:"org_id"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
	WindowEnd   pgtype.Timestamptz `json:"window_end"`
}

type ListReportCostByAgentRow struct {
	AgentName string  `json:"agent_name"`
	CostUsd   float64 `json:"cost_usd"`
}

func (q *Queries) ListReportCostByAgent(ctx context.Context, arg ListReportCostByAgentParams) ([]ListReportCostByAgentRow, error) {
	rows, err := q.db.Query(ctx, listReportCostByAgent, arg.OrgID, arg.WindowStart, arg.WindowEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReportCostByAgentRow
	for rows.Next() {
		var i ListReportCostByAgentRow
		if err := rows.Scan(&i.AgentName, &i.CostUsd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportRuns = `-- name: ListReportRuns :many
SELECT r.id, w.name AS workflow_name, r.status, r.created_at, r.started_at, r.completed_at,
       r.hours_saved,
       (SELECT COALESCE(SUM(cl.estimated_cost_usd), 0) FROM cost_ledger cl
          WHERE cl.run_id = r.id
             OR cl.run_id IN (SELECT c.id FROM workflow_runs c WHERE c.parent_run_id = r.id))::double precision AS cost_usd
FROM workflow_runs r
JOIN workflows w ON w.id = r.workflow_id
WHERE r.org_id = $1 AND r.parent_run_id IS NULL AND r.created_at >= $2 AND r.created_at < $3
ORDER BY r.created_at DESC
LIMIT $4
`

type ListReportRunsParams struct {
	OrgID       pgtype.UUID        `json:"org_id"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
	WindowEnd   pgtype.Timestamptz `json:"window_end"`
	RowLimit    int32              `json:"row_limit"`
}

type ListReportRunsRow struct {
	ID           pgtype.UUID        `json:"id"`
	WorkflowName string             `json:"workflow_name"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	HoursSaved   *float64           `json:"hours_saved"`
	CostUsd      float64            `json:"cost_usd"`
}

// cost_usd includes a team run's specialist sub-runs, so one row carries the
// whole task's cost.
func (q *Queries) ListReportRuns(ctx context.Context, arg ListReportRunsParams) ([]ListReportRunsRow, error) {
	rows, err := q.db.Query(ctx, listReportRuns,
		arg.OrgID,
		arg.WindowStart,
		arg.WindowEnd,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReportRunsRow
	for rows.Next() {
		var i ListReportRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowName,
			&i.Status,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.HoursSaved,
			&i.CostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportWorkflowOutcomes = `-- name: ListReportWorkflowOutcomes :many
SELECT w.name,
       count(*) FILTER (WHERE r.status = 'completed')::bigint AS runs_completed,
       count(*)::bigint AS runs_total,
       COALESCE(SUM(r.hours_saved), 0)::double precision AS hours_saved
FROM workflow_runs r
JOIN workflows w ON w.id = r.workflow_id
WHERE r.org_id = $1 AND r.parent_run_id IS NULL AND r.created_at >= $2 AND r.created_at < $3
GROUP BY w.id, w.name
ORDER BY hours_saved DESC, w.name
`

type ListReportWorkflowOutcomesParams struct {
	OrgID       pgtype.UUID        `json:"org_id"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
	WindowEnd   pgtype.Timestamptz `json:"window_end"`
}

type ListReportWorkflowOutcomesRow struct {
	Name          string  `json:"name"`
	RunsCompleted int64   `json:"runs_completed"`
	RunsTotal     int64   `json:"runs_total"`
	HoursSaved    float64 `json:"hours_saved"`
}

func (q *Queries) ListReportWorkflowOutcomes(ctx context.Context, arg ListReportWorkflowOutcomesParams) ([]ListReportWorkflowOutcomesRow, error) {
	rows, err := q.db.Query(ctx, listReportWorkflowOutcomes, arg.OrgID, arg.WindowStart, arg.WindowEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReportWorkflowOutcomesRow
	for rows.Next() {
		var i ListReportWorkflowOutcomesRow
		if err := rows.Scan(
			&i.Name,
			&i.RunsCompleted,
			&i.RunsTotal,
			&i.HoursSaved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordClientReportView = `-- name: RecordClientReportView :exec
UPDATE client_reports SET view_count = view_count + 1, last_viewed_at = now() WHERE id = $1
`

func (q *Queries) RecordClientReportView(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, recordClientReportView, id)
	return err
}

const revokeClientReport = `-- name: RevokeClientReport :execrows
UPDATE client_reports SET is_revoked = true WHERE id = $1 AND org_id = $2 AND is_revoked = false
`

type RevokeClientReportParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) RevokeClientReport(ctx context.Context, arg RevokeClientReportParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeClientReport, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
