// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sop.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpSopPlaybookVersion = `-- name: BumpSopPlaybookVersion :one
UPDATE sop_playbooks SET
    agent_config = $3, workflow_config = $4, parameters = $5,
    current_version = current_version + 1
WHERE id = $1 AND practice_id = $2 AND is_active = true
RETURNING current_version
`

type BumpSopPlaybookVersionParams struct {
	ID             pgtype.UUID `json:"id"`
	PracticeID     pgtype.UUID `json:"practice_id"`
	AgentConfig    []byte      `json:"agent_config"`
	WorkflowConfig []byte      `json:"workflow_config"`
	Parameters     []byte      `json:"parameters"`
}

// The row lock this UPDATE takes serializes concurrent edits, and
// sop_playbook_versions' UNIQUE(sop_playbook_id, version) backs it up.
func (q *Queries) BumpSopPlaybookVersion(ctx context.Context, arg BumpSopPlaybookVersionParams) (int32, error) {
	row := q.db.QueryRow(ctx, bumpSopPlaybookVersion,
		arg.ID,
		arg.PracticeID,
		arg.AgentConfig,
		arg.WorkflowConfig,
		arg.Parameters,
	)
	var current_version int32
	err := row.Scan(&current_version)
	return current_version, err
}

const deactivateSopAgent = `-- name: DeactivateSopAgent :exec
UPDATE agents SET is_active = false WHERE org_id = $1 AND id = $2
`

type DeactivateSopAgentParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) DeactivateSopAgent(ctx context.Context, arg DeactivateSopAgentParams) error {
	_, err := q.db.Exec(ctx, deactivateSopAgent, arg.OrgID, arg.ID)
	return err
}

const deactivateSopDeployment = `-- name: DeactivateSopDeployment :execrows
UPDATE sop_deployments SET is_active = false WHERE id = $1 AND target_org_id = $2 AND is_active = true
`

type DeactivateSopDeploymentParams struct {
	ID          pgtype.UUID `json:"id"`
	TargetOrgID pgtype.UUID `json:"target_org_id"`
}

func (q *Queries) DeactivateSopDeployment(ctx context.Context, arg DeactivateSopDeploymentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateSopDeployment, arg.ID, arg.TargetOrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deactivateSopPlaybook = `-- name: DeactivateSopPlaybook :execrows
UPDATE sop_playbooks SET is_active = false WHERE id = $1 AND practice_id = $2 AND is_active = true
`

type DeactivateSopPlaybookParams struct {
	ID         pgtype.UUID `json:"id"`
	PracticeID pgtype.UUID `json:"practice_id"`
}

func (q *Queries) DeactivateSopPlaybook(ctx context.Context, arg DeactivateSopPlaybookParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateSopPlaybook, arg.ID, arg.PracticeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const detachSopDeployments = `-- name: DetachSopDeployments :exec
UPDATE sop_deployments SET is_active = false
WHERE sop_playbook_id = $1 AND is_active = true
`

// System pool: runs with the library delete, which executes in the
// practice's context, while deployments are only writable from their client
// workspace's. Stops tracking only — the agents/workflows are untouched and
// keep running; this just clears their "Managed by SOP" labels, since a
// deleted SOP can never sync them again.
func (q *Queries) DetachSopDeployments(ctx context.Context, sopPlaybookID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, detachSopDeployments, sopPlaybookID)
	return err
}

const getSopDeployment = `-- name: GetSopDeployment :one
SELECT d.id, d.target_org_id, d.deployed_version, d.parameter_overrides, d.agent_id, d.workflow_id
FROM sop_deployments d
WHERE d.id = $1 AND d.sop_playbook_id = $2 AND d.is_active = true
`

type GetSopDeploymentParams struct {
	ID            pgtype.UUID `json:"id"`
	SopPlaybookID pgtype.UUID `json:"sop_playbook_id"`
}

type GetSopDeploymentRow struct {
	ID                 pgtype.UUID `json:"id"`
	TargetOrgID        pgtype.UUID `json:"target_org_id"`
	DeployedVersion    int32       `json:"deployed_version"`
	ParameterOverrides []byte      `json:"parameter_overrides"`
	AgentID            pgtype.UUID `json:"agent_id"`
	WorkflowID         pgtype.UUID `json:"workflow_id"`
}

func (q *Queries) GetSopDeployment(ctx context.Context, arg GetSopDeploymentParams) (GetSopDeploymentRow, error) {
	row := q.db.QueryRow(ctx, getSopDeployment, arg.ID, arg.SopPlaybookID)
	var i GetSopDeploymentRow
	err := row.Scan(
		&i.ID,
		&i.TargetOrgID,
		&i.DeployedVersion,
		&i.ParameterOverrides,
		&i.AgentID,
		&i.WorkflowID,
	)
	return i, err
}

const getSopPlaybook = `-- name: GetSopPlaybook :one
SELECT id, name, description, category, current_version, agent_config, workflow_config,
       parameters, created_at, updated_at
FROM sop_playbooks
WHERE id = $1 AND practice_id = $2 AND is_active = true
`

type GetSopPlaybookParams struct {
	ID         pgtype.UUID `json:"id"`
	PracticeID pgtype.UUID `json:"practice_id"`
}

type GetSopPlaybookRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Description    *string            `json:"description"`
	Category       *string            `json:"category"`
	CurrentVersion int32              `json:"current_version"`
	AgentConfig    []byte             `json:"agent_config"`
	WorkflowConfig []byte             `json:"workflow_config"`
	Parameters     []byte             `json:"parameters"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSopPlaybook(ctx context.Context, arg GetSopPlaybookParams) (GetSopPlaybookRow, error) {
	row := q.db.QueryRow(ctx, getSopPlaybook, arg.ID, arg.PracticeID)
	var i GetSopPlaybookRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.CurrentVersion,
		&i.AgentConfig,
		&i.WorkflowConfig,
		&i.Parameters,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSopPlaybookVersion = `-- name: GetSopPlaybookVersion :one
SELECT agent_config, workflow_config, parameters FROM sop_playbook_versions
WHERE sop_playbook_id = $1 AND version = $2
`

type GetSopPlaybookVersionParams struct {
	SopPlaybookID pgtype.UUID `json:"sop_playbook_id"`
	Version       int32       `json:"version"`
}

type GetSopPlaybookVersionRow struct {
	AgentConfig    []byte `json:"agent_config"`
	WorkflowConfig []byte `json:"workflow_config"`
	Parameters     []byte `json:"parameters"`
}

func (q *Queries) GetSopPlaybookVersion(ctx context.Context, arg GetSopPlaybookVersionParams) (GetSopPlaybookVersionRow, error) {
	row := q.db.QueryRow(ctx, getSopPlaybookVersion, arg.SopPlaybookID, arg.Version)
	var i GetSopPlaybookVersionRow
	err := row.Scan(&i.AgentConfig, &i.WorkflowConfig, &i.Parameters)
	return i, err
}

const hasActiveSopDeployment = `-- name: HasActiveSopDeployment :one
SELECT EXISTS (
    SELECT 1 FROM sop_deployments
    WHERE sop_playbook_id = $1 AND target_org_id = $2 AND is_active = true
)::boolean
`

type HasActiveSopDeploymentParams struct {
	SopPlaybookID pgtype.UUID `json:"sop_playbook_id"`
	TargetOrgID   pgtype.UUID `json:"target_org_id"`
}

func (q *Queries) HasActiveSopDeployment(ctx context.Context, arg HasActiveSopDeploymentParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveSopDeployment, arg.SopPlaybookID, arg.TargetOrgID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const insertSopDeployment = `-- name: InsertSopDeployment :one

INSERT INTO sop_deployments (sop_playbook_id, sop_name, deployed_version, target_org_id, agent_id, workflow_id, parameter_overrides, deployed_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, deployed_at
`

type InsertSopDeploymentParams struct {
	SopPlaybookID      pgtype.UUID `json:"sop_playbook_id"`
	SopName            string      `json:"sop_name"`
	DeployedVersion    int32       `json:"deployed_version"`
	TargetOrgID        pgtype.UUID `json:"target_org_id"`
	AgentID            pgtype.UUID `json:"agent_id"`
	WorkflowID         pgtype.UUID `json:"workflow_id"`
	ParameterOverrides []byte      `json:"parameter_overrides"`
	DeployedBy         pgtype.UUID `json:"deployed_by"`
}

type InsertSopDeploymentRow struct {
	ID         pgtype.UUID        `json:"id"`
	DeployedAt pgtype.Timestamptz `json:"deployed_at"`
}

// Client-side writes (tenant.WithTx on the target workspace).
func (q *Queries) InsertSopDeployment(ctx context.Context, arg InsertSopDeploymentParams) (InsertSopDeploymentRow, error) {
	row := q.db.QueryRow(ctx, insertSopDeployment,
		arg.SopPlaybookID,
		arg.SopName,
		arg.DeployedVersion,
		arg.TargetOrgID,
		arg.AgentID,
		arg.WorkflowID,
		arg.ParameterOverrides,
		arg.DeployedBy,
	)
	var i InsertSopDeploymentRow
	err := row.Scan(&i.ID, &i.DeployedAt)
	return i, err
}

const insertSopPlaybook = `-- name: InsertSopPlaybook :one
INSERT INTO sop_playbooks (practice_id, name, description, category, agent_config, workflow_config, parameters, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (practice_id, name) WHERE is_active = true DO NOTHING
RETURNING id
`

type InsertSopPlaybookParams struct {
	PracticeID     pgtype.UUID `json:"practice_id"`
	Name           string      `json:"name"`
	Description    *string     `json:"description"`
	Category       *string     `json:"category"`
	AgentConfig    []byte      `json:"agent_config"`
	WorkflowConfig []byte      `json:"workflow_config"`
	Parameters     []byte      `json:"parameters"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

// A name collision with another active SOP returns no row (ErrNoRows), same
// convention as InsertAgent.
func (q *Queries) InsertSopPlaybook(ctx context.Context, arg InsertSopPlaybookParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertSopPlaybook,
		arg.PracticeID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.AgentConfig,
		arg.WorkflowConfig,
		arg.Parameters,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertSopPlaybookVersion = `-- name: InsertSopPlaybookVersion :exec
INSERT INTO sop_playbook_versions (sop_playbook_id, version, agent_config, workflow_config, parameters, changelog, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertSopPlaybookVersionParams struct {
	SopPlaybookID  pgtype.UUID `json:"sop_playbook_id"`
	Version        int32       `json:"version"`
	AgentConfig    []byte      `json:"agent_config"`
	WorkflowConfig []byte      `json:"workflow_config"`
	Parameters     []byte      `json:"parameters"`
	Changelog      *string     `json:"changelog"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) InsertSopPlaybookVersion(ctx context.Context, arg InsertSopPlaybookVersionParams) error {
	_, err := q.db.Exec(ctx, insertSopPlaybookVersion,
		arg.SopPlaybookID,
		arg.Version,
		arg.AgentConfig,
		arg.WorkflowConfig,
		arg.Parameters,
		arg.Changelog,
		arg.CreatedBy,
	)
	return err
}

const listConnectedServices = `-- name: ListConnectedServices :many
SELECT service_name FROM mcp_connections WHERE org_id = $1 AND is_active = true
`

func (q *Queries) ListConnectedServices(ctx context.Context, orgID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listConnectedServices, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var service_name string
		if err := rows.Scan(&service_name); err != nil {
			return nil, err
		}
		items = append(items, service_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSopDeploymentsForPlaybook = `-- name: ListSopDeploymentsForPlaybook :many
SELECT d.id, d.target_org_id, o.name AS workspace_name, o.is_active AS workspace_active,
       d.deployed_version, d.parameter_overrides, d.agent_id, d.workflow_id,
       d.deployed_at, d.synced_at,
       COALESCE(a.is_active, false)::boolean AS agent_active,
       ARRAY(SELECT m.service_name FROM mcp_connections m
              WHERE m.org_id = d.target_org_id AND m.is_active = true)::text[] AS connected_services
FROM sop_deployments d
JOIN organizations o ON o.id = d.target_org_id
JOIN agents a ON a.id = d.agent_id
JOIN users u ON u.org_id = d.target_org_id AND u.clerk_user_id = $2 AND u.is_active = true
WHERE d.sop_playbook_id = $1 AND d.is_active = true
ORDER BY o.name
`

type ListSopDeploymentsForPlaybookParams struct {
	SopPlaybookID pgtype.UUID `json:"sop_playbook_id"`
	ClerkUserID   string      `json:"clerk_user_id"`
}

type ListSopDeploymentsForPlaybookRow struct {
	ID                 pgtype.UUID        `json:"id"`
	TargetOrgID        pgtype.UUID        `json:"target_org_id"`
	WorkspaceName      string             `json:"workspace_name"`
	WorkspaceActive    *bool              `json:"workspace_active"`
	DeployedVersion    int32              `json:"deployed_version"`
	ParameterOverrides []byte             `json:"parameter_overrides"`
	AgentID            pgtype.UUID        `json:"agent_id"`
	WorkflowID         pgtype.UUID        `json:"workflow_id"`
	DeployedAt         pgtype.Timestamptz `json:"deployed_at"`
	SyncedAt           pgtype.Timestamptz `json:"synced_at"`
	AgentActive        bool               `json:"agent_active"`
	ConnectedServices  []string           `json:"connected_services"`
}

// Only workspaces the caller belongs to, same rule as the portfolio.
func (q *Queries) ListSopDeploymentsForPlaybook(ctx context.Context, arg ListSopDeploymentsForPlaybookParams) ([]ListSopDeploymentsForPlaybookRow, error) {
	rows, err := q.db.Query(ctx, listSopDeploymentsForPlaybook, arg.SopPlaybookID, arg.ClerkUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSopDeploymentsForPlaybookRow
	for rows.Next() {
		var i ListSopDeploymentsForPlaybookRow
		if err := rows.Scan(
			&i.ID,
			&i.TargetOrgID,
			&i.WorkspaceName,
			&i.WorkspaceActive,
			&i.DeployedVersion,
			&i.ParameterOverrides,
			&i.AgentID,
			&i.WorkflowID,
			&i.DeployedAt,
			&i.SyncedAt,
			&i.AgentActive,
			&i.ConnectedServices,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSopManagedResources = `-- name: ListSopManagedResources :many
SELECT agent_id, workflow_id, sop_name, deployed_version
FROM sop_deployments
WHERE target_org_id = $1 AND is_active = true
`

type ListSopManagedResourcesRow struct {
	AgentID         pgtype.UUID `json:"agent_id"`
	WorkflowID      pgtype.UUID `json:"workflow_id"`
	SopName         string      `json:"sop_name"`
	DeployedVersion int32       `json:"deployed_version"`
}

// Tenant-scoped (app_user in the client workspace): which of this
// workspace's agents/workflows a SOP deployment manages, for the "Managed by
// SOP" labels. sop_name is the deployment's own snapshot, since the
// practice's playbook rows are invisible from here.
func (q *Queries) ListSopManagedResources(ctx context.Context, targetOrgID pgtype.UUID) ([]ListSopManagedResourcesRow, error) {
	rows, err := q.db.Query(ctx, listSopManagedResources, targetOrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSopManagedResourcesRow
	for rows.Next() {
		var i ListSopManagedResourcesRow
		if err := rows.Scan(
			&i.AgentID,
			&i.WorkflowID,
			&i.SopName,
			&i.DeployedVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSopPlaybookVersions = `-- name: ListSopPlaybookVersions :many
SELECT version, changelog, created_at FROM sop_playbook_versions
WHERE sop_playbook_id = $1 ORDER BY version DESC
`

type ListSopPlaybookVersionsRow struct {
	Version   int32              `json:"version"`
	Changelog *string            `json:"changelog"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListSopPlaybookVersions(ctx context.Context, sopPlaybookID pgtype.UUID) ([]ListSopPlaybookVersionsRow, error) {
	rows, err := q.db.Query(ctx, listSopPlaybookVersions, sopPlaybookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSopPlaybookVersionsRow
	for rows.Next() {
		var i ListSopPlaybookVersionsRow
		if err := rows.Scan(&i.Version, &i.Changelog, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSopPlaybooks = `-- name: ListSopPlaybooks :many

SELECT p.id, p.name, p.description, p.category, p.current_version,
       p.agent_config, p.workflow_config, p.parameters, p.created_at, p.updated_at,
       (SELECT count(*) FROM sop_deployments d
          JOIN organizations o ON o.id = d.target_org_id AND o.is_active = true
          JOIN users u ON u.org_id = d.target_org_id AND u.clerk_user_id = $1 AND u.is_active = true
         WHERE d.sop_playbook_id = p.id AND d.is_active = true)::bigint AS active_deployments,
       (SELECT count(*) FROM sop_deployments d
          JOIN organizations o ON o.id = d.target_org_id AND o.is_active = true
          JOIN users u ON u.org_id = d.target_org_id AND u.clerk_user_id = $1 AND u.is_active = true
         WHERE d.sop_playbook_id = p.id AND d.is_active = true
           AND d.deployed_version < p.current_version)::bigint AS outdated_deployments
FROM sop_playbooks p
WHERE p.practice_id = $2 AND p.is_active = true
ORDER BY p.name
`

type ListSopPlaybooksParams struct {
	ClerkUserID string      `json:"clerk_user_id"`
	PracticeID  pgtype.UUID `json:"practice_id"`
}

type ListSopPlaybooksRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	Description         *string            `json:"description"`
	Category            *string            `json:"category"`
	CurrentVersion      int32              `json:"current_version"`
	AgentConfig         []byte             `json:"agent_config"`
	WorkflowConfig      []byte             `json:"workflow_config"`
	Parameters          []byte             `json:"parameters"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ActiveDeployments   int64              `json:"active_deployments"`
	OutdatedDeployments int64              `json:"outdated_deployments"`
}

// Workflow 22 (SOP Library). Two trust boundaries, same split as practice.sql:
//   - reads that span tenants (a playbook's deployments across client
//     workspaces, with their names and connected integrations) run on
//     app_system, and every one is pinned to the practice_id the handler
//     already authorized plus the caller's own active memberships;
//   - writes run on app_user under tenant.WithTx — playbook edits scoped to
//     the practice, deploy/sync writes scoped to the target client workspace
//     (sop_deployments' WITH CHECK only admits rows for the current org).
//
// System pool: the deployment counts join client organizations, which the
// practice's own RLS context can't see. Counts only workspaces the caller
// belongs to, the same rule as ListSopDeploymentsForPlaybook, so a card's
// count always matches the deployments list behind it.
func (q *Queries) ListSopPlaybooks(ctx context.Context, arg ListSopPlaybooksParams) ([]ListSopPlaybooksRow, error) {
	rows, err := q.db.Query(ctx, listSopPlaybooks, arg.ClerkUserID, arg.PracticeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSopPlaybooksRow
	for rows.Next() {
		var i ListSopPlaybooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.CurrentVersion,
			&i.AgentConfig,
			&i.WorkflowConfig,
			&i.Parameters,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActiveDeployments,
			&i.OutdatedDeployments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSopDeploymentSynced = `-- name: MarkSopDeploymentSynced :exec
UPDATE sop_deployments SET
    deployed_version = $3, parameter_overrides = $4, sop_name = $5, workflow_id = $6, synced_at = now()
WHERE id = $1 AND target_org_id = $2
`

type MarkSopDeploymentSyncedParams struct {
	ID                 pgtype.UUID `json:"id"`
	TargetOrgID        pgtype.UUID `json:"target_org_id"`
	DeployedVersion    int32       `json:"deployed_version"`
	ParameterOverrides []byte      `json:"parameter_overrides"`
	SopName            string      `json:"sop_name"`
	WorkflowID         pgtype.UUID `json:"workflow_id"`
}

func (q *Queries) MarkSopDeploymentSynced(ctx context.Context, arg MarkSopDeploymentSyncedParams) error {
	_, err := q.db.Exec(ctx, markSopDeploymentSynced,
		arg.ID,
		arg.TargetOrgID,
		arg.DeployedVersion,
		arg.ParameterOverrides,
		arg.SopName,
		arg.WorkflowID,
	)
	return err
}

const pauseSopWorkflow = `-- name: PauseSopWorkflow :exec
UPDATE workflows SET is_active = false WHERE org_id = $1 AND id = $2
`

type PauseSopWorkflowParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) PauseSopWorkflow(ctx context.Context, arg PauseSopWorkflowParams) error {
	_, err := q.db.Exec(ctx, pauseSopWorkflow, arg.OrgID, arg.ID)
	return err
}

const syncSopAgent = `-- name: SyncSopAgent :one
UPDATE agents SET
    name = $3, description = $4, agent_type = $5, model = $6, system_prompt = $7,
    max_output_tokens = $8, temperature = $9, policy_scope = $10, allowed_mcp_servers = $11,
    version = version + 1
WHERE org_id = $1 AND id = $2 AND is_active = true
RETURNING id
`

type SyncSopAgentParams struct {
	OrgID             pgtype.UUID `json:"org_id"`
	ID                pgtype.UUID `json:"id"`
	Name              string      `json:"name"`
	Description       *string     `json:"description"`
	AgentType         string      `json:"agent_type"`
	Model             *string     `json:"model"`
	SystemPrompt      string      `json:"system_prompt"`
	MaxOutputTokens   *int32      `json:"max_output_tokens"`
	Temperature       *float64    `json:"temperature"`
	PolicyScope       []byte      `json:"policy_scope"`
	AllowedMcpServers []byte      `json:"allowed_mcp_servers"`
}

// Overwrites every SOP-controlled field. Returns no row if the client has
// since removed the agent, which the handler reports as a broken deployment.
func (q *Queries) SyncSopAgent(ctx context.Context, arg SyncSopAgentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, syncSopAgent,
		arg.OrgID,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.AgentType,
		arg.Model,
		arg.SystemPrompt,
		arg.MaxOutputTokens,
		arg.Temperature,
		arg.PolicyScope,
		arg.AllowedMcpServers,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const syncSopWorkflow = `-- name: SyncSopWorkflow :execrows
UPDATE workflows SET
    name = $3, description = $4, trigger_type = $5, cron_expression = $6, next_run_at = $7,
    requires_approval = $8, task_input_template = $9, estimated_manual_minutes = $10,
    version = version + 1
WHERE org_id = $1 AND id = $2
`

type SyncSopWorkflowParams struct {
	OrgID                  pgtype.UUID        `json:"org_id"`
	ID                     pgtype.UUID        `json:"id"`
	Name                   string             `json:"name"`
	Description            *string            `json:"description"`
	TriggerType            string             `json:"trigger_type"`
	CronExpression         *string            `json:"cron_expression"`
	NextRunAt              pgtype.Timestamptz `json:"next_run_at"`
	RequiresApproval       *bool              `json:"requires_approval"`
	TaskInputTemplate      *string            `json:"task_input_template"`
	EstimatedManualMinutes *int32             `json:"estimated_manual_minutes"`
}

// Deliberately leaves is_active alone: a sync must never un-pause a
// workflow the client paused.
func (q *Queries) SyncSopWorkflow(ctx context.Context, arg SyncSopWorkflowParams) (int64, error) {
	result, err := q.db.Exec(ctx, syncSopWorkflow,
		arg.OrgID,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.TriggerType,
		arg.CronExpression,
		arg.NextRunAt,
		arg.RequiresApproval,
		arg.TaskInputTemplate,
		arg.EstimatedManualMinutes,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSopPlaybookMeta = `-- name: UpdateSopPlaybookMeta :execrows
UPDATE sop_playbooks SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    category = COALESCE($3, category)
WHERE id = $4 AND practice_id = $5 AND is_active = true
`

type UpdateSopPlaybookMetaParams struct {
	Name        *string     `json:"name"`
	Description *string     `json:"description"`
	Category    *string     `json:"category"`
	ID          pgtype.UUID `json:"id"`
	PracticeID  pgtype.UUID `json:"practice_id"`
}

// Name/description/category aren't part of what a deployment renders, so
// they change in place without a new version.
func (q *Queries) UpdateSopPlaybookMeta(ctx context.Context, arg UpdateSopPlaybookMetaParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSopPlaybookMeta,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.ID,
		arg.PracticeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
