// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deactivateAgentTeam = `-- name: DeactivateAgentTeam :execrows
UPDATE agent_teams SET is_active = false WHERE org_id = $1 AND id = $2 AND is_active = true
`

type DeactivateAgentTeamParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

// One-way, unlike workflows' pause/resume DeactivateWorkflow — a team has
// no equivalent "reactivate" endpoint (see GetAgentTeam's own note).
func (q *Queries) DeactivateAgentTeam(ctx context.Context, arg DeactivateAgentTeamParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateAgentTeam, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgentForA2AManifest = `-- name: GetAgentForA2AManifest :one
SELECT id, org_id, name, description, model, team_role, policy_scope, version
FROM agents
WHERE org_id = $1 AND id = $2 AND is_active = true
`

type GetAgentForA2AManifestParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

type GetAgentForA2AManifestRow struct {
	ID          pgtype.UUID `json:"id"`
	OrgID       pgtype.UUID `json:"org_id"`
	Name        string      `json:"name"`
	Description *string     `json:"description"`
	Model       *string     `json:"model"`
	TeamRole    *string     `json:"team_role"`
	PolicyScope []byte      `json:"policy_scope"`
	Version     *int32      `json:"version"`
}

// The fields internal/core/a2a/manifest.go needs to build an A2A agent
// card — name/description/model for display, policy_scope's allowed_tools
// for the card's declared "skills" (an external caller should be able to
// see what a specialist can actually do before dispatching a task to it).
func (q *Queries) GetAgentForA2AManifest(ctx context.Context, arg GetAgentForA2AManifestParams) (GetAgentForA2AManifestRow, error) {
	row := q.db.QueryRow(ctx, getAgentForA2AManifest, arg.OrgID, arg.ID)
	var i GetAgentForA2AManifestRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Model,
		&i.TeamRole,
		&i.PolicyScope,
		&i.Version,
	)
	return i, err
}

const getAgentTeam = `-- name: GetAgentTeam :one
SELECT t.id, t.name, t.description, t.orchestrator_agent_id, o.name AS orchestrator_agent_name,
       t.max_agent_hops, t.parallel_execution, t.timeout_seconds, t.is_active,
       t.created_at, t.updated_at
FROM agent_teams t
JOIN agents o ON o.id = t.orchestrator_agent_id
WHERE t.org_id = $1 AND t.id = $2 AND t.is_active = true
`

type GetAgentTeamParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

type GetAgentTeamRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Name                  string             `json:"name"`
	Description           *string            `json:"description"`
	OrchestratorAgentID   pgtype.UUID        `json:"orchestrator_agent_id"`
	OrchestratorAgentName string             `json:"orchestrator_agent_name"`
	MaxAgentHops          *int32             `json:"max_agent_hops"`
	ParallelExecution     *bool              `json:"parallel_execution"`
	TimeoutSeconds        *int32             `json:"timeout_seconds"`
	IsActive              *bool              `json:"is_active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

// is_active = true, unlike GetWorkflow's deliberate "show it either way"
// choice — a deactivated team has no equivalent of a workflow's
// pause/resume toggle (DeactivateAgentTeam is a one-way soft delete, see
// its own doc comment), so a founder should never be able to Get or Run
// one again after deleting it.
func (q *Queries) GetAgentTeam(ctx context.Context, arg GetAgentTeamParams) (GetAgentTeamRow, error) {
	row := q.db.QueryRow(ctx, getAgentTeam, arg.OrgID, arg.ID)
	var i GetAgentTeamRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OrchestratorAgentID,
		&i.OrchestratorAgentName,
		&i.MaxAgentHops,
		&i.ParallelExecution,
		&i.TimeoutSeconds,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentTeamMemberRole = `-- name: GetAgentTeamMemberRole :one
SELECT role FROM agent_team_members WHERE team_id = $1 AND agent_id = $2
`

type GetAgentTeamMemberRoleParams struct {
	TeamID  pgtype.UUID `json:"team_id"`
	AgentID pgtype.UUID `json:"agent_id"`
}

// The real authorization check behind POST .../a2a/agents/{agent_id}/tasks/send:
// an orchestrator's dispatching run resolves its own team via
// GetRunTeamID, then this confirms the requested target agent is actually
// a member of *that* team (pgx.ErrNoRows if not, treated as 403) — never
// trusts a client-supplied role or team id.
func (q *Queries) GetAgentTeamMemberRole(ctx context.Context, arg GetAgentTeamMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getAgentTeamMemberRole, arg.TeamID, arg.AgentID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const insertAgentTeam = `-- name: InsertAgentTeam :one

INSERT INTO agent_teams (org_id, name, description, orchestrator_agent_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, orchestrator_agent_id, max_agent_hops,
    parallel_execution, timeout_seconds, is_active, created_at, updated_at
`

type InsertAgentTeamParams struct {
	OrgID               pgtype.UUID `json:"org_id"`
	Name                string      `json:"name"`
	Description         *string     `json:"description"`
	OrchestratorAgentID pgtype.UUID `json:"orchestrator_agent_id"`
}

type InsertAgentTeamRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	Description         *string            `json:"description"`
	OrchestratorAgentID pgtype.UUID        `json:"orchestrator_agent_id"`
	MaxAgentHops        *int32             `json:"max_agent_hops"`
	ParallelExecution   *bool              `json:"parallel_execution"`
	TimeoutSeconds      *int32             `json:"timeout_seconds"`
	IsActive            *bool              `json:"is_active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

// Queries backing workflow 18 (Multi-Agent Team Run / A2A). agent_teams
// and agent_team_members have existed, RLS-covered, since 000001/000002 —
// these are the first queries ever written against them. All tenant-scoped
// through app_user via tenant.WithTx, same as every other feature area in
// this file set — team membership and A2A dispatch never cross an org
// boundary.
func (q *Queries) InsertAgentTeam(ctx context.Context, arg InsertAgentTeamParams) (InsertAgentTeamRow, error) {
	row := q.db.QueryRow(ctx, insertAgentTeam,
		arg.OrgID,
		arg.Name,
		arg.Description,
		arg.OrchestratorAgentID,
	)
	var i InsertAgentTeamRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OrchestratorAgentID,
		&i.MaxAgentHops,
		&i.ParallelExecution,
		&i.TimeoutSeconds,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAgentTeamMember = `-- name: InsertAgentTeamMember :one
INSERT INTO agent_team_members (team_id, agent_id, role, priority)
VALUES ($1, $2, $3, $4)
RETURNING id, team_id, agent_id, role, priority
`

type InsertAgentTeamMemberParams struct {
	TeamID   pgtype.UUID `json:"team_id"`
	AgentID  pgtype.UUID `json:"agent_id"`
	Role     string      `json:"role"`
	Priority *int32      `json:"priority"`
}

type InsertAgentTeamMemberRow struct {
	ID       pgtype.UUID `json:"id"`
	TeamID   pgtype.UUID `json:"team_id"`
	AgentID  pgtype.UUID `json:"agent_id"`
	Role     string      `json:"role"`
	Priority *int32      `json:"priority"`
}

func (q *Queries) InsertAgentTeamMember(ctx context.Context, arg InsertAgentTeamMemberParams) (InsertAgentTeamMemberRow, error) {
	row := q.db.QueryRow(ctx, insertAgentTeamMember,
		arg.TeamID,
		arg.AgentID,
		arg.Role,
		arg.Priority,
	)
	var i InsertAgentTeamMemberRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.AgentID,
		&i.Role,
		&i.Priority,
	)
	return i, err
}

const isAgentOnActiveTeam = `-- name: IsAgentOnActiveTeam :one
SELECT EXISTS (
    SELECT 1 FROM agent_team_members m
    JOIN agent_teams t ON t.id = m.team_id
    WHERE m.agent_id = $1 AND t.org_id = $2 AND t.is_active = true
) AS on_active_team
`

type IsAgentOnActiveTeamParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	OrgID   pgtype.UUID `json:"org_id"`
}

// Gates internal/core/a2a's manifest/tasks-send endpoints: only an agent
// that is (still) a member of at least one active team is A2A-addressable.
// Checked live against agent_team_members/agent_teams, not a cached flag —
// same "don't trust a second source of truth" reasoning as workflow 9's
// policy_scope decision (see CLAUDE.md's Agent Execution Engine section) —
// a member removed from every team loses A2A reachability immediately, not
// whenever some denormalized column next happens to get refreshed.
func (q *Queries) IsAgentOnActiveTeam(ctx context.Context, arg IsAgentOnActiveTeamParams) (bool, error) {
	row := q.db.QueryRow(ctx, isAgentOnActiveTeam, arg.AgentID, arg.OrgID)
	var on_active_team bool
	err := row.Scan(&on_active_team)
	return on_active_team, err
}

const listAgentTeamMembers = `-- name: ListAgentTeamMembers :many
SELECT m.id, m.agent_id, a.name AS agent_name, a.description AS agent_description,
       m.role, m.priority
FROM agent_team_members m
JOIN agents a ON a.id = m.agent_id
WHERE m.team_id = $1
ORDER BY m.priority ASC, m.created_at ASC
`

type ListAgentTeamMembersRow struct {
	ID               pgtype.UUID `json:"id"`
	AgentID          pgtype.UUID `json:"agent_id"`
	AgentName        string      `json:"agent_name"`
	AgentDescription *string     `json:"agent_description"`
	Role             string      `json:"role"`
	Priority         *int32      `json:"priority"`
}

// Joined against agents for display (name, description, model) — the
// specialist card the team page and the multi-agent pipeline UI both need,
// without a second round trip per member.
func (q *Queries) ListAgentTeamMembers(ctx context.Context, teamID pgtype.UUID) ([]ListAgentTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listAgentTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentTeamMembersRow
	for rows.Next() {
		var i ListAgentTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.AgentName,
			&i.AgentDescription,
			&i.Role,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentTeamsForOrg = `-- name: ListAgentTeamsForOrg :many
SELECT t.id, t.name, t.description, t.orchestrator_agent_id, o.name AS orchestrator_agent_name,
       t.max_agent_hops, t.parallel_execution, t.timeout_seconds, t.is_active,
       t.created_at, t.updated_at,
       (SELECT COUNT(*) FROM agent_team_members m WHERE m.team_id = t.id) AS member_count
FROM agent_teams t
JOIN agents o ON o.id = t.orchestrator_agent_id
WHERE t.org_id = $1 AND t.is_active = true
ORDER BY t.created_at DESC
`

type ListAgentTeamsForOrgRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Name                  string             `json:"name"`
	Description           *string            `json:"description"`
	OrchestratorAgentID   pgtype.UUID        `json:"orchestrator_agent_id"`
	OrchestratorAgentName string             `json:"orchestrator_agent_name"`
	MaxAgentHops          *int32             `json:"max_agent_hops"`
	ParallelExecution     *bool              `json:"parallel_execution"`
	TimeoutSeconds        *int32             `json:"timeout_seconds"`
	IsActive              *bool              `json:"is_active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	MemberCount           int64              `json:"member_count"`
}

// member_count is a correlated subquery, same reasoning as ListAgents'
// workflow_count — a team with 0 members (mid-setup, or every member
// since removed) must still appear exactly once.
func (q *Queries) ListAgentTeamsForOrg(ctx context.Context, orgID pgtype.UUID) ([]ListAgentTeamsForOrgRow, error) {
	rows, err := q.db.Query(ctx, listAgentTeamsForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentTeamsForOrgRow
	for rows.Next() {
		var i ListAgentTeamsForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OrchestratorAgentID,
			&i.OrchestratorAgentName,
			&i.MaxAgentHops,
			&i.ParallelExecution,
			&i.TimeoutSeconds,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const validateAgentForTeamMembership = `-- name: ValidateAgentForTeamMembership :one
SELECT id, name FROM agents WHERE org_id = $1 AND id = $2 AND is_active = true
`

type ValidateAgentForTeamMembershipParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

type ValidateAgentForTeamMembershipRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

// Same "must belong to this org and be active" guard InsertWorkflow's
// ValidateAgentForOrg already applies to workflows — a team's orchestrator
// and every specialist must pass it too.
func (q *Queries) ValidateAgentForTeamMembership(ctx context.Context, arg ValidateAgentForTeamMembershipParams) (ValidateAgentForTeamMembershipRow, error) {
	row := q.db.QueryRow(ctx, validateAgentForTeamMembership, arg.OrgID, arg.ID)
	var i ValidateAgentForTeamMembershipRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
