// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAgentTemplate = `-- name: GetAgentTemplate :one
SELECT id, name, description, category, system_prompt, model, policy_scope, icon, is_featured
FROM agent_templates
WHERE id = $1 AND is_active = true
`

type GetAgentTemplateRow struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Description  string      `json:"description"`
	Category     string      `json:"category"`
	SystemPrompt string      `json:"system_prompt"`
	Model        string      `json:"model"`
	PolicyScope  []byte      `json:"policy_scope"`
	Icon         string      `json:"icon"`
	IsFeatured   bool        `json:"is_featured"`
}

func (q *Queries) GetAgentTemplate(ctx context.Context, id pgtype.UUID) (GetAgentTemplateRow, error) {
	row := q.db.QueryRow(ctx, getAgentTemplate, id)
	var i GetAgentTemplateRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.SystemPrompt,
		&i.Model,
		&i.PolicyScope,
		&i.Icon,
		&i.IsFeatured,
	)
	return i, err
}

const listAgentTemplates = `-- name: ListAgentTemplates :many

SELECT id, name, description, category, icon, is_featured,
       jsonb_array_length(policy_scope->'allowed_tools') AS tool_count
FROM agent_templates
WHERE is_active = true
  AND ($1::varchar IS NULL OR category = $1)
ORDER BY is_featured DESC, name ASC
`

type ListAgentTemplatesRow struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Category    string      `json:"category"`
	Icon        string      `json:"icon"`
	IsFeatured  bool        `json:"is_featured"`
	ToolCount   int32       `json:"tool_count"`
}

// Queries backing workflow 19 (Agent Templates Marketplace). Deliberately
// run through app_user like everything else in this file set — not
// app_system — even though agent_templates has no org_id/RLS of its own:
// a request handler already runs inside tenant.WithTx for its other work
// (the install path also touches agents, which IS RLS-scoped), and there
// is no cross-tenant write here that would need app_system's bypass.
func (q *Queries) ListAgentTemplates(ctx context.Context, category *string) ([]ListAgentTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listAgentTemplates, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentTemplatesRow
	for rows.Next() {
		var i ListAgentTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Icon,
			&i.IsFeatured,
			&i.ToolCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
