// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflows.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deactivateWorkflow = `-- name: DeactivateWorkflow :execrows
UPDATE workflows SET is_active = false WHERE org_id = $1 AND id = $2 AND is_active = true
`

type DeactivateWorkflowParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

// Semantically identical to PATCH {is_active: false} (pause) — kept as its
// own endpoint only for symmetry with every other resource's DELETE verb
// in this codebase, not because it does anything a pause doesn't already
// do. See CLAUDE.md's workflow 8 section for why workflows don't have a
// separate "really gone" state the way documents/agents effectively do.
func (q *Queries) DeactivateWorkflow(ctx context.Context, arg DeactivateWorkflowParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateWorkflow, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT w.id, w.agent_id, a.name AS agent_name, w.name, w.description,
       w.trigger_type, w.cron_expression, w.timezone, w.next_run_at,
       w.requires_approval, w.task_input_template, w.estimated_manual_minutes,
       w.is_active, w.version, w.created_at, w.updated_at
FROM workflows w
JOIN agents a ON a.id = w.agent_id
WHERE w.org_id = $1 AND w.id = $2
`

type GetWorkflowParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

type GetWorkflowRow struct {
	ID                     pgtype.UUID        `json:"id"`
	AgentID                pgtype.UUID        `json:"agent_id"`
	AgentName              string             `json:"agent_name"`
	Name                   string             `json:"name"`
	Description            *string            `json:"description"`
	TriggerType            string             `json:"trigger_type"`
	CronExpression         *string            `json:"cron_expression"`
	Timezone               *string            `json:"timezone"`
	NextRunAt              pgtype.Timestamptz `json:"next_run_at"`
	RequiresApproval       *bool              `json:"requires_approval"`
	TaskInputTemplate      *string            `json:"task_input_template"`
	EstimatedManualMinutes *int32             `json:"estimated_manual_minutes"`
	IsActive               *bool              `json:"is_active"`
	Version                *int32             `json:"version"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetWorkflow(ctx context.Context, arg GetWorkflowParams) (GetWorkflowRow, error) {
	row := q.db.QueryRow(ctx, getWorkflow, arg.OrgID, arg.ID)
	var i GetWorkflowRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.AgentName,
		&i.Name,
		&i.Description,
		&i.TriggerType,
		&i.CronExpression,
		&i.Timezone,
		&i.NextRunAt,
		&i.RequiresApproval,
		&i.TaskInputTemplate,
		&i.EstimatedManualMinutes,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowRun = `-- name: GetWorkflowRun :one
SELECT id, workflow_id, status, triggered_by FROM workflow_runs WHERE org_id = $1 AND id = $2
`

type GetWorkflowRunParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

type GetWorkflowRunRow struct {
	ID          pgtype.UUID `json:"id"`
	WorkflowID  pgtype.UUID `json:"workflow_id"`
	Status      string      `json:"status"`
	TriggeredBy pgtype.UUID `json:"triggered_by"`
}

func (q *Queries) GetWorkflowRun(ctx context.Context, arg GetWorkflowRunParams) (GetWorkflowRunRow, error) {
	row := q.db.QueryRow(ctx, getWorkflowRun, arg.OrgID, arg.ID)
	var i GetWorkflowRunRow
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Status,
		&i.TriggeredBy,
	)
	return i, err
}

const insertWorkflow = `-- name: InsertWorkflow :one
INSERT INTO workflows (
    org_id, agent_id, name, description, trigger_type, graph_definition,
    cron_expression, next_run_at, requires_approval, task_input_template,
    estimated_manual_minutes, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, agent_id, name, description, trigger_type, cron_expression,
    timezone, next_run_at, requires_approval, task_input_template,
    estimated_manual_minutes, is_active, version, created_at, updated_at
`

type InsertWorkflowParams struct {
	OrgID                  pgtype.UUID        `json:"org_id"`
	AgentID                pgtype.UUID        `json:"agent_id"`
	Name                   string             `json:"name"`
	Description            *string            `json:"description"`
	TriggerType            string             `json:"trigger_type"`
	GraphDefinition        []byte             `json:"graph_definition"`
	CronExpression         *string            `json:"cron_expression"`
	NextRunAt              pgtype.Timestamptz `json:"next_run_at"`
	RequiresApproval       *bool              `json:"requires_approval"`
	TaskInputTemplate      *string            `json:"task_input_template"`
	EstimatedManualMinutes *int32             `json:"estimated_manual_minutes"`
	CreatedBy              pgtype.UUID        `json:"created_by"`
}

type InsertWorkflowRow struct {
	ID                     pgtype.UUID        `json:"id"`
	AgentID                pgtype.UUID        `json:"agent_id"`
	Name                   string             `json:"name"`
	Description            *string            `json:"description"`
	TriggerType            string             `json:"trigger_type"`
	CronExpression         *string            `json:"cron_expression"`
	Timezone               *string            `json:"timezone"`
	NextRunAt              pgtype.Timestamptz `json:"next_run_at"`
	RequiresApproval       *bool              `json:"requires_approval"`
	TaskInputTemplate      *string            `json:"task_input_template"`
	EstimatedManualMinutes *int32             `json:"estimated_manual_minutes"`
	IsActive               *bool              `json:"is_active"`
	Version                *int32             `json:"version"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

// graph_definition is fixed, not user-configurable — every workflow runs
// the same planner -> rag_retriever -> executor -> validator -> reporter
// pipeline (Workflow 9's node list); nothing in this workflow's spec lets
// a founder customize the graph shape itself, only the trigger/schedule
// and the agent + task input that pipeline runs against.
func (q *Queries) InsertWorkflow(ctx context.Context, arg InsertWorkflowParams) (InsertWorkflowRow, error) {
	row := q.db.QueryRow(ctx, insertWorkflow,
		arg.OrgID,
		arg.AgentID,
		arg.Name,
		arg.Description,
		arg.TriggerType,
		arg.GraphDefinition,
		arg.CronExpression,
		arg.NextRunAt,
		arg.RequiresApproval,
		arg.TaskInputTemplate,
		arg.EstimatedManualMinutes,
		arg.CreatedBy,
	)
	var i InsertWorkflowRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Name,
		&i.Description,
		&i.TriggerType,
		&i.CronExpression,
		&i.Timezone,
		&i.NextRunAt,
		&i.RequiresApproval,
		&i.TaskInputTemplate,
		&i.EstimatedManualMinutes,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWorkflowRun = `-- name: InsertWorkflowRun :one
INSERT INTO workflow_runs (workflow_id, org_id, triggered_by, status)
VALUES ($1, $2, $3, 'pending')
RETURNING id, status, created_at
`

type InsertWorkflowRunParams struct {
	WorkflowID  pgtype.UUID `json:"workflow_id"`
	OrgID       pgtype.UUID `json:"org_id"`
	TriggeredBy pgtype.UUID `json:"triggered_by"`
}

type InsertWorkflowRunRow struct {
	ID        pgtype.UUID        `json:"id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// "Run Now" and the scheduler both stop here — INSERT a pending run row,
// nothing consumes it yet. See CLAUDE.md's workflow 8 section: turning
// 'pending' rows into actual execution is Workflow 9's job
// (internal/core/graph, not built).
func (q *Queries) InsertWorkflowRun(ctx context.Context, arg InsertWorkflowRunParams) (InsertWorkflowRunRow, error) {
	row := q.db.QueryRow(ctx, insertWorkflowRun, arg.WorkflowID, arg.OrgID, arg.TriggeredBy)
	var i InsertWorkflowRunRow
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const listDueScheduledWorkflows = `-- name: ListDueScheduledWorkflows :many

SELECT id, org_id, cron_expression FROM workflows
WHERE trigger_type = 'scheduled' AND is_active = true AND next_run_at <= now()
`

type ListDueScheduledWorkflowsRow struct {
	ID             pgtype.UUID `json:"id"`
	OrgID          pgtype.UUID `json:"org_id"`
	CronExpression *string     `json:"cron_expression"`
}

// Background scheduler (internal/core/workflows/scheduler.go) — app_system,
// never tenant.WithTx; see the file-level comment above.
func (q *Queries) ListDueScheduledWorkflows(ctx context.Context) ([]ListDueScheduledWorkflowsRow, error) {
	rows, err := q.db.Query(ctx, listDueScheduledWorkflows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueScheduledWorkflowsRow
	for rows.Next() {
		var i ListDueScheduledWorkflowsRow
		if err := rows.Scan(&i.ID, &i.OrgID, &i.CronExpression); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT w.id, w.agent_id, a.name AS agent_name, w.name, w.description,
       w.trigger_type, w.cron_expression, w.timezone, w.next_run_at,
       w.requires_approval, w.task_input_template, w.estimated_manual_minutes,
       w.is_active, w.version, w.created_at, w.updated_at
FROM workflows w
JOIN agents a ON a.id = w.agent_id
WHERE w.org_id = $1
ORDER BY w.created_at DESC
`

type ListWorkflowsRow struct {
	ID                     pgtype.UUID        `json:"id"`
	AgentID                pgtype.UUID        `json:"agent_id"`
	AgentName              string             `json:"agent_name"`
	Name                   string             `json:"name"`
	Description            *string            `json:"description"`
	TriggerType            string             `json:"trigger_type"`
	CronExpression         *string            `json:"cron_expression"`
	Timezone               *string            `json:"timezone"`
	NextRunAt              pgtype.Timestamptz `json:"next_run_at"`
	RequiresApproval       *bool              `json:"requires_approval"`
	TaskInputTemplate      *string            `json:"task_input_template"`
	EstimatedManualMinutes *int32             `json:"estimated_manual_minutes"`
	IsActive               *bool              `json:"is_active"`
	Version                *int32             `json:"version"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

// Deliberately NOT filtered by is_active, unlike ListAgents/ListDocuments
// — pausing a workflow (PATCH is_active=false) must keep it visible so the
// founder can toggle it back on; is_active in the response drives the
// pause/resume toggle and "Paused" badge client-side. agent_name comes via
// a plain JOIN, not a nullable LEFT JOIN: agent_id is NOT NULL and agents
// are only ever soft-deleted (never actually removed), so the referenced
// row always exists.
func (q *Queries) ListWorkflows(ctx context.Context, orgID pgtype.UUID) ([]ListWorkflowsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflows, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowsRow
	for rows.Next() {
		var i ListWorkflowsRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.AgentName,
			&i.Name,
			&i.Description,
			&i.TriggerType,
			&i.CronExpression,
			&i.Timezone,
			&i.NextRunAt,
			&i.RequiresApproval,
			&i.TaskInputTemplate,
			&i.EstimatedManualMinutes,
			&i.IsActive,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const systemInsertWorkflowRun = `-- name: SystemInsertWorkflowRun :exec
INSERT INTO workflow_runs (workflow_id, org_id, status)
VALUES ($1, $2, 'pending')
`

type SystemInsertWorkflowRunParams struct {
	WorkflowID pgtype.UUID `json:"workflow_id"`
	OrgID      pgtype.UUID `json:"org_id"`
}

// Same shape as InsertWorkflowRun (triggered_by is NULL — the system, not
// a user, triggered this one), used because the scheduler has no
// per-request user/org session to run InsertWorkflowRun's tenant.WithTx
// variant under.
func (q *Queries) SystemInsertWorkflowRun(ctx context.Context, arg SystemInsertWorkflowRunParams) error {
	_, err := q.db.Exec(ctx, systemInsertWorkflowRun, arg.WorkflowID, arg.OrgID)
	return err
}

const updateWorkflow = `-- name: UpdateWorkflow :one
UPDATE workflows SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    trigger_type = COALESCE($3, trigger_type),
    cron_expression = $4,
    next_run_at = $5,
    requires_approval = COALESCE($6, requires_approval),
    task_input_template = COALESCE($7, task_input_template),
    estimated_manual_minutes = COALESCE($8, estimated_manual_minutes),
    is_active = COALESCE($9, is_active),
    version = version + 1
WHERE org_id = $10 AND id = $11
RETURNING id, agent_id, name, description, trigger_type, cron_expression,
    timezone, next_run_at, requires_approval, task_input_template,
    estimated_manual_minutes, is_active, version, created_at, updated_at
`

type UpdateWorkflowParams struct {
	Name                   *string            `json:"name"`
	Description            *string            `json:"description"`
	TriggerType            *string            `json:"trigger_type"`
	CronExpression         *string            `json:"cron_expression"`
	NextRunAt              pgtype.Timestamptz `json:"next_run_at"`
	RequiresApproval       *bool              `json:"requires_approval"`
	TaskInputTemplate      *string            `json:"task_input_template"`
	EstimatedManualMinutes *int32             `json:"estimated_manual_minutes"`
	IsActive               *bool              `json:"is_active"`
	OrgID                  pgtype.UUID        `json:"org_id"`
	ID                     pgtype.UUID        `json:"id"`
}

type UpdateWorkflowRow struct {
	ID                     pgtype.UUID        `json:"id"`
	AgentID                pgtype.UUID        `json:"agent_id"`
	Name                   string             `json:"name"`
	Description            *string            `json:"description"`
	TriggerType            string             `json:"trigger_type"`
	CronExpression         *string            `json:"cron_expression"`
	Timezone               *string            `json:"timezone"`
	NextRunAt              pgtype.Timestamptz `json:"next_run_at"`
	RequiresApproval       *bool              `json:"requires_approval"`
	TaskInputTemplate      *string            `json:"task_input_template"`
	EstimatedManualMinutes *int32             `json:"estimated_manual_minutes"`
	IsActive               *bool              `json:"is_active"`
	Version                *int32             `json:"version"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

// Partial update via COALESCE, same convention as UpdateAgent — but
// trigger_type/cron_expression/next_run_at are 3 fields the *handler*
// treats as one coupled unit (see internal/api/workflows/handler.go's
// Update): it always passes explicit values for all 3 together, computed
// from the effective (existing-unless-overridden) trigger config, rather
// than relying on COALESCE to reconcile them independently — a bare
// COALESCE per-field could otherwise land on a state like
// trigger_type='scheduled' with a stale or absent cron_expression.
// agent_id is intentionally not updatable here — reassigning a workflow to
// a different agent isn't part of this workflow's spec.
func (q *Queries) UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (UpdateWorkflowRow, error) {
	row := q.db.QueryRow(ctx, updateWorkflow,
		arg.Name,
		arg.Description,
		arg.TriggerType,
		arg.CronExpression,
		arg.NextRunAt,
		arg.RequiresApproval,
		arg.TaskInputTemplate,
		arg.EstimatedManualMinutes,
		arg.IsActive,
		arg.OrgID,
		arg.ID,
	)
	var i UpdateWorkflowRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Name,
		&i.Description,
		&i.TriggerType,
		&i.CronExpression,
		&i.Timezone,
		&i.NextRunAt,
		&i.RequiresApproval,
		&i.TaskInputTemplate,
		&i.EstimatedManualMinutes,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkflowNextRunAt = `-- name: UpdateWorkflowNextRunAt :exec
UPDATE workflows SET next_run_at = $2 WHERE id = $1
`

type UpdateWorkflowNextRunAtParams struct {
	ID        pgtype.UUID        `json:"id"`
	NextRunAt pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) UpdateWorkflowNextRunAt(ctx context.Context, arg UpdateWorkflowNextRunAtParams) error {
	_, err := q.db.Exec(ctx, updateWorkflowNextRunAt, arg.ID, arg.NextRunAt)
	return err
}

const validateAgentForOrg = `-- name: ValidateAgentForOrg :one

SELECT id, name FROM agents WHERE org_id = $1 AND id = $2 AND is_active = true
`

type ValidateAgentForOrgParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

type ValidateAgentForOrgRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

// Queries backing workflow 8 (workflow config CRUD + scheduling). Most are
// tenant-scoped through app_user via tenant.WithTx, like every other
// feature area in this file set. The 3 queries under "background
// scheduler" are the deliberate exception — the scheduler scans due
// workflows across every org, which is inherently a cross-tenant
// system-context operation, so those run on app_system directly, same
// reasoning as internal/core/integrations/refresh.go's RunRefreshJob and
// internal/core/documents/recover.go's RecoverStuckJobs.
// Used at create time to confirm the agent_id a workflow is being pointed
// at both belongs to this org and is still active — you shouldn't be able
// to assign a workflow to a deactivated agent. Also returns name so the
// Create response can embed agent_name without a second query.
func (q *Queries) ValidateAgentForOrg(ctx context.Context, arg ValidateAgentForOrgParams) (ValidateAgentForOrgRow, error) {
	row := q.db.QueryRow(ctx, validateAgentForOrg, arg.OrgID, arg.ID)
	var i ValidateAgentForOrgRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
