REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM app_system;
REVOKE USAGE ON SCHEMA public FROM app_system;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM app_system;
DROP OWNED BY app_system;
DROP ROLE IF EXISTS app_system;
